# 📝 Ćwiczenia Praktyczne: Moduł 030 (Praca ze Strukturą Series)

### 📋 Zadanie 1: Statystyki, ekstrema i brakujące dane

Dla serii ocen: `s = pd.Series([4.5, 3.0, 5.0, 2.0, np.nan, 5.0, 4.0])`:
1. Oblicz liczbę braków za pomocą `.isnull().sum()`.
2. Wypełnij brakujące wartości średnią ocen.
3. Wyznacz 2 najwyższe oceny za pomocą metody `.nlargest(2)`.

In [4]:
# TUTAJ WPISZ SWÓJ KOD:
import pandas as pd
import numpy as np

s = pd.Series([4.5, 3.0, 5.0, 2.0, np.nan, 5.0, 4.0])
# Twój kod poniżej:

#### 💡 Rozwiązanie wzorcowe (kliknij komórkę poniżej aby podejrzeć):

In [ ]:
# ROZWIĄZANIE WZORCOWE:
print('Liczba braków:', s.isnull().sum())
s_uzupelnione = s.fillna(s.mean())
print('Top 2 oceny:\n', s_uzupelnione.nlargest(2))

### 📋 Zadanie 2: Slicing i resetowanie indeksu z drop=True

Z serii cen `ceny = pd.Series([15, 80, 25, 120, 45], index=list('abcde'))` wybierz produkty droższe niż 30 zł i zresetuj indeks tak, aby usunąć stare etykiety (`drop=True`).

In [5]:
# TUTAJ WPISZ SWÓJ KOD:
ceny = pd.Series([15, 80, 25, 120, 45], index=list('abcde'))
# Twój kod poniżej:

In [6]:
ceny

a     15
b     80
c     25
d    120
e     45
dtype: int64

In [10]:
ceny.reset_index(drop=True)

0     15
1     80
2     25
3    120
4     45
dtype: int64

In [14]:
nowe_ceny = ceny[ceny > 30]
nowe_ceny

b     80
d    120
e     45
dtype: int64

In [15]:
nowe_ceny

b     80
d    120
e     45
dtype: int64

In [17]:
ceny["a"]

np.int64(15)

In [16]:
nowe_ceny['a']

KeyError: 'a'

In [19]:
ceny[ceny > 30].reset_index(drop=True)

0     80
1    120
2     45
dtype: int64

In [30]:
s1 = pd.Series([1,1,1,1,1], index = ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([1,1,1,1,1], index=["a", "x", "y", "d", "z"])

In [31]:
s1

a    1
b    1
c    1
d    1
e    1
dtype: int64

In [32]:
s2

a    1
x    1
y    1
d    1
z    1
dtype: int64

In [33]:
s1+s2

a    2.0
b    NaN
c    NaN
d    2.0
e    NaN
x    NaN
y    NaN
z    NaN
dtype: float64

In [ ]:
s1.add(s2, fill_value=0)

a      2.0
b   -998.0
c   -998.0
d      2.0
e   -998.0
x   -998.0
y   -998.0
z   -998.0
dtype: float64

In [36]:
df = pd.DataFrame({"zarobki": [1000, 2000, 3000, 4000, 5500],
                   "nazwisko": ["Nowak", "Kowalski", "Iksiński", "Dyrman", "Wójcik"]})
df

   zarobki  nazwisko
0     1000     Nowak
1     2000  Kowalski
2     3000  Iksiński
3     4000    Dyrman
4     5500    Wójcik

In [38]:
# wszyscy którzy zarabiają > 3500 do zwolnienia
df['czy_zwolnic'] = np.where(df["zarobki"] > 3500, "zwalniamy", "pracuje")
df

   zarobki  nazwisko czy_zwolnic
0     1000     Nowak     pracuje
1     2000  Kowalski     pracuje
2     3000  Iksiński     pracuje
3     4000    Dyrman   zwalniamy
4     5500    Wójcik   zwalniamy

In [40]:
df.where(df["zarobki"] > 3500).dropna()

   zarobki nazwisko czy_zwolnic
3   4000.0   Dyrman   zwalniamy
4   5500.0   Wójcik   zwalniamy