# 📝 Ćwiczenia Praktyczne: Moduł 040 (Praca z DataFrame)

Zadania obejmujące selekcję, diagnostykę, czyszczenie braków z parametrem **`subset`**, deduplikację, sortowanie wielokolumnowe oraz `itertuples()`.

### 📋 Zadanie 1: Selektywne czyszczenie braków z parametrem subset

W tabeli zamówień usuń TYLKO te wiersze, w których brakuje kwoty transakcji (`subset=['kwota']`). Rekordy z brakującym emailem powinny pozostać w bazie.

In [2]:
# TUTAJ WPISZ SWÓJ KOD:
import pandas as pd
import numpy as np

df_zam = pd.DataFrame({
    'id': [1, 2, 3, 4],
    'klient': ['Jan', 'Anna', 'Piotr', 'Maria'],
    'kwota': [150.0, np.nan, 220.0, np.nan],
    'email': ['jan@a.pl', None, 'piotr@c.pl', None]
})
# Twój kod poniżej:
df_zam

   id klient  kwota       email
0   1    Jan  150.0    jan@a.pl
1   2   Anna    NaN         NaN
2   3  Piotr  220.0  piotr@c.pl
3   4  Maria    NaN         NaN

#### 💡 Rozwiązanie wzorcowe (kliknij komórkę poniżej aby podejrzeć):

In [3]:
# ROZWIĄZANIE WZORCOWE:
df_czyste = df_zam.dropna(subset=['kwota'], ignore_index=True)
print(df_czyste)

   id klient  kwota       email
0   1    Jan  150.0    jan@a.pl
1   3  Piotr  220.0  piotr@c.pl

### 📋 Zadanie 2: Deduplikacja z zachowaniem najnowszego rekordu (keep='last')

Posortuj logi według kolumny `'data'` i usuń duplikaty użytkownika (`subset=['user']`), zachowując wyłącznie jego ostatnie logowanie (`keep='last'`).

In [6]:
# TUTAJ WPISZ SWÓJ KOD:
df_logi = pd.DataFrame({
    'user': ['jan', 'anna', 'jan', 'piotr'],
    'data': ['2024-01-01', '2024-01-02', '2024-01-05', '2024-01-03'],
    'ip': ['1.1.1.1', '2.2.2.2', '1.1.1.9', '3.3.3.3']
})
# Twój kod poniżej:
df_logi

    user        data       ip
0    jan  2024-01-01  1.1.1.1
1   anna  2024-01-02  2.2.2.2
2    jan  2024-01-05  1.1.1.9
3  piotr  2024-01-03  3.3.3.3

#### 💡 Rozwiązanie wzorcowe (kliknij komórkę poniżej aby podejrzeć):

In [7]:
# ROZWIĄZANIE WZORCOWE:
df_posortowane = df_logi.sort_values(by='data')
df_unikalne = df_posortowane.drop_duplicates(subset=['user'], keep='last', ignore_index=True)
print(df_unikalne)

    user        data       ip
0   anna  2024-01-02  2.2.2.2
1  piotr  2024-01-03  3.3.3.3
2    jan  2024-01-05  1.1.1.9

### 📋 Zadanie 3: Sortowanie wielokolumnowe z różnymi kierunkami

Posortuj poniższą tabelę tak, aby `'Dzial'` był posortowany rosnąco (A-Z), a `'Pensja'` malejąco (od najwyższej).

In [9]:
# TUTAJ WPISZ SWÓJ KOD:
df_pracownicy = pd.DataFrame({
    'Dzial': ['IT', 'Marketing', 'IT', 'Marketing', 'Finanse'],
    'Pracownik': ['Jan', 'Ewa', 'Anna', 'Piotr', 'Zofia'],
    'Pensja': [8000, 7500, 14000, 11000, 15000]
})
# Twój kod poniżej:
df_pracownicy

       Dzial Pracownik  Pensja
0         IT       Jan    8000
1  Marketing       Ewa    7500
2         IT      Anna   14000
3  Marketing     Piotr   11000
4    Finanse     Zofia   15000

#### 💡 Rozwiązanie wzorcowe (kliknij komórkę poniżej aby podejrzeć):

In [10]:
# ROZWIĄZANIE WZORCOWE:
df_posortowani = df_pracownicy.sort_values(by=['Dzial', 'Pensja'], ascending=[True, False], ignore_index=True)
print(df_posortowani)

       Dzial Pracownik  Pensja
0    Finanse     Zofia   15000
1         IT      Anna   14000
2         IT       Jan    8000
3  Marketing     Piotr   11000
4  Marketing       Ewa    7500

### 📋 Zadanie 4: Bezpieczna iteracja z .itertuples()

Napisz pętlę wykorzystującą `df_pracownicy.itertuples()`, która wyświetli tekst: `'Pracownik: {Pracownik} zarabia {Pensja} zł w dziale {Dzial}'`.

In [11]:
# TUTAJ WPISZ SWÓJ KOD:
# Twój kod poniżej:
for pracownik in df_pracownicy.itertuples():
    print(
        f"Pracownik: {pracownik.Pracownik} zarabia {pracownik.Pensja} zł w dziale {pracownik.Dzial}"
    )

Pracownik: Jan zarabia 8000 zł w dziale IT
Pracownik: Ewa zarabia 7500 zł w dziale Marketing
Pracownik: Anna zarabia 14000 zł w dziale IT
Pracownik: Piotr zarabia 11000 zł w dziale Marketing
Pracownik: Zofia zarabia 15000 zł w dziale Finanse

#### 💡 Rozwiązanie wzorcowe (kliknij komórkę poniżej aby podejrzeć):

In [ ]:
# ROZWIĄZANIE WZORCOWE:
for r in df_pracownicy.itertuples():
    print(f'Pracownik: {r.Pracownik} zarabia {r.Pensja} zł w dziale {r.Dzial}')