In [1]:
import pandas as pd
import numpy as np

In [2]:
# seria z samymi wartościami  -zwróć uwagę na indeks i nazwe
ceny = pd.Series([12.50, 45.00, 8.99, 120.00, 24.50, 65.00, 45.00])
ceny

0     12.50
1     45.00
2      8.99
3    120.00
4     24.50
5     65.00
6     45.00
dtype: float64

In [3]:
# seria z  wartościami i indeksem  -zwróć uwagę na indeks i nazwe
ceny = pd.Series(
    [12.50, 45.00, 8.99, 120.00, 24.50, 65.00, 45.00],
    index=["Kawa", "Herbata", "Woda", "Wino", "Sok", "Miód", "Ciastko"],
)
ceny

Kawa        12.50
Herbata     45.00
Woda         8.99
Wino       120.00
Sok         24.50
Miód        65.00
Ciastko     45.00
dtype: float64

In [4]:
# seria z wartościami, indeksem i nazwą
ceny = pd.Series(
    [12.50, 45.00, 8.99, 120.00, 24.50, 65.00, 45.00],
    index=["Kawa", "Herbata", "Woda", "Wino", "Sok", "Miód", "Ciastko"],
    name="Cena_PLN",
)
ceny

Kawa        12.50
Herbata     45.00
Woda         8.99
Wino       120.00
Sok         24.50
Miód        65.00
Ciastko     45.00
Name: Cena_PLN, dtype: float64

In [5]:
# wartości
ceny.values

array([ 12.5 ,  45.  ,   8.99, 120.  ,  24.5 ,  65.  ,  45.  ])

In [6]:
# indeks
ceny.index

Index(['Kawa', 'Herbata', 'Woda', 'Wino', 'Sok', 'Miód', 'Ciastko'], dtype='str')

In [7]:
# typ danych w serii
ceny.dtypes

dtype('float64')

In [8]:
# unikalność - tylko uniklane wartości w serii
ceny.unique()

array([ 12.5 ,  45.  ,   8.99, 120.  ,  24.5 ,  65.  ])

In [9]:
# ile jest unikalnych
ceny.nunique()

6

In [10]:
# opisowe statystyki
ceny.describe()

count      7.000000
mean      45.855714
std       38.282055
min        8.990000
25%       18.500000
50%       45.000000
75%       55.000000
max      120.000000
Name: Cena_PLN, dtype: float64

In [11]:
# wybieranie wartości = slicing

In [12]:
ceny.Miód

np.float64(65.0)

In [13]:
ceny."Miód lipowy"

SyntaxError: invalid syntax (2105079492.py, line 1)

In [ ]:
lista = [0,1,2,3,4,5,6]
lista[3:5]

In [ ]:
# .loc -> indeksowanie po nazwach indeksu, zamknięte z obu stron
ceny.loc["Herbata" : "Miód"]

In [ ]:
# 0 Kawa        12.50
# 1 Herbata     45.00
# 2 Woda         8.99
# 3 Wino       120.00
# 4 Sok         24.50
# 5 Miód        65.00
# 6 Ciastko     45.00
# Name: Cena_PLN, dtype: float64

In [ ]:
# .iloc -> indeksowanie po numerach wierszy od zera, przedział otwarty z prawej
ceny.iloc[1:5]

In [ ]:
# .iloc - ujemne indeksy
ceny.iloc[-3:]

In [ ]:
# .iloc - co któryś element
ceny.iloc[::2]

In [ ]:
# .iloc - lista od końca
ceny.iloc[::-1]

In [ ]:
ceny['Herbata']

In [ ]:
ceny.at["Herbata"]

In [ ]:
ceny.iat[4]

In [ ]:
ceny.values[4]

In [ ]:
ceny

In [ ]:
# statystyka serii
ceny.sum()

In [ ]:
ceny.min()

In [ ]:
ceny.max()

In [ ]:
ceny.std()

In [ ]:
ceny.mean()

In [ ]:
ceny.median()

In [ ]:
# n-najwiekszych
ceny.nlargest(3)

In [ ]:
ceny.nsmallest(3)

In [ ]:
s = pd.Series([4.5, 3.0, 5.0, 2.0, np.nan, 5.0, np.nan, 4.0])
s

In [ ]:
# usuwanie braków
s.dropna()

In [ ]:
# uzupełnianie braków
s.fillna(-999)

In [ ]:
s.fillna(s.mean())

In [ ]:
s.isnull()

In [ ]:
s.isnull().sum()

In [15]:
# sortowanie
s = pd.Series([4.5, 3.0, 5.0, 2.0, np.nan, 5.0, np.nan, 4.0])
s

0    4.5
1    3.0
2    5.0
3    2.0
4    NaN
5    5.0
6    NaN
7    4.0
dtype: float64

In [18]:
s.sort_values()

3    2.0
1    3.0
7    4.0
0    4.5
2    5.0
5    5.0
4    NaN
6    NaN
dtype: float64

In [ ]:
s.sort_values(na_position='first')

4    NaN
6    NaN
3    2.0
1    3.0
7    4.0
0    4.5
2    5.0
5    5.0
dtype: float64

In [ ]:
s.sort_values(ascending=True) # kolejnosć - domyślnie od malejących do rosnących

3    2.0
1    3.0
7    4.0
0    4.5
2    5.0
5    5.0
4    NaN
6    NaN
dtype: float64

In [20]:
s.sort_values(ascending=False)

5    5.0
2    5.0
0    4.5
7    4.0
1    3.0
3    2.0
4    NaN
6    NaN
dtype: float64

In [24]:
imiona = pd.Series(
    [
        "Jan",
        "Antoni",
        "Jakub",
        "Franciszek",
        np.nan,
        "Aleksander",
        "Szymon",
        "Mikołaj",
        "Filip",
        "Stanisław",
        "Wojciech",
        "Aleksander",
        "Szymon",
        "Mikołaj",
        np.nan,
        "Filip",
        "Stanisław",
        "Wojciech",
        "Szymon",
        "Mikołaj",
        "Filip",
        "Stanisław",
        "Wojciech",
        "Aleksander",
        "Szymon",
        "Mikołaj",
        "Filip",
        np.nan,
        "Stanisław",
        "Wojciech",
        "Szymon",
        "Mikołaj",
        "Filip",
        "Stanisław",
        "Jan",
        "Antoni",
        "Jakub",
        "Franciszek",
        "Aleksander",
        "Szymon",
    ]
)

imiona

0            Jan
1         Antoni
2          Jakub
3     Franciszek
4            NaN
5     Aleksander
6         Szymon
7        Mikołaj
8          Filip
9      Stanisław
10      Wojciech
11    Aleksander
12        Szymon
13       Mikołaj
14           NaN
15         Filip
16     Stanisław
17      Wojciech
18        Szymon
19       Mikołaj
20         Filip
21     Stanisław
22      Wojciech
23    Aleksander
24        Szymon
25       Mikołaj
26         Filip
27           NaN
28     Stanisław
29      Wojciech
30        Szymon
31       Mikołaj
32         Filip
33     Stanisław
34           Jan
35        Antoni
36         Jakub
37    Franciszek
38    Aleksander
39        Szymon
dtype: str

In [ ]:
# zliczanie wartości w serii - zwróć uwagę na NaN - pominięty!
imiona.value_counts()

Szymon        6
Mikołaj       5
Filip         5
Stanisław     5
Aleksander    4
Wojciech      4
Jan           2
Antoni        2
Jakub         2
Franciszek    2
Name: count, dtype: int64

In [26]:
imiona.value_counts(dropna=False)

Szymon        6
Mikołaj       5
Filip         5
Stanisław     5
Aleksander    4
Wojciech      4
NaN           3
Jan           2
Antoni        2
Jakub         2
Franciszek    2
Name: count, dtype: int64

In [ ]:
# ile % - częstość występowania
imiona.value_counts(dropna=False, normalize=True) * 100

Szymon        15.0
Mikołaj       12.5
Filip         12.5
Stanisław     12.5
Aleksander    10.0
Wojciech      10.0
NaN            7.5
Jan            5.0
Antoni         5.0
Jakub          5.0
Franciszek     5.0
Name: proportion, dtype: float64

In [34]:
# "kubełkowanie" - tylko loczby
liczby = pd.Series(np.random.normal(50, 10, size=1000))
liczby

0      40.812337
1      58.760371
2      57.992097
3      51.990594
4      37.980545
         ...
995    37.095251
996    41.578237
997    45.711705
998    52.706775
999    37.042789
Length: 1000, dtype: float64

In [35]:
liczby.sort_values()

471    17.086732
600    22.520761
681    23.700775
189    24.988150
450    25.177887
         ...
75     75.545605
43     76.660833
403    80.467071
193    84.342921
297    85.775395
Length: 1000, dtype: float64

In [36]:
liczby.value_counts(bins=4)

(34.259, 51.431]    500
(51.431, 68.603]    414
(17.017, 34.259]     56
(68.603, 85.775]     30
Name: count, dtype: int64

In [39]:
# mapowanie
slownik = {
 "PL": "Polska",
 "DE": "Niemcy",
 "FR": "Francja",
 "GB": "Wielka Brytania",
 "IT": "Włochy",
 "ES": "Hiszpania",
 "NL": "Holandia",
 "CH": "Szwajcaria",
 "SE": "Szwecja",
 "NO": "Norwegia",
}

kraje = pd.Series(
    [
        "PL",
        "DE",
        "FR",
        "GB",
        "IT",
        "ES",
        "NL",
        "CH",
        "SE",
        "NO",
        "FR",
        "GB",
        "IT",
        "CH",
        "SE",
        "NO",
        "FR",
        "GB",
        "ES",
        "NL",
        "CH",
        "SE",
        "USA"
    ]
)

kraje

0      PL
1      DE
2      FR
3      GB
4      IT
5      ES
6      NL
7      CH
8      SE
9      NO
10     FR
11     GB
12     IT
13     CH
14     SE
15     NO
16     FR
17     GB
18     ES
19     NL
20     CH
21     SE
22    USA
dtype: str

In [40]:
# mapowanie skrótów na nazwy
kraje.map(slownik)

0              Polska
1              Niemcy
2             Francja
3     Wielka Brytania
4              Włochy
5           Hiszpania
6            Holandia
7          Szwajcaria
8             Szwecja
9            Norwegia
10            Francja
11    Wielka Brytania
12             Włochy
13         Szwajcaria
14            Szwecja
15           Norwegia
16            Francja
17    Wielka Brytania
18          Hiszpania
19           Holandia
20         Szwajcaria
21            Szwecja
22                NaN
dtype: str

In [47]:
# mapowanie funkcją
def mapowanie(s):
    if s == "USA":
        return "Ameryka panie!"
    return 1 if s[0] < "K" else 0

In [48]:
mapowanie("GB"), mapowanie("PL"), mapowanie("USA")

(1, 0, 'Ameryka panie!')

In [49]:
kraje.map(mapowanie)

0                  0
1                  1
2                  1
3                  1
4                  1
5                  1
6                  0
7                  1
8                  0
9                  0
10                 1
11                 1
12                 1
13                 1
14                 0
15                 0
16                 1
17                 1
18                 1
19                 0
20                 1
21                 0
22    Ameryka panie!
dtype: object

In [57]:
df = pd.DataFrame({"iso_kraju": kraje})
df

   iso_kraju
0         PL
1         DE
2         FR
3         GB
4         IT
5         ES
6         NL
7         CH
8         SE
9         NO
10        FR
11        GB
12        IT
13        CH
14        SE
15        NO
16        FR
17        GB
18        ES
19        NL
20        CH
21        SE
22       USA

In [60]:
df['nazwa_kraju'] = df['iso_kraju'].map(slownik)
df

   iso_kraju      nazwa_kraju
0         PL           Polska
1         DE           Niemcy
2         FR          Francja
3         GB  Wielka Brytania
4         IT           Włochy
5         ES        Hiszpania
6         NL         Holandia
7         CH       Szwajcaria
8         SE          Szwecja
9         NO         Norwegia
10        FR          Francja
11        GB  Wielka Brytania
12        IT           Włochy
13        CH       Szwajcaria
14        SE          Szwecja
15        NO         Norwegia
16        FR          Francja
17        GB  Wielka Brytania
18        ES        Hiszpania
19        NL         Holandia
20        CH       Szwajcaria
21        SE          Szwecja
22       USA              NaN

In [58]:
slownik_df = pd.DataFrame(slownik.items())
slownik_df.columns = ['iso', 'nazwa']
slownik_df

  iso            nazwa
0  PL           Polska
1  DE           Niemcy
2  FR          Francja
3  GB  Wielka Brytania
4  IT           Włochy
5  ES        Hiszpania
6  NL         Holandia
7  CH       Szwajcaria
8  SE          Szwecja
9  NO         Norwegia

In [59]:
pd.merge(df, slownik_df, how="left", left_on="iso_kraju", right_on="iso")

   iso_kraju  iso            nazwa
0         PL   PL           Polska
1         DE   DE           Niemcy
2         FR   FR          Francja
3         GB   GB  Wielka Brytania
4         IT   IT           Włochy
5         ES   ES        Hiszpania
6         NL   NL         Holandia
7         CH   CH       Szwajcaria
8         SE   SE          Szwecja
9         NO   NO         Norwegia
10        FR   FR          Francja
11        GB   GB  Wielka Brytania
12        IT   IT           Włochy
13        CH   CH       Szwajcaria
14        SE   SE          Szwecja
15        NO   NO         Norwegia
16        FR   FR          Francja
17        GB   GB  Wielka Brytania
18        ES   ES        Hiszpania
19        NL   NL         Holandia
20        CH   CH       Szwajcaria
21        SE   SE          Szwecja
22       USA  NaN              NaN

In [ ]:
# pd.merge(df, slownik_df, how="left", left_on="iso_kraju", right_on="iso")
# vs
# df['nazwa_kraju'] = df['iso_kraju'].map(slownik)

In [ ]:
def male_litery(s):
    return str(s).lower()

df["nazwa_kraju"].apply(male_litery)

In [62]:
male_litery("fwgwgWEGWEFwefwvw")

'fwgwgwegwefwefwvw'

In [66]:
df["nazwa_kraju"].map(male_litery)

0              polska
1              niemcy
2             francja
3     wielka brytania
4              włochy
5           hiszpania
6            holandia
7          szwajcaria
8             szwecja
9            norwegia
10            francja
11    wielka brytania
12             włochy
13         szwajcaria
14            szwecja
15           norwegia
16            francja
17    wielka brytania
18          hiszpania
19           holandia
20         szwajcaria
21            szwecja
22                nan
Name: nazwa_kraju, dtype: str

In [68]:
df["nazwa_kraju"].apply(male_litery)

0              polska
1              niemcy
2             francja
3     wielka brytania
4              włochy
5           hiszpania
6            holandia
7          szwajcaria
8             szwecja
9            norwegia
10            francja
11    wielka brytania
12             włochy
13         szwajcaria
14            szwecja
15           norwegia
16            francja
17    wielka brytania
18          hiszpania
19           holandia
20         szwajcaria
21            szwecja
22                nan
Name: nazwa_kraju, dtype: str

In [ ]:
df["nazwa_kraju"].apply(lambda s: str(s).upper())

0              POLSKA
1              NIEMCY
2             FRANCJA
3     WIELKA BRYTANIA
4              WŁOCHY
5           HISZPANIA
6            HOLANDIA
7          SZWAJCARIA
8             SZWECJA
9            NORWEGIA
10            FRANCJA
11    WIELKA BRYTANIA
12             WŁOCHY
13         SZWAJCARIA
14            SZWECJA
15           NORWEGIA
16            FRANCJA
17    WIELKA BRYTANIA
18          HISZPANIA
19           HOLANDIA
20         SZWAJCARIA
21            SZWECJA
22                NAN
Name: nazwa_kraju, dtype: str

In [70]:
df["nazwa_kraju"].map(lambda s: str(s).upper())

0              POLSKA
1              NIEMCY
2             FRANCJA
3     WIELKA BRYTANIA
4              WŁOCHY
5           HISZPANIA
6            HOLANDIA
7          SZWAJCARIA
8             SZWECJA
9            NORWEGIA
10            FRANCJA
11    WIELKA BRYTANIA
12             WŁOCHY
13         SZWAJCARIA
14            SZWECJA
15           NORWEGIA
16            FRANCJA
17    WIELKA BRYTANIA
18          HISZPANIA
19           HOLANDIA
20         SZWAJCARIA
21            SZWECJA
22                NAN
Name: nazwa_kraju, dtype: str

In [77]:
dfa = pd.DataFrame({"masa_wzrost": pd.Series([ [1,2], [3,4], [5,6]])})
dfa

  masa_wzrost
0      [1, 2]
1      [3, 4]
2      [5, 6]

In [75]:
def licz_bmi(wektor):
    return wektor[0] * wektor[1]

In [79]:
dfa['bmi'] = dfa["masa_wzrost"].map(licz_bmi)
dfa

  masa_wzrost  bmi
0      [1, 2]    2
1      [3, 4]   12
2      [5, 6]   30

In [80]:
dfa.to_csv("plik.csv")

In [91]:
dfa.to_excel("plik.xlsx")

In [83]:
dfa['masa'] = dfa['masa_wzrost'].map(lambda w: w[0])
dfa["wzrost"] = dfa["masa_wzrost"].map(lambda w: w[1])
dfa

  masa_wzrost  bmi  masa  wzrost
0      [1, 2]    2     1       2
1      [3, 4]   12     3       4
2      [5, 6]   30     5       6

In [89]:
dfa["nowe"] = dfa.apply(lambda row: [row["masa"], row["wzrost"]], axis=1)
dfa

  masa_wzrost  bmi  masa  wzrost    nowe
0      [1, 2]    2     1       2  [1, 2]
1      [3, 4]   12     3       4  [3, 4]
2      [5, 6]   30     5       6  [5, 6]

In [90]:
dfa.dtypes

masa_wzrost    object
bmi             int64
masa            int64
wzrost          int64
nowe           object
dtype: object