In [1]:
import pandas as pd

In [2]:
# potrzebny do współpracy z Excelem pakiet openpyxl
!pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: C:\Users\lemur\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

In [ ]:
ceny = pd.DataFrame(
    {
        "cena": [12.50, 45.00, 8.99, 120.00, 24.50, 65.00, 45.00],
        "towar": ["Kawa", "Herbata", "Woda", "Wino", "Sok", "Miód", "Ciastko"],
    }
)

ceny

     cena    towar
0   12.50     Kawa
1   45.00  Herbata
2    8.99     Woda
3  120.00     Wino
4   24.50      Sok
5   65.00     Miód
6   45.00  Ciastko

In [ ]:
ceny.to_csv("towary_1.csv", index=False, sep=";", decimal=",", encoding="Windows-1250") # cp1250

     cena    towar
0   12.50     Kawa
1   45.00  Herbata
2    8.99     Woda
3  120.00     Wino
4   24.50      Sok
5   65.00     Miód
6   45.00  Ciastko

In [18]:
df = pd.read_csv("towary_2.csv", encoding="Windows-1250", sep=";", decimal=",")
df

      cena     towar
0    12.50      Kawa
1    45.00   Herbata
2     8.99      Woda
3   120.00      Wino
4    24.50       Sok
5    65.00      Miód
6    45.00   Ciastko
7    56.00   Żelasko
8   562.00    Źdźbło
9   148.00      Góra
10  548.00  Łachmany

In [19]:
df['cena'].sum()

np.float64(1634.99)

In [20]:
df.to_excel("towary_2.xlsx", index=False)

In [21]:
pd.read_excel("towary_2.xlsx")

      cena     towar
0    12.50      Kawa
1    45.00   Herbata
2     8.99      Woda
3   120.00      Wino
4    24.50       Sok
5    65.00      Miód
6    45.00   Ciastko
7    56.00   Żelasko
8   562.00    Źdźbło
9   148.00      Góra
10  548.00  Łachmany

In [ ]:
df = pd.read_excel("towary_3.xlsx")
df

      cena     towar       data data_jako_tekst
0    12.50      Kawa 2026-09-28      2026-09-28
1    45.00   Herbata 2026-09-28      2026-09-28
2     8.99      Woda 2026-08-02      2026-08-02
3   120.00      Wino 2026-09-28      2026-09-28
4    24.50       Sok 2025-09-28      2025-09-28
5    65.00      Miód 2026-10-28      2026-10-28
6    45.00   Ciastko 2026-09-08      2026-09-08
7    56.00   Żelasko 2026-09-28      2026-09-28
8   562.00    Źdźbło 2024-10-12      2024-10-12
9   148.00      Góra 2026-09-28      2026-09-28
10  548.00  Łachmany 2026-09-28      2026-09-28

In [28]:
df.dtypes

cena                      float64
towar                         str
data               datetime64[us]
data_jako_tekst               str
dtype: object

In [30]:
pd.read_excel("towary_3.xlsx",sheet_name="Arkusz1" )

   to jest mój drugi arkuisz
0                          1
1                          2
2                          3

In [31]:
df

      cena     towar       data data_jako_tekst
0    12.50      Kawa 2026-09-28      2026-09-28
1    45.00   Herbata 2026-09-28      2026-09-28
2     8.99      Woda 2026-08-02      2026-08-02
3   120.00      Wino 2026-09-28      2026-09-28
4    24.50       Sok 2025-09-28      2025-09-28
5    65.00      Miód 2026-10-28      2026-10-28
6    45.00   Ciastko 2026-09-08      2026-09-08
7    56.00   Żelasko 2026-09-28      2026-09-28
8   562.00    Źdźbło 2024-10-12      2024-10-12
9   148.00      Góra 2026-09-28      2026-09-28
10  548.00  Łachmany 2026-09-28      2026-09-28

In [33]:
df.columns = ["cena", "nazwa_produktu", "data", "data_jako_tekst"]

In [34]:
df

      cena nazwa_produktu       data data_jako_tekst
0    12.50           Kawa 2026-09-28      2026-09-28
1    45.00        Herbata 2026-09-28      2026-09-28
2     8.99           Woda 2026-08-02      2026-08-02
3   120.00           Wino 2026-09-28      2026-09-28
4    24.50            Sok 2025-09-28      2025-09-28
5    65.00           Miód 2026-10-28      2026-10-28
6    45.00        Ciastko 2026-09-08      2026-09-08
7    56.00        Żelasko 2026-09-28      2026-09-28
8   562.00         Źdźbło 2024-10-12      2024-10-12
9   148.00           Góra 2026-09-28      2026-09-28
10  548.00       Łachmany 2026-09-28      2026-09-28

In [38]:
pd.read_excel("towary_3.xlsx", sheet_name="pusta kolumna w środku")

,koljumna a,Unnamed: 1,Unnamed: 2,kolumna d,kolumna e,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,1.0,NaN,NaN,1.0,3.0,NaN,NaN,NaN,NaN,NaN
1,2.0,NaN,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN
2,3.0,NaN,NaN,3.0,3.0,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25454.0

In [37]:
pd.read_csv("towary_2.csv", sep=";")

    cena     towar  Unnamed: 2
0   12,5      Kawa         NaN
1     45   Herbata         NaN
2   8,99      Woda         NaN
3    120      Wino         NaN
4   24,5       Sok         NaN
5     65      Mi�d         NaN
6     45   Ciastko         NaN
7     56   �elasko         NaN
8    562    �d�b�o         NaN
9    148      G�ra         NaN
10   548  �achmany         NaN

In [39]:
pd.read_excel("towary_3.xlsx", sheet_name="Sheet2")

         Raport z dnia 2026-09-28 Unnamed: 1           Unnamed: 2
0   Przygotował: Łukasz Prokulski        NaN                  NaN
1                             NaN        NaN                  NaN
2                            cena      towar                 data
3                            12.5       Kawa  2026-09-28 00:00:00
4                              45    Herbata  2026-09-28 00:00:00
5                            8.99       Woda  2026-08-02 00:00:00
6                             120       Wino  2026-09-28 00:00:00
7                            24.5        Sok  2025-09-28 00:00:00
8                              65       Miód  2026-10-28 00:00:00
9                              45    Ciastko  2026-09-08 00:00:00
10                             56    Żelasko  2026-09-28 00:00:00
11                            562     Źdźbło  2024-10-12 00:00:00
12                            148       Góra  2026-09-28 00:00:00
13                            548   Łachmany  2026-09-28 00:00:00

In [47]:
pd.read_excel("towary_3.xlsx", sheet_name="Sheet2", skiprows=3)

      cena     towar       data
0    12.50      Kawa 2026-09-28
1    45.00   Herbata 2026-09-28
2     8.99      Woda 2026-08-02
3   120.00      Wino 2026-09-28
4    24.50       Sok 2025-09-28
5    65.00      Miód 2026-10-28
6    45.00   Ciastko 2026-09-08
7    56.00   Żelasko 2026-09-28
8   562.00    Źdźbło 2024-10-12
9   148.00      Góra 2026-09-28
10  548.00  Łachmany 2026-09-28

In [51]:
df = pd.read_excel("towary_3.xlsx", sheet_name="osoby", dtype={
    "pesel": "str",
    "nr telefonu": "str"
    })
print(df)
print("")
print(df.dtypes)

      imie  nazwisko        pesel nr telefonu
0      jan     nowak  80010112345   510000111
1    maria  kowalska  00321454321   690333666
2  zdzichu    dyrman  22113198745   607123456

imie           str
nazwisko       str
pesel          str
nr telefonu    str
dtype: object