In [ ]:
import pandas as pd

In [19]:
df = pd.DataFrame(
    {
        "Klient": [
            "Jan Kowalski",
            "Anna Nowak",
            "Piotr Wiśniewski",
            "Maria Dąbrowska",
            "Tomasz Lis",
            "Zdzisław Dyrman"
        ],
        "Wiek": [28, 42, 35, 22, 51, 34],
        "Miasto": ["Warszawa", "Kraków", "Warszawa", "Gdańsk", "Kraków", "Sopot"],
        "Kwota_Zakupow": [1250.50, 4300.00, 890.20, 310.00, 2150.00, 1500],
        "Status": ["Aktywny", "VIP", "Aktywny", "Nowy", "VIP", "Aktywny"],
    }
)

In [20]:
df

             Klient  Wiek    Miasto  Kwota_Zakupow   Status
0      Jan Kowalski    28  Warszawa         1250.5  Aktywny
1        Anna Nowak    42    Kraków         4300.0      VIP
2  Piotr Wiśniewski    35  Warszawa          890.2  Aktywny
3   Maria Dąbrowska    22    Gdańsk          310.0     Nowy
4        Tomasz Lis    51    Kraków         2150.0      VIP
5   Zdzisław Dyrman    34     Sopot         1500.0  Aktywny

In [5]:
df.dtypes

Klient               str
Wiek               int64
Miasto               str
Kwota_Zakupow    float64
Status               str
dtype: object

In [6]:
df.describe()

            Wiek  Kwota_Zakupow
count   5.000000       5.000000
mean   35.600000    1780.140000
std    11.414903    1558.870921
min    22.000000     310.000000
25%    28.000000     890.200000
50%    35.000000    1250.500000
75%    42.000000    2150.000000
max    51.000000    4300.000000

In [10]:
df.shape

(6, 5)

In [12]:
df.empty

False

In [14]:
pusty_df = pd.DataFrame()

In [15]:
pusty_df.shape

(0, 0)

In [16]:
pusty_df.empty

True

In [17]:
df.nunique()

Klient           6
Wiek             6
Miasto           4
Kwota_Zakupow    6
Status           3
dtype: int64

In [21]:
df.describe(include='all')

              Klient       Wiek    Miasto  Kwota_Zakupow   Status
count              6   6.000000         6       6.000000        6
unique             6        NaN         4            NaN        3
top     Jan Kowalski        NaN  Warszawa            NaN  Aktywny
freq               1        NaN         2            NaN        3
mean             NaN  35.333333       NaN    1733.450000      NaN
std              NaN  10.230673       NaN    1398.979119      NaN
min              NaN  22.000000       NaN     310.000000      NaN
25%              NaN  29.500000       NaN     980.275000      NaN
50%              NaN  34.500000       NaN    1375.250000      NaN
75%              NaN  40.250000       NaN    1987.500000      NaN
max              NaN  51.000000       NaN    4300.000000      NaN

In [22]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [23]:
df.columns

Index(['Klient', 'Wiek', 'Miasto', 'Kwota_Zakupow', 'Status'], dtype='str')

In [24]:
df2 = pd.DataFrame(
    {
        "Klient": [
            "Jan Kowalski",
            "Anna Nowak",
            "Piotr Wiśniewski",
            "Maria Dąbrowska",
            "Tomasz Lis",
            "Zdzisław Dyrman",
        ],
        "Wiek": [28, 42, 35, 22, 51, 34],
        "Miasto": ["Warszawa", "Kraków", "Warszawa", "Gdańsk", "Kraków", "Sopot"],
        "Kwota_Zakupow": [1250.50, 4300.00, 890.20, 310.00, 2150.00, 1500],
        "Status": ["Aktywny", "VIP", "Aktywny", "Nowy", "VIP", "Aktywny"],
    },
    index=['a','b','c','d','e','f']
)
df2

             Klient  Wiek    Miasto  Kwota_Zakupow   Status
a      Jan Kowalski    28  Warszawa         1250.5  Aktywny
b        Anna Nowak    42    Kraków         4300.0      VIP
c  Piotr Wiśniewski    35  Warszawa          890.2  Aktywny
d   Maria Dąbrowska    22    Gdańsk          310.0     Nowy
e        Tomasz Lis    51    Kraków         2150.0      VIP
f   Zdzisław Dyrman    34     Sopot         1500.0  Aktywny

In [25]:
df2.index

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='str')

In [28]:
df2.info()

<class 'pandas.DataFrame'>
Index: 6 entries, a to f
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Klient         6 non-null      str
 1   Wiek           6 non-null      int64
 2   Miasto         6 non-null      str
 3   Kwota_Zakupow  6 non-null      float64
 4   Status         6 non-null      str
dtypes: float64(1), int64(1), str(3)
memory usage: 620.0 bytes

In [29]:
df2.info(memory_usage="deep")

<class 'pandas.DataFrame'>
Index: 6 entries, a to f
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Klient         6 non-null      str
 1   Wiek           6 non-null      int64
 2   Miasto         6 non-null      str
 3   Kwota_Zakupow  6 non-null      float64
 4   Status         6 non-null      str
dtypes: float64(1), int64(1), str(3)
memory usage: 620.0 bytes

In [33]:
df3 = pd.DataFrame(
    {
        "Klient": [
            "Jan Kowalski",
            None,
            "Piotr Wiśniewski",
            "Maria Dąbrowska",
            "Tomasz Lis",
            "Zdzisław Dyrman",
        ],
        "Wiek": [28, 42, None, 22, 51, None],
        "Miasto": ["Warszawa", "Kraków", "Warszawa", None, "Kraków", "Sopot"],
        "Kwota_Zakupow": [1250.50, 4300.00, 890.20, 310.00, None, 1500],
        "Status": ["Aktywny", "VIP", "Aktywny", "Nowy", "VIP", None],
    }
)
df3

             Klient  Wiek    Miasto  Kwota_Zakupow   Status
0      Jan Kowalski  28.0  Warszawa         1250.5  Aktywny
1               NaN  42.0    Kraków         4300.0      VIP
2  Piotr Wiśniewski   NaN  Warszawa          890.2  Aktywny
3   Maria Dąbrowska  22.0       NaN          310.0     Nowy
4        Tomasz Lis  51.0    Kraków            NaN      VIP
5   Zdzisław Dyrman   NaN     Sopot         1500.0      NaN

In [34]:
df3.isnull().sum()

Klient           1
Wiek             2
Miasto           1
Kwota_Zakupow    1
Status           1
dtype: int64

In [35]:
df3.dropna()

         Klient  Wiek    Miasto  Kwota_Zakupow   Status
0  Jan Kowalski  28.0  Warszawa         1250.5  Aktywny

In [36]:
df3.dropna(subset=['Klient'])

             Klient  Wiek    Miasto  Kwota_Zakupow   Status
0      Jan Kowalski  28.0  Warszawa         1250.5  Aktywny
2  Piotr Wiśniewski   NaN  Warszawa          890.2  Aktywny
3   Maria Dąbrowska  22.0       NaN          310.0     Nowy
4        Tomasz Lis  51.0    Kraków            NaN      VIP
5   Zdzisław Dyrman   NaN     Sopot         1500.0      NaN

In [37]:
df3.dropna(subset=["Klient", "Wiek"])

            Klient  Wiek    Miasto  Kwota_Zakupow   Status
0     Jan Kowalski  28.0  Warszawa         1250.5  Aktywny
3  Maria Dąbrowska  22.0       NaN          310.0     Nowy
4       Tomasz Lis  51.0    Kraków            NaN      VIP

In [38]:
towary = pd.read_excel("towary_3.xlsx", sheet_name="pusta kolumna w środku")
towary.dropna()

Empty DataFrame
Columns: [koljumna a, Unnamed: 1, Unnamed: 2, kolumna d, kolumna e, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9]
Index: []

In [39]:
towary.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   koljumna a  3 non-null      float64
 1   Unnamed: 1  0 non-null      float64
 2   Unnamed: 2  0 non-null      float64
 3   kolumna d   3 non-null      float64
 4   kolumna e   3 non-null      float64
 5   Unnamed: 5  0 non-null      float64
 6   Unnamed: 6  0 non-null      float64
 7   Unnamed: 7  0 non-null      float64
 8   Unnamed: 8  0 non-null      float64
 9   Unnamed: 9  1 non-null      float64
dtypes: float64(10)
memory usage: 932.0 bytes

In [40]:
df3

             Klient  Wiek    Miasto  Kwota_Zakupow   Status
0      Jan Kowalski  28.0  Warszawa         1250.5  Aktywny
1               NaN  42.0    Kraków         4300.0      VIP
2  Piotr Wiśniewski   NaN  Warszawa          890.2  Aktywny
3   Maria Dąbrowska  22.0       NaN          310.0     Nowy
4        Tomasz Lis  51.0    Kraków            NaN      VIP
5   Zdzisław Dyrman   NaN     Sopot         1500.0      NaN

In [47]:
df3["Kwota_Zakupow"]

0    1250.5
1    4300.0
2     890.2
3     310.0
4       NaN
5    1500.0
Name: Kwota_Zakupow, dtype: float64

In [48]:
df3[ ['Kwota_Zakupow'] ]

   Kwota_Zakupow
0         1250.5
1         4300.0
2          890.2
3          310.0
4            NaN
5         1500.0

In [49]:
df3[["Kwota_Zakupow", "Klient"]]

   Kwota_Zakupow            Klient
0         1250.5      Jan Kowalski
1         4300.0               NaN
2          890.2  Piotr Wiśniewski
3          310.0   Maria Dąbrowska
4            NaN        Tomasz Lis
5         1500.0   Zdzisław Dyrman

In [57]:
liczba_wierszy = towary.shape[0]
kolumny_niepuste = []

for col in towary.columns:
    print(f"Kolumna: {col}")
    licz_puste = towary[col].isnull().sum()
    print(f"Pustych: {licz_puste}")
    if licz_puste == liczba_wierszy:
        print("Wszystkie wiersze puste!")
    else:
        kolumny_niepuste.append(col)
    print()

print(f"Niepuste kolumny: {kolumny_niepuste}")

Kolumna: koljumna a
Pustych: 7

Kolumna: Unnamed: 1
Pustych: 10
Wszystkie wiersze puste!

Kolumna: Unnamed: 2
Pustych: 10
Wszystkie wiersze puste!

Kolumna: kolumna d
Pustych: 7

Kolumna: kolumna e
Pustych: 7

Kolumna: Unnamed: 5
Pustych: 10
Wszystkie wiersze puste!

Kolumna: Unnamed: 6
Pustych: 10
Wszystkie wiersze puste!

Kolumna: Unnamed: 7
Pustych: 10
Wszystkie wiersze puste!

Kolumna: Unnamed: 8
Pustych: 10
Wszystkie wiersze puste!

Kolumna: Unnamed: 9
Pustych: 9

Niepuste kolumny: ['koljumna a', 'kolumna d', 'kolumna e', 'Unnamed: 9']

In [59]:
towary[kolumny_niepuste]

   koljumna a  kolumna d  kolumna e  Unnamed: 9
0         1.0        1.0        3.0         NaN
1         2.0        2.0        2.0         NaN
2         3.0        3.0        3.0         NaN
3         NaN        NaN        NaN         NaN
4         NaN        NaN        NaN         NaN
5         NaN        NaN        NaN         NaN
6         NaN        NaN        NaN         NaN
7         NaN        NaN        NaN         NaN
8         NaN        NaN        NaN         NaN
9         NaN        NaN        NaN     25454.0

In [61]:
df2

             Klient  Wiek    Miasto  Kwota_Zakupow   Status
a      Jan Kowalski    28  Warszawa         1250.5  Aktywny
b        Anna Nowak    42    Kraków         4300.0      VIP
c  Piotr Wiśniewski    35  Warszawa          890.2  Aktywny
d   Maria Dąbrowska    22    Gdańsk          310.0     Nowy
e        Tomasz Lis    51    Kraków         2150.0      VIP
f   Zdzisław Dyrman    34     Sopot         1500.0  Aktywny

In [62]:
df2.reset_index()

  index            Klient  Wiek    Miasto  Kwota_Zakupow   Status
0     a      Jan Kowalski    28  Warszawa         1250.5  Aktywny
1     b        Anna Nowak    42    Kraków         4300.0      VIP
2     c  Piotr Wiśniewski    35  Warszawa          890.2  Aktywny
3     d   Maria Dąbrowska    22    Gdańsk          310.0     Nowy
4     e        Tomasz Lis    51    Kraków         2150.0      VIP
5     f   Zdzisław Dyrman    34     Sopot         1500.0  Aktywny

In [63]:
df2.reset_index(drop=True)

             Klient  Wiek    Miasto  Kwota_Zakupow   Status
0      Jan Kowalski    28  Warszawa         1250.5  Aktywny
1        Anna Nowak    42    Kraków         4300.0      VIP
2  Piotr Wiśniewski    35  Warszawa          890.2  Aktywny
3   Maria Dąbrowska    22    Gdańsk          310.0     Nowy
4        Tomasz Lis    51    Kraków         2150.0      VIP
5   Zdzisław Dyrman    34     Sopot         1500.0  Aktywny

In [64]:
df2.columns

Index(['Klient', 'Wiek', 'Miasto', 'Kwota_Zakupow', 'Status'], dtype='str')

In [65]:
df2.columns = ["imie_nazwisko", "wiek", "miasto", "wydana_kwota", "typ_klienta"]

In [67]:
df2.columns[0]= "nazwa"

TypeError: Index does not support mutable operations

In [69]:
df2['imie_nazwisko']

a        Jan Kowalski
b          Anna Nowak
c    Piotr Wiśniewski
d     Maria Dąbrowska
e          Tomasz Lis
f     Zdzisław Dyrman
Name: imie_nazwisko, dtype: str

In [70]:
df2.imie_nazwisko

a        Jan Kowalski
b          Anna Nowak
c    Piotr Wiśniewski
d     Maria Dąbrowska
e          Tomasz Lis
f     Zdzisław Dyrman
Name: imie_nazwisko, dtype: str

In [71]:
df3

             Klient  Wiek    Miasto  Kwota_Zakupow   Status
0      Jan Kowalski  28.0  Warszawa         1250.5  Aktywny
1               NaN  42.0    Kraków         4300.0      VIP
2  Piotr Wiśniewski   NaN  Warszawa          890.2  Aktywny
3   Maria Dąbrowska  22.0       NaN          310.0     Nowy
4        Tomasz Lis  51.0    Kraków            NaN      VIP
5   Zdzisław Dyrman   NaN     Sopot         1500.0      NaN

In [74]:
df3.value_counts('Miasto', dropna=False)

Miasto
Warszawa    2
Kraków      2
NaN         1
Sopot       1
Name: count, dtype: int64

In [76]:
df3.value_counts("Miasto", dropna=False, normalize=True)*100

Miasto
Warszawa    33.333333
Kraków      33.333333
NaN         16.666667
Sopot       16.666667
Name: proportion, dtype: float64

In [77]:
spoleczenstwo = pd.read_parquet("spoleczensto.parquet")
spoleczenstwo

,id,imie,nazwisko,firma,email,telefon,miasto,ulica,nr_budynku
0,1,Kacper,Ciuk,Cudzich s.c.,dagmara53@example.net,579 880 315,Legionowo,Zakole,87/88
1,2,Bianka,Dybaś,Kustosz Sp.j.,skomuda@example.net,+48 533 979 087,Oleśnica,Kościuszki,54/17
2,3,Sara,Kubasiak,Stowarzyszenie Czerniec Sp. z o.o.,nycartur@example.org,505 484 908,Nowy Dwór Mazowiecki,Orla,890
3,4,Juliusz,Furga,Grupa Kasperczak s.c.,elzbietabakiewicz@example.com,696 973 561,Biłgoraj,Bankowa,64
4,5,Olaf,Mydlarz,Tolak-Jędrys Sp.k.,apietrusiak@example.com,+48 739 856 809,Lublin,Wierzbowa,925
...,...,...,...,...,...,...,...,...,...
9995,9996,Maciej,Skubała,Grupa Pilipczuk,adrian51@example.com,726 300 145,Września,Wiśniowa,236
9996,9997,Tomasz,Pachuta,Zbroszczyk-Żelazo S.A.,buksaliwia@example.org,798 327 965,Olkusz,Perłowa,222
9997,9998,Kaja,Musiolik,Fundacja Chmielak s.c.,juliusz13@example.net,+48 538 645 366,Nysa,Partyzantów,14/62
9998,9999,Bruno,Armata,Stowarzyszenie Moryc Sp.k.,anastazjajakiel@example.com,+48 783 436 091,Stargard Szczeciński,Kossaka,062
9999,10000,Karol,Gadzała,Potęga-Smardz Sp.k.,justyna97@example.net,732 063 096,Wągrowiec,Sawickiej,954

In [78]:
spoleczenstwo.value_counts(['imie','nazwisko'])

imie     nazwisko
Marcin   Jędrys      2
Iwo      Zbiciak     2
Inga     Prygiel     2
Gabriel  Hutnik      2
Jerzy    Frelich     2
                    ..
Maciej   Skubała     1
Tomasz   Pachuta     1
Kaja     Musiolik    1
Bruno    Armata      1
Karol    Gadzała     1
Name: count, Length: 9903, dtype: int64

In [ ]:
spoleczenstwo.sort_values('imie' )

,id,imie,nazwisko,firma,email,telefon,miasto,ulica,nr_budynku
23,24,Ada,Reiter,FPUH Giezek,nklepka@example.com,696 038 251,Sopot,Bolesława Chrobrego,24
26,27,Ada,Panicz,Andrearczyk-Glazik Sp. z o.o.,adam42@example.com,+48 506 210 124,Chrzanów,Pogodna,393
49,50,Ada,Bystrek,Grupa Walusiak S.A.,qparada@example.net,690 644 948,Jawor,Odrzańska,99/81
202,203,Ada,Sadowy,FPUH Antoń Sp.k.,liwia02@example.net,793 520 435,Piekary Śląskie,Dąbrowskiej,388
228,229,Ada,Bohdanowicz,Spółdzielnia Bodych i syn s.c.,ekamieniak@example.com,783 347 620,Pruszków,Polna,232
...,...,...,...,...,...,...,...,...,...
9481,9482,Łukasz,Hasiak,Rurarz-Gumienna S.A.,antonitorz@example.org,667 736 184,Kutno,Górnicza,179
9576,9577,Łukasz,Golczyk,Matela Sp. z o.o. Sp.k.,tymonsaran@example.com,603 649 464,Lubartów,Widok,635
9662,9663,Łukasz,Krzykała,FPUH Cieciora,pasztaleniecjanina@example.net,+48 533 944 908,Zamość,Kochanowskiego,435
9792,9793,Łukasz,Smoter,Gabinety Luberda s.c.,slimakklara@example.net,+48 781 325 407,Swarzędz,Wrocławska,447
9863,9864,Łukasz,Freitag,PPUH Szczerbiak-Szajek Sp. z o.o. Sp.k.,roksana13@example.com,882 061 361,Katowice,Witosa,04/46

In [81]:
spoleczenstwo.sort_values("imie", ascending=False)

,id,imie,nazwisko,firma,email,telefon,miasto,ulica,nr_budynku
38,39,Łukasz,Pietryga,PPUH Zegadło S.A.,bstrzelczak@example.net,+48 502 152 979,Pabianice,Jagiellońska,83/64
79,80,Łukasz,Mleczak,Dziwak-Kalka Sp. z o.o.,kazimierz17@example.org,+48 608 869 868,Siedlce,Wybickiego,71
221,222,Łukasz,Mieloch,Gabinety Lalak,cudzichradoslaw@example.org,+48 734 983 610,Jarosław,Rataja,54/56
479,480,Łukasz,Dynak,Walocha-Rysz s.c.,jakub29@example.net,+48 572 340 148,Gdynia,Krasińskiego,708
651,652,Łukasz,Misiejuk,Durlej-Stempniak Sp. z o.o. Sp.k.,iwo80@example.com,882 025 382,Zawiercie,Listopada,043
...,...,...,...,...,...,...,...,...,...
8889,8890,Ada,Matela,Cywka Sp. z o.o.,wdanieluk@example.com,696 699 340,Gdynia,Poniatowskiego,17/51
8915,8916,Ada,Kiełbik,Grupa Lepianka,roksanabialk@example.net,+48 577 352 570,Kluczbork,Zdrojowa,47/25
9463,9464,Ada,Dyszy,Grupa Piekart Sp.k.,blazej47@example.org,+48 695 194 098,Jawor,Śląska,80/36
9659,9660,Ada,Szajda,Stowarzyszenie Hennig,wiencekroksana@example.com,+48 886 842 568,Krosno,Maja,59
9808,9809,Ada,Leszcz,Stowarzyszenie Wielgo i syn s.c.,jchlebek@example.com,733 283 835,Piekary Śląskie,Zamkowa,972

In [83]:
spoleczenstwo.sort_values(["imie", 'nazwisko'], ascending=[False, True])

,id,imie,nazwisko,firma,email,telefon,miasto,ulica,nr_budynku
6419,6420,Łukasz,Aleksa,PPUH Nowek,korzekwakonstanty@example.org,517 304 665,Pszczyna,Kazimierza Wielkiego,45/68
5374,5375,Łukasz,Augustynek,Gabinety Feliksiak-Augustynek Sp. z o.o. Sp.k.,tryckornelia@example.com,+48 782 584 517,Nowy Targ,Sokola,70/45
1197,1198,Łukasz,Baum,Dyka S.A.,otoborek@example.net,+48 510 933 004,Rzeszów,Kossaka,890
4169,4170,Łukasz,Bojarczuk,Soliwoda Sp.j.,lmonkiewicz@example.com,22 214 46 76,Konin,Podmiejska,97/12
9358,9359,Łukasz,Butrym,Igras-Szwaj Sp. z o.o. Sp.k.,agnieszkastaciwa@example.org,+48 694 615 429,Kraśnik,Wysoka,01
...,...,...,...,...,...,...,...,...,...
4709,4710,Ada,Woszczak,FPUH Wardzała-Machoń S.A.,pyszkamaurycy@example.net,735 102 951,Zakopane,Borowa,898
473,474,Ada,Wołoszyk,Stowarzyszenie Kawala,brodawkajerzy@example.org,+48 667 746 532,Jelenia Góra,Strzelecka,13/75
6716,6717,Ada,Wąsiewicz,Stowarzyszenie Dziczek-Owsiany S.A.,lkuziora@example.net,782 885 904,Pszczyna,Turkusowa,78/03
3912,3913,Ada,Zagrodnik,Stowarzyszenie Lejk S.A.,pawel10@example.net,+48 504 785 976,Malbork,Listopada,98/67
4181,4182,Ada,Łaś,Paździora S.A.,alanpolewka@example.org,+48 693 139 913,Knurów,Zachodnia,64

In [ ]:
# widok
df_warszawa = spoleczenstwo[spoleczenstwo["miasto"] == "Warszawa"].copy()
df_warszawa

,id,imie,nazwisko,firma,email,telefon,miasto,ulica,nr_budynku
430,431,Ada,Kuciel,Groborz S.A.,rozalia44@example.com,661 953 750,Warszawa,Klonowa,13/79
556,557,Natan,Plak,Stowarzyszenie Warych S.A.,dryndamelania@example.net,+48 22 761 20 65,Warszawa,Jasna,812
587,588,Nataniel,Bosek,Spółdzielnia Olesiejuk Sp.k.,kaja72@example.net,+48 576 886 330,Warszawa,Jodłowa,63
626,627,Sylwia,Nasiadka,FPUH Narożna,xsaternus@example.com,+48 887 084 962,Warszawa,Letnia,41/88
939,940,Antoni,Cabała,Stowarzyszenie Oskroba i syn s.c.,ochniodamian@example.com,+48 728 215 378,Warszawa,Wolności,677
1012,1013,Sandra,Kołodziejak,Morawiak Sp.j.,cypriankrysik@example.org,606 961 245,Warszawa,Wiśniowa,903
1019,1020,Jakub,Ważna,Fundacja Franiak-Siejak Sp.j.,andrzej00@example.net,781 673 630,Warszawa,Miłosza,85
1058,1059,Paweł,Palica,Kostera-Zieniewicz s.c.,oleksikkarol@example.net,537 951 754,Warszawa,Zaciszna,45/27
1158,1159,Anna Maria,Sadoch,Spółdzielnia Szymała,janinawojs@example.net,503 469 859,Warszawa,Żabia,735
1351,1352,Cyprian,Siejak,Młocek Sp.j.,zauchaarkadiusz@example.com,787 611 025,Warszawa,Kolejowa,41
1353,1354,Krzysztof,Zaucha,Stowarzyszenie Ciarka Sp.k.,byzdraaleksander@example.com,887 263 675,Warszawa,Jadwigi,839
1720,1721,Cezary,Kochman,Rycerz Sp.k.,belzstanislaw@example.org,+48 665 615 946,Warszawa,Dąbrowskiego,89
1762,1763,Kazimierz,Jakóbiak,Spółdzielnia Tecław-Kusztal i syn s.c.,cbladek@example.org,+48 508 374 629,Warszawa,Miodowa,66
1901,1902,Kacper,Gabrych,Grupa Olbrych-Kuk Sp. z o.o. Sp.k.,lukaszfelus@example.com,32 476 81 01,Warszawa,Nadbrzeżna,363
2420,2421,Daniel,Lemke,Dmoch Sp.k.,marek78@example.org,+48 32 174 37 14,Warszawa,Żeromskiego,50/86
2556,2557,Franciszek,Pietrasiak,Fuławka-Mikusek i syn s.c.,juliuszbros@example.net,574 350 187,Warszawa,Rejtana,47/86
2576,2577,Jędrzej,Frelich,Gowin Sp.k.,ygrab@example.com,+48 535 427 235,Warszawa,Widokowa,15/78
2662,2663,Krzysztof,Tutka,FPUH Buszka,julianwojczuk@example.org,696 154 488,Warszawa,Mazurska,34/59
2946,2947,Albert,Kierepka,Wierzchoń-Koss s.c.,nicole24@example.org,+48 609 937 828,Warszawa,Jadwigi,67
3290,3291,Ewelina,Krzeszowiec,Gabinety Sulich,machaaleks@example.org,+48 32 273 68 62,Warszawa,Plater,632
3389,3390,Gabriel,Ofiara,Czulak-Jaśko Sp.j.,dgamrat@example.org,+48 22 902 56 26,Warszawa,Plater,831
3709,3710,Marcin,Wenzel,Fundacja Świerszcz-Nowotnik s.c.,icieloch@example.com,737 356 618,Warszawa,Urocza,16/42
3735,3736,Tadeusz,Płocharczyk,Spółdzielnia Zatoń Sp.j.,kajetansiemek@example.com,782 995 838,Warszawa,Kolonia,068
3793,3794,Anita,Midura,Spółdzielnia Majtyka-Bujko Sp. z o.o.,vrzad@example.org,+48 723 867 169,Warszawa,Jadwigi,073
4035,4036,Monika,Pawełko,Fundacja Sałuda-Tworzydło s.c.,czemanek@example.com,+48 789 937 596,Warszawa,Sowia,39/69
4514,4515,Lidia,Kleinschmidt,Bogdał-Banachowicz i syn s.c.,sdziurla@example.net,+48 603 990 184,Warszawa,Boczna,085
4539,4540,Grzegorz,Ziniewicz,Wiercigroch S.A.,idetka@example.net,732 355 430,Warszawa,Magnoliowa,32/16
4779,4780,Filip,Pachowicz,Podsiadła Sp.j.,lidiakonsek@example.net,661 984 821,Warszawa,Morcinka,77/92
5023,5024,Mieszko,Kudra,Prejs-Sobuś Sp. z o.o. Sp.k.,gillfryderyk@example.net,+48 885 257 523,Warszawa,Wiązowa,467
5071,5072,Alan,Ziajka,Stowarzyszenie Olas,miloszpalac@example.com,+48 32 217 90 02,Warszawa,Krokusowa,10
5265,5266,Mieszko,Czesak,Steuer-Kośnik Sp. z o.o.,nikodem13@example.net,786 580 934,Warszawa,Strzelecka,14
5399,5400,Marika,Tomzik,Fundacja Marcińczyk-Misiarz Sp. z o.o. Sp.k.,cezarysuchenek@example.net,696 657 649,Warszawa,Głogowa,75
5476,5477,Sonia,Grzech,Gabinety Kłosowicz,karol44@example.com,+48 782 651 143,Warszawa,Wyszyńskiego,33
5487,5488,Anna Maria,Kolanko,Cyroń-Milczarczyk S.A.,feliksiaktadeusz@example.org,+48 668 866 871,Warszawa,Konopnickiej,479
5517,5518,Ryszard,Bekus,Ciuba-Lukas s.c.,hubert57@example.net,+48 668 660 608,Warszawa,Jesienna,809
5603,5604,Nikodem,Wylegała,Grupa Kuba,sleziaktomasz@example.net,+48 735 843 910,Warszawa,Wieniawskiego,11
5722,5723,Kacper,Pronobis,Wita-Murat s.c.,mateuszmoryc@example.net,+48 738 414 914,Warszawa,Strumykowa,083
5788,5789,Mieszko,Hadaś,Spółdzielnia Burzawa-Calik Sp. z o.o.,witold51@example.com,+48 508 132 647,Warszawa,Sarnia,08/44
5821,5822,Mieszko,Witko,Klinkosz Sp. z o.o. Sp.k.,julian36@example.org,+48 530 997 685,Warszawa,Jeżynowa,25/65
6007,6008,Józef,Kośnik,Grupa Patora Sp. z o.o. Sp.k.,lfaferek@example.com,+48 22 138 96 52,Warszawa,Borowa,36/36
6122,6123,Olaf,Drynda,Milcarz-Lewko i syn s.c.,bartosstefan@example.net,514 381 468,Warszawa,Piaskowa,513
6376,6377,Iwo,Szwaja,PPUH Kupaj,ernest13@example.org,+48 577 685 964,Warszawa,Zbożowa,663
6476,6477,Alan,Kujawiak,Spółdzielnia Jamrożek-Litwinowicz i syn s.c.,anna-maria56@example.org,534 429 127,Warszawa,Piastowska,51/85
6943,6944,Adrian,Skrzecz,FPUH Stanclik Sp.j.,dawid57@example.com,+48 661 884 614,Warszawa,Konarskiego,248
7158,7159,Kamil,Postawa,PPUH Zdancewicz Sp. z o.o. Sp.k.,pawel27@example.com,793 300 526,Warszawa,Władysława Jagiełły,47
7311,7312,Stanisław,Taczała,Pilipczuk Sp.j.,iwo16@example.net,+48 22 117 86 84,Warszawa,Żwirki i Wigury,505
7562,7563,Rozalia,Burchardt,Basa Sp. z o.o. Sp.k.,konstantysteuer@example.net,+48 574 535 419,Warszawa,Bałtycka,43
7794,7795,Jacek,Bytner,Grupa Fabiańczyk,anna-marianamysl@example.com,+48 732 705 009,Warszawa,Rynek,11
8063,8064,Karol,Labudda,Stowarzyszenie Wojtach-Kucharzyk S.A.,kazimierzhamerla@example.com,+48 503 627 816,Warszawa,Traugutta,36
8375,8376,Konrad,Rakus,Trybała i syn s.c.,lantoszczyk@example.com,500 423 364,Warszawa,Prusa,52
8465,8466,Dominik,Kajdan,Stowarzyszenie Jagieło S.A.,ghass@example.com,+48 662 686 745,Warszawa,Osiedlowa,929
9065,9066,Sandra,Maciejuk,PPUH Grześków Sp.j.,ldomek@example.com,+48 32 154 05 72,Warszawa,Mazurska,988
9172,9173,Kamila,Kołata,Oczko-Janc Sp.k.,atrojanek@example.org,+48 738 465 010,Warszawa,Bankowa,052
9621,9622,Gustaw,Barszczak,Stowarzyszenie Kott-Kosno S.A.,bruno97@example.com,+48 664 842 035,Warszawa,Środkowa,19
9947,9948,Daniel,Świątkiewicz,Rubacha Sp.j.,anita95@example.com,664 177 139,Warszawa,Jaworowa,95
9955,9956,Jakub,Krysta,Kałwa-Szumiec Sp. z o.o. Sp.k.,pietrakjulianna@example.net,533 200 276,Warszawa,Spacerowa,599
9965,9966,Tola,Peda,Fundacja Szmurło Sp.j.,bitnerewa@example.com,+48 697 996 756,Warszawa,Brzechwy,20

In [86]:
df_warszawa['firma'] = 'Firma warszawska'

In [87]:
df_warszawa

,id,imie,nazwisko,firma,email,telefon,miasto,ulica,nr_budynku
430,431,Ada,Kuciel,Firma warszawska,rozalia44@example.com,661 953 750,Warszawa,Klonowa,13/79
556,557,Natan,Plak,Firma warszawska,dryndamelania@example.net,+48 22 761 20 65,Warszawa,Jasna,812
587,588,Nataniel,Bosek,Firma warszawska,kaja72@example.net,+48 576 886 330,Warszawa,Jodłowa,63
626,627,Sylwia,Nasiadka,Firma warszawska,xsaternus@example.com,+48 887 084 962,Warszawa,Letnia,41/88
939,940,Antoni,Cabała,Firma warszawska,ochniodamian@example.com,+48 728 215 378,Warszawa,Wolności,677
1012,1013,Sandra,Kołodziejak,Firma warszawska,cypriankrysik@example.org,606 961 245,Warszawa,Wiśniowa,903
1019,1020,Jakub,Ważna,Firma warszawska,andrzej00@example.net,781 673 630,Warszawa,Miłosza,85
1058,1059,Paweł,Palica,Firma warszawska,oleksikkarol@example.net,537 951 754,Warszawa,Zaciszna,45/27
1158,1159,Anna Maria,Sadoch,Firma warszawska,janinawojs@example.net,503 469 859,Warszawa,Żabia,735
1351,1352,Cyprian,Siejak,Firma warszawska,zauchaarkadiusz@example.com,787 611 025,Warszawa,Kolejowa,41
1353,1354,Krzysztof,Zaucha,Firma warszawska,byzdraaleksander@example.com,887 263 675,Warszawa,Jadwigi,839
1720,1721,Cezary,Kochman,Firma warszawska,belzstanislaw@example.org,+48 665 615 946,Warszawa,Dąbrowskiego,89
1762,1763,Kazimierz,Jakóbiak,Firma warszawska,cbladek@example.org,+48 508 374 629,Warszawa,Miodowa,66
1901,1902,Kacper,Gabrych,Firma warszawska,lukaszfelus@example.com,32 476 81 01,Warszawa,Nadbrzeżna,363
2420,2421,Daniel,Lemke,Firma warszawska,marek78@example.org,+48 32 174 37 14,Warszawa,Żeromskiego,50/86
2556,2557,Franciszek,Pietrasiak,Firma warszawska,juliuszbros@example.net,574 350 187,Warszawa,Rejtana,47/86
2576,2577,Jędrzej,Frelich,Firma warszawska,ygrab@example.com,+48 535 427 235,Warszawa,Widokowa,15/78
2662,2663,Krzysztof,Tutka,Firma warszawska,julianwojczuk@example.org,696 154 488,Warszawa,Mazurska,34/59
2946,2947,Albert,Kierepka,Firma warszawska,nicole24@example.org,+48 609 937 828,Warszawa,Jadwigi,67
3290,3291,Ewelina,Krzeszowiec,Firma warszawska,machaaleks@example.org,+48 32 273 68 62,Warszawa,Plater,632
3389,3390,Gabriel,Ofiara,Firma warszawska,dgamrat@example.org,+48 22 902 56 26,Warszawa,Plater,831
3709,3710,Marcin,Wenzel,Firma warszawska,icieloch@example.com,737 356 618,Warszawa,Urocza,16/42
3735,3736,Tadeusz,Płocharczyk,Firma warszawska,kajetansiemek@example.com,782 995 838,Warszawa,Kolonia,068
3793,3794,Anita,Midura,Firma warszawska,vrzad@example.org,+48 723 867 169,Warszawa,Jadwigi,073
4035,4036,Monika,Pawełko,Firma warszawska,czemanek@example.com,+48 789 937 596,Warszawa,Sowia,39/69
4514,4515,Lidia,Kleinschmidt,Firma warszawska,sdziurla@example.net,+48 603 990 184,Warszawa,Boczna,085
4539,4540,Grzegorz,Ziniewicz,Firma warszawska,idetka@example.net,732 355 430,Warszawa,Magnoliowa,32/16
4779,4780,Filip,Pachowicz,Firma warszawska,lidiakonsek@example.net,661 984 821,Warszawa,Morcinka,77/92
5023,5024,Mieszko,Kudra,Firma warszawska,gillfryderyk@example.net,+48 885 257 523,Warszawa,Wiązowa,467
5071,5072,Alan,Ziajka,Firma warszawska,miloszpalac@example.com,+48 32 217 90 02,Warszawa,Krokusowa,10
5265,5266,Mieszko,Czesak,Firma warszawska,nikodem13@example.net,786 580 934,Warszawa,Strzelecka,14
5399,5400,Marika,Tomzik,Firma warszawska,cezarysuchenek@example.net,696 657 649,Warszawa,Głogowa,75
5476,5477,Sonia,Grzech,Firma warszawska,karol44@example.com,+48 782 651 143,Warszawa,Wyszyńskiego,33
5487,5488,Anna Maria,Kolanko,Firma warszawska,feliksiaktadeusz@example.org,+48 668 866 871,Warszawa,Konopnickiej,479
5517,5518,Ryszard,Bekus,Firma warszawska,hubert57@example.net,+48 668 660 608,Warszawa,Jesienna,809
5603,5604,Nikodem,Wylegała,Firma warszawska,sleziaktomasz@example.net,+48 735 843 910,Warszawa,Wieniawskiego,11
5722,5723,Kacper,Pronobis,Firma warszawska,mateuszmoryc@example.net,+48 738 414 914,Warszawa,Strumykowa,083
5788,5789,Mieszko,Hadaś,Firma warszawska,witold51@example.com,+48 508 132 647,Warszawa,Sarnia,08/44
5821,5822,Mieszko,Witko,Firma warszawska,julian36@example.org,+48 530 997 685,Warszawa,Jeżynowa,25/65
6007,6008,Józef,Kośnik,Firma warszawska,lfaferek@example.com,+48 22 138 96 52,Warszawa,Borowa,36/36
6122,6123,Olaf,Drynda,Firma warszawska,bartosstefan@example.net,514 381 468,Warszawa,Piaskowa,513
6376,6377,Iwo,Szwaja,Firma warszawska,ernest13@example.org,+48 577 685 964,Warszawa,Zbożowa,663
6476,6477,Alan,Kujawiak,Firma warszawska,anna-maria56@example.org,534 429 127,Warszawa,Piastowska,51/85
6943,6944,Adrian,Skrzecz,Firma warszawska,dawid57@example.com,+48 661 884 614,Warszawa,Konarskiego,248
7158,7159,Kamil,Postawa,Firma warszawska,pawel27@example.com,793 300 526,Warszawa,Władysława Jagiełły,47
7311,7312,Stanisław,Taczała,Firma warszawska,iwo16@example.net,+48 22 117 86 84,Warszawa,Żwirki i Wigury,505
7562,7563,Rozalia,Burchardt,Firma warszawska,konstantysteuer@example.net,+48 574 535 419,Warszawa,Bałtycka,43
7794,7795,Jacek,Bytner,Firma warszawska,anna-marianamysl@example.com,+48 732 705 009,Warszawa,Rynek,11
8063,8064,Karol,Labudda,Firma warszawska,kazimierzhamerla@example.com,+48 503 627 816,Warszawa,Traugutta,36
8375,8376,Konrad,Rakus,Firma warszawska,lantoszczyk@example.com,500 423 364,Warszawa,Prusa,52
8465,8466,Dominik,Kajdan,Firma warszawska,ghass@example.com,+48 662 686 745,Warszawa,Osiedlowa,929
9065,9066,Sandra,Maciejuk,Firma warszawska,ldomek@example.com,+48 32 154 05 72,Warszawa,Mazurska,988
9172,9173,Kamila,Kołata,Firma warszawska,atrojanek@example.org,+48 738 465 010,Warszawa,Bankowa,052
9621,9622,Gustaw,Barszczak,Firma warszawska,bruno97@example.com,+48 664 842 035,Warszawa,Środkowa,19
9947,9948,Daniel,Świątkiewicz,Firma warszawska,anita95@example.com,664 177 139,Warszawa,Jaworowa,95
9955,9956,Jakub,Krysta,Firma warszawska,pietrakjulianna@example.net,533 200 276,Warszawa,Spacerowa,599
9965,9966,Tola,Peda,Firma warszawska,bitnerewa@example.com,+48 697 996 756,Warszawa,Brzechwy,20

In [89]:
spoleczenstwo[spoleczenstwo['miasto'] == "Warszawa"]

,id,imie,nazwisko,firma,email,telefon,miasto,ulica,nr_budynku
430,431,Ada,Kuciel,Groborz S.A.,rozalia44@example.com,661 953 750,Warszawa,Klonowa,13/79
556,557,Natan,Plak,Stowarzyszenie Warych S.A.,dryndamelania@example.net,+48 22 761 20 65,Warszawa,Jasna,812
587,588,Nataniel,Bosek,Spółdzielnia Olesiejuk Sp.k.,kaja72@example.net,+48 576 886 330,Warszawa,Jodłowa,63
626,627,Sylwia,Nasiadka,FPUH Narożna,xsaternus@example.com,+48 887 084 962,Warszawa,Letnia,41/88
939,940,Antoni,Cabała,Stowarzyszenie Oskroba i syn s.c.,ochniodamian@example.com,+48 728 215 378,Warszawa,Wolności,677
1012,1013,Sandra,Kołodziejak,Morawiak Sp.j.,cypriankrysik@example.org,606 961 245,Warszawa,Wiśniowa,903
1019,1020,Jakub,Ważna,Fundacja Franiak-Siejak Sp.j.,andrzej00@example.net,781 673 630,Warszawa,Miłosza,85
1058,1059,Paweł,Palica,Kostera-Zieniewicz s.c.,oleksikkarol@example.net,537 951 754,Warszawa,Zaciszna,45/27
1158,1159,Anna Maria,Sadoch,Spółdzielnia Szymała,janinawojs@example.net,503 469 859,Warszawa,Żabia,735
1351,1352,Cyprian,Siejak,Młocek Sp.j.,zauchaarkadiusz@example.com,787 611 025,Warszawa,Kolejowa,41
1353,1354,Krzysztof,Zaucha,Stowarzyszenie Ciarka Sp.k.,byzdraaleksander@example.com,887 263 675,Warszawa,Jadwigi,839
1720,1721,Cezary,Kochman,Rycerz Sp.k.,belzstanislaw@example.org,+48 665 615 946,Warszawa,Dąbrowskiego,89
1762,1763,Kazimierz,Jakóbiak,Spółdzielnia Tecław-Kusztal i syn s.c.,cbladek@example.org,+48 508 374 629,Warszawa,Miodowa,66
1901,1902,Kacper,Gabrych,Grupa Olbrych-Kuk Sp. z o.o. Sp.k.,lukaszfelus@example.com,32 476 81 01,Warszawa,Nadbrzeżna,363
2420,2421,Daniel,Lemke,Dmoch Sp.k.,marek78@example.org,+48 32 174 37 14,Warszawa,Żeromskiego,50/86
2556,2557,Franciszek,Pietrasiak,Fuławka-Mikusek i syn s.c.,juliuszbros@example.net,574 350 187,Warszawa,Rejtana,47/86
2576,2577,Jędrzej,Frelich,Gowin Sp.k.,ygrab@example.com,+48 535 427 235,Warszawa,Widokowa,15/78
2662,2663,Krzysztof,Tutka,FPUH Buszka,julianwojczuk@example.org,696 154 488,Warszawa,Mazurska,34/59
2946,2947,Albert,Kierepka,Wierzchoń-Koss s.c.,nicole24@example.org,+48 609 937 828,Warszawa,Jadwigi,67
3290,3291,Ewelina,Krzeszowiec,Gabinety Sulich,machaaleks@example.org,+48 32 273 68 62,Warszawa,Plater,632
3389,3390,Gabriel,Ofiara,Czulak-Jaśko Sp.j.,dgamrat@example.org,+48 22 902 56 26,Warszawa,Plater,831
3709,3710,Marcin,Wenzel,Fundacja Świerszcz-Nowotnik s.c.,icieloch@example.com,737 356 618,Warszawa,Urocza,16/42
3735,3736,Tadeusz,Płocharczyk,Spółdzielnia Zatoń Sp.j.,kajetansiemek@example.com,782 995 838,Warszawa,Kolonia,068
3793,3794,Anita,Midura,Spółdzielnia Majtyka-Bujko Sp. z o.o.,vrzad@example.org,+48 723 867 169,Warszawa,Jadwigi,073
4035,4036,Monika,Pawełko,Fundacja Sałuda-Tworzydło s.c.,czemanek@example.com,+48 789 937 596,Warszawa,Sowia,39/69
4514,4515,Lidia,Kleinschmidt,Bogdał-Banachowicz i syn s.c.,sdziurla@example.net,+48 603 990 184,Warszawa,Boczna,085
4539,4540,Grzegorz,Ziniewicz,Wiercigroch S.A.,idetka@example.net,732 355 430,Warszawa,Magnoliowa,32/16
4779,4780,Filip,Pachowicz,Podsiadła Sp.j.,lidiakonsek@example.net,661 984 821,Warszawa,Morcinka,77/92
5023,5024,Mieszko,Kudra,Prejs-Sobuś Sp. z o.o. Sp.k.,gillfryderyk@example.net,+48 885 257 523,Warszawa,Wiązowa,467
5071,5072,Alan,Ziajka,Stowarzyszenie Olas,miloszpalac@example.com,+48 32 217 90 02,Warszawa,Krokusowa,10
5265,5266,Mieszko,Czesak,Steuer-Kośnik Sp. z o.o.,nikodem13@example.net,786 580 934,Warszawa,Strzelecka,14
5399,5400,Marika,Tomzik,Fundacja Marcińczyk-Misiarz Sp. z o.o. Sp.k.,cezarysuchenek@example.net,696 657 649,Warszawa,Głogowa,75
5476,5477,Sonia,Grzech,Gabinety Kłosowicz,karol44@example.com,+48 782 651 143,Warszawa,Wyszyńskiego,33
5487,5488,Anna Maria,Kolanko,Cyroń-Milczarczyk S.A.,feliksiaktadeusz@example.org,+48 668 866 871,Warszawa,Konopnickiej,479
5517,5518,Ryszard,Bekus,Ciuba-Lukas s.c.,hubert57@example.net,+48 668 660 608,Warszawa,Jesienna,809
5603,5604,Nikodem,Wylegała,Grupa Kuba,sleziaktomasz@example.net,+48 735 843 910,Warszawa,Wieniawskiego,11
5722,5723,Kacper,Pronobis,Wita-Murat s.c.,mateuszmoryc@example.net,+48 738 414 914,Warszawa,Strumykowa,083
5788,5789,Mieszko,Hadaś,Spółdzielnia Burzawa-Calik Sp. z o.o.,witold51@example.com,+48 508 132 647,Warszawa,Sarnia,08/44
5821,5822,Mieszko,Witko,Klinkosz Sp. z o.o. Sp.k.,julian36@example.org,+48 530 997 685,Warszawa,Jeżynowa,25/65
6007,6008,Józef,Kośnik,Grupa Patora Sp. z o.o. Sp.k.,lfaferek@example.com,+48 22 138 96 52,Warszawa,Borowa,36/36
6122,6123,Olaf,Drynda,Milcarz-Lewko i syn s.c.,bartosstefan@example.net,514 381 468,Warszawa,Piaskowa,513
6376,6377,Iwo,Szwaja,PPUH Kupaj,ernest13@example.org,+48 577 685 964,Warszawa,Zbożowa,663
6476,6477,Alan,Kujawiak,Spółdzielnia Jamrożek-Litwinowicz i syn s.c.,anna-maria56@example.org,534 429 127,Warszawa,Piastowska,51/85
6943,6944,Adrian,Skrzecz,FPUH Stanclik Sp.j.,dawid57@example.com,+48 661 884 614,Warszawa,Konarskiego,248
7158,7159,Kamil,Postawa,PPUH Zdancewicz Sp. z o.o. Sp.k.,pawel27@example.com,793 300 526,Warszawa,Władysława Jagiełły,47
7311,7312,Stanisław,Taczała,Pilipczuk Sp.j.,iwo16@example.net,+48 22 117 86 84,Warszawa,Żwirki i Wigury,505
7562,7563,Rozalia,Burchardt,Basa Sp. z o.o. Sp.k.,konstantysteuer@example.net,+48 574 535 419,Warszawa,Bałtycka,43
7794,7795,Jacek,Bytner,Grupa Fabiańczyk,anna-marianamysl@example.com,+48 732 705 009,Warszawa,Rynek,11
8063,8064,Karol,Labudda,Stowarzyszenie Wojtach-Kucharzyk S.A.,kazimierzhamerla@example.com,+48 503 627 816,Warszawa,Traugutta,36
8375,8376,Konrad,Rakus,Trybała i syn s.c.,lantoszczyk@example.com,500 423 364,Warszawa,Prusa,52
8465,8466,Dominik,Kajdan,Stowarzyszenie Jagieło S.A.,ghass@example.com,+48 662 686 745,Warszawa,Osiedlowa,929
9065,9066,Sandra,Maciejuk,PPUH Grześków Sp.j.,ldomek@example.com,+48 32 154 05 72,Warszawa,Mazurska,988
9172,9173,Kamila,Kołata,Oczko-Janc Sp.k.,atrojanek@example.org,+48 738 465 010,Warszawa,Bankowa,052
9621,9622,Gustaw,Barszczak,Stowarzyszenie Kott-Kosno S.A.,bruno97@example.com,+48 664 842 035,Warszawa,Środkowa,19
9947,9948,Daniel,Świątkiewicz,Rubacha Sp.j.,anita95@example.com,664 177 139,Warszawa,Jaworowa,95
9955,9956,Jakub,Krysta,Kałwa-Szumiec Sp. z o.o. Sp.k.,pietrakjulianna@example.net,533 200 276,Warszawa,Spacerowa,599
9965,9966,Tola,Peda,Fundacja Szmurło Sp.j.,bitnerewa@example.com,+48 697 996 756,Warszawa,Brzechwy,20