In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame(
    {
        "Klient": [
            "Jan Kowalski",
            "Anna Nowak",
            "Piotr Wiśniewski",
            "Maria Dąbrowska",
            "Tomasz Lis",
            "Zdzisław Dyrman",
        ],
        "Wiek": [28, 42, 35, 22, 51, 34],
        "Miasto": ["Warszawa", "Kraków", "Warszawa", "Gdańsk", "Kraków", "Sopot"],
        "Kwota_Zakupow": [1250.50, 4300.00, 890.20, 310.00, 2150.00, 1500],
        "Status": ["Aktywny", "VIP", "Aktywny", "Nowy", "VIP", "Aktywny"],
    }
)
df

             Klient  Wiek    Miasto  Kwota_Zakupow   Status
0      Jan Kowalski    28  Warszawa         1250.5  Aktywny
1        Anna Nowak    42    Kraków         4300.0      VIP
2  Piotr Wiśniewski    35  Warszawa          890.2  Aktywny
3   Maria Dąbrowska    22    Gdańsk          310.0     Nowy
4        Tomasz Lis    51    Kraków         2150.0      VIP
5   Zdzisław Dyrman    34     Sopot         1500.0  Aktywny

In [3]:
# .loc - wybeiranie wycinka tabeli wg nazw indeksów i kolumn
df.loc[2:4, ['Miasto', 'Status']]

     Miasto   Status
2  Warszawa  Aktywny
3    Gdańsk     Nowy
4    Kraków      VIP

In [4]:
# .iloc - wybeiranie wycinka tabeli wg numerów wierszy i numerów kolumn
df.iloc[2:4, 0:2]

             Klient  Wiek
2  Piotr Wiśniewski    35
3   Maria Dąbrowska    22

In [5]:
df["Miasto"] == "Warszawa"

0     True
1    False
2     True
3    False
4    False
5    False
Name: Miasto, dtype: bool

In [6]:
df["Wiek"] > 30

0    False
1     True
2     True
3    False
4     True
5     True
Name: Wiek, dtype: bool

In [7]:
df[ (df["Wiek"] > 30) ]

             Klient  Wiek    Miasto  Kwota_Zakupow   Status
1        Anna Nowak    42    Kraków         4300.0      VIP
2  Piotr Wiśniewski    35  Warszawa          890.2  Aktywny
4        Tomasz Lis    51    Kraków         2150.0      VIP
5   Zdzisław Dyrman    34     Sopot         1500.0  Aktywny

In [8]:
df[(df["Wiek"] > 30) & (df["Miasto"] == "Warszawa")]

             Klient  Wiek    Miasto  Kwota_Zakupow   Status
2  Piotr Wiśniewski    35  Warszawa          890.2  Aktywny

In [9]:
df[(df["Wiek"] > 30) | (df["Miasto"] == "Warszawa")]

             Klient  Wiek    Miasto  Kwota_Zakupow   Status
0      Jan Kowalski    28  Warszawa         1250.5  Aktywny
1        Anna Nowak    42    Kraków         4300.0      VIP
2  Piotr Wiśniewski    35  Warszawa          890.2  Aktywny
4        Tomasz Lis    51    Kraków         2150.0      VIP
5   Zdzisław Dyrman    34     Sopot         1500.0  Aktywny

In [10]:
(df["Wiek"] > 30) | (df["Miasto"] == "Warszawa")

0     True
1     True
2     True
3    False
4     True
5     True
dtype: bool

In [11]:
df[ df['Miasto'] != "Warszawa"]

            Klient  Wiek  Miasto  Kwota_Zakupow   Status
1       Anna Nowak    42  Kraków         4300.0      VIP
3  Maria Dąbrowska    22  Gdańsk          310.0     Nowy
4       Tomasz Lis    51  Kraków         2150.0      VIP
5  Zdzisław Dyrman    34   Sopot         1500.0  Aktywny

In [12]:
df3 = pd.DataFrame(
    {
        "Klient": [
            "Jan Kowalski",
            None,
            "Piotr Wiśniewski",
            "Maria Dąbrowska",
            "Tomasz Lis",
            "Zdzisław Dyrman",
        ],
        "Wiek": [28, 42, None, 22, 51, None],
        "Miasto": ["Warszawa", "Kraków", "Warszawa", None, "Kraków", "Sopot"],
        "Kwota_Zakupow": [1250.50, 4300.00, 890.20, 310.00, None, 1500],
        "Status": ["Aktywny", "VIP", "Aktywny", "Nowy", "VIP", None],
    },
    index=list("abcdef")
)
df3

             Klient  Wiek    Miasto  Kwota_Zakupow   Status
a      Jan Kowalski  28.0  Warszawa         1250.5  Aktywny
b               NaN  42.0    Kraków         4300.0      VIP
c  Piotr Wiśniewski   NaN  Warszawa          890.2  Aktywny
d   Maria Dąbrowska  22.0       NaN          310.0     Nowy
e        Tomasz Lis  51.0    Kraków            NaN      VIP
f   Zdzisław Dyrman   NaN     Sopot         1500.0      NaN

In [13]:
df3[ df3['Wiek'].isnull() ]

             Klient  Wiek    Miasto  Kwota_Zakupow   Status
c  Piotr Wiśniewski   NaN  Warszawa          890.2  Aktywny
f   Zdzisław Dyrman   NaN     Sopot         1500.0      NaN

In [14]:
# znak ~ to zaprzeczenie warunku
df3[ ~df3["Wiek"].isnull()]

            Klient  Wiek    Miasto  Kwota_Zakupow   Status
a     Jan Kowalski  28.0  Warszawa         1250.5  Aktywny
b              NaN  42.0    Kraków         4300.0      VIP
d  Maria Dąbrowska  22.0       NaN          310.0     Nowy
e       Tomasz Lis  51.0    Kraków            NaN      VIP

In [15]:
df3[~(df3["Miasto"] == "Kraków")]

             Klient  Wiek    Miasto  Kwota_Zakupow   Status
a      Jan Kowalski  28.0  Warszawa         1250.5  Aktywny
c  Piotr Wiśniewski   NaN  Warszawa          890.2  Aktywny
d   Maria Dąbrowska  22.0       NaN          310.0     Nowy
f   Zdzisław Dyrman   NaN     Sopot         1500.0      NaN

In [16]:
df[df["Miasto"].isin(["Warszawa", "Sopot"])]

             Klient  Wiek    Miasto  Kwota_Zakupow   Status
0      Jan Kowalski    28  Warszawa         1250.5  Aktywny
2  Piotr Wiśniewski    35  Warszawa          890.2  Aktywny
5   Zdzisław Dyrman    34     Sopot         1500.0  Aktywny

In [17]:
df

             Klient  Wiek    Miasto  Kwota_Zakupow   Status
0      Jan Kowalski    28  Warszawa         1250.5  Aktywny
1        Anna Nowak    42    Kraków         4300.0      VIP
2  Piotr Wiśniewski    35  Warszawa          890.2  Aktywny
3   Maria Dąbrowska    22    Gdańsk          310.0     Nowy
4        Tomasz Lis    51    Kraków         2150.0      VIP
5   Zdzisław Dyrman    34     Sopot         1500.0  Aktywny

In [18]:
df[
    df["Miasto"].isin(["Warszawa", "Sopot"])
    & (
        (df["Wiek"] > 30)
        | (df["Status"] == 'Nowy')
    )
]

             Klient  Wiek    Miasto  Kwota_Zakupow   Status
2  Piotr Wiśniewski    35  Warszawa          890.2  Aktywny
5   Zdzisław Dyrman    34     Sopot         1500.0  Aktywny

In [19]:
df.query("Wiek >= 18 | Status == 'VIP' and Kwota_Zakupow > 1500")

             Klient  Wiek    Miasto  Kwota_Zakupow   Status
0      Jan Kowalski    28  Warszawa         1250.5  Aktywny
1        Anna Nowak    42    Kraków         4300.0      VIP
2  Piotr Wiśniewski    35  Warszawa          890.2  Aktywny
3   Maria Dąbrowska    22    Gdańsk          310.0     Nowy
4        Tomasz Lis    51    Kraków         2150.0      VIP
5   Zdzisław Dyrman    34     Sopot         1500.0  Aktywny

In [20]:
prog = 2000
typ_klienta = "VIP"
df.query("Wiek >= 18 and Status == @typ_klienta and Kwota_Zakupow > @prog")

       Klient  Wiek  Miasto  Kwota_Zakupow Status
1  Anna Nowak    42  Kraków         4300.0    VIP
4  Tomasz Lis    51  Kraków         2150.0    VIP

In [21]:
wiek_minimalny = 30
lista_miast = ["Warszawa", "Sopot"]

df[
    df["Miasto"].isin(lista_miast)
    & ((df["Wiek"] > wiek_minimalny) | (df["Status"] == typ_klienta))
]

             Klient  Wiek    Miasto  Kwota_Zakupow   Status
2  Piotr Wiśniewski    35  Warszawa          890.2  Aktywny
5   Zdzisław Dyrman    34     Sopot         1500.0  Aktywny

In [22]:
df3

             Klient  Wiek    Miasto  Kwota_Zakupow   Status
a      Jan Kowalski  28.0  Warszawa         1250.5  Aktywny
b               NaN  42.0    Kraków         4300.0      VIP
c  Piotr Wiśniewski   NaN  Warszawa          890.2  Aktywny
d   Maria Dąbrowska  22.0       NaN          310.0     Nowy
e        Tomasz Lis  51.0    Kraków            NaN      VIP
f   Zdzisław Dyrman   NaN     Sopot         1500.0      NaN

In [23]:
# iterowanie po wierszach - .iterrows()
for row_index, row in df3.iterrows():
    print("row_index:", row_index)
    print(row)
    print("--------------")
    print(row['Wiek'])

row_index: a
Klient           Jan Kowalski
Wiek                     28.0
Miasto               Warszawa
Kwota_Zakupow          1250.5
Status                Aktywny
Name: a, dtype: object
--------------
28.0
row_index: b
Klient              NaN
Wiek               42.0
Miasto           Kraków
Kwota_Zakupow    4300.0
Status              VIP
Name: b, dtype: object
--------------
42.0
row_index: c
Klient           Piotr Wiśniewski
Wiek                          NaN
Miasto                   Warszawa
Kwota_Zakupow               890.2
Status                    Aktywny
Name: c, dtype: object
--------------
nan
row_index: d
Klient           Maria Dąbrowska
Wiek                        22.0
Miasto                       NaN
Kwota_Zakupow              310.0
Status                      Nowy
Name: d, dtype: object
--------------
22.0
row_index: e
Klient           Tomasz Lis
Wiek                   51.0
Miasto               Kraków
Kwota_Zakupow           NaN
Status                  VIP
Name: e, dtype: object
--------------
51.0
row_index: f
Klient           Zdzisław Dyrman
Wiek                         NaN
Miasto                     Sopot
Kwota_Zakupow             1500.0
Status                       NaN
Name: f, dtype: object
--------------
nan

In [24]:
# iterowanie po wierszach - .itertuples()
for row in df3.itertuples():
    print(row)
    print(row[4])
    print(row.Kwota_Zakupow)
    print("--------------")

Pandas(Index='a', Klient='Jan Kowalski', Wiek=28.0, Miasto='Warszawa', Kwota_Zakupow=1250.5, Status='Aktywny')
1250.5
1250.5
--------------
Pandas(Index='b', Klient=nan, Wiek=42.0, Miasto='Kraków', Kwota_Zakupow=4300.0, Status='VIP')
4300.0
4300.0
--------------
Pandas(Index='c', Klient='Piotr Wiśniewski', Wiek=nan, Miasto='Warszawa', Kwota_Zakupow=890.2, Status='Aktywny')
890.2
890.2
--------------
Pandas(Index='d', Klient='Maria Dąbrowska', Wiek=22.0, Miasto=nan, Kwota_Zakupow=310.0, Status='Nowy')
310.0
310.0
--------------
Pandas(Index='e', Klient='Tomasz Lis', Wiek=51.0, Miasto='Kraków', Kwota_Zakupow=nan, Status='VIP')
nan
nan
--------------
Pandas(Index='f', Klient='Zdzisław Dyrman', Wiek=nan, Miasto='Sopot', Kwota_Zakupow=1500.0, Status=nan)
1500.0
1500.0
--------------

In [25]:
df3

             Klient  Wiek    Miasto  Kwota_Zakupow   Status
a      Jan Kowalski  28.0  Warszawa         1250.5  Aktywny
b               NaN  42.0    Kraków         4300.0      VIP
c  Piotr Wiśniewski   NaN  Warszawa          890.2  Aktywny
d   Maria Dąbrowska  22.0       NaN          310.0     Nowy
e        Tomasz Lis  51.0    Kraków            NaN      VIP
f   Zdzisław Dyrman   NaN     Sopot         1500.0      NaN

In [26]:
df3['Wiek'].fillna(df3['Wiek'].mean())

a    28.00
b    42.00
c    35.75
d    22.00
e    51.00
f    35.75
Name: Wiek, dtype: float64

In [27]:
df3.fillna({"Wiek": df["Wiek"].median(), "Status": "Nieznany"})

             Klient  Wiek    Miasto  Kwota_Zakupow    Status
a      Jan Kowalski  28.0  Warszawa         1250.5   Aktywny
b               NaN  42.0    Kraków         4300.0       VIP
c  Piotr Wiśniewski  34.5  Warszawa          890.2   Aktywny
d   Maria Dąbrowska  22.0       NaN          310.0      Nowy
e        Tomasz Lis  51.0    Kraków            NaN       VIP
f   Zdzisław Dyrman  34.5     Sopot         1500.0  Nieznany

In [28]:
df3

             Klient  Wiek    Miasto  Kwota_Zakupow   Status
a      Jan Kowalski  28.0  Warszawa         1250.5  Aktywny
b               NaN  42.0    Kraków         4300.0      VIP
c  Piotr Wiśniewski   NaN  Warszawa          890.2  Aktywny
d   Maria Dąbrowska  22.0       NaN          310.0     Nowy
e        Tomasz Lis  51.0    Kraków            NaN      VIP
f   Zdzisław Dyrman   NaN     Sopot         1500.0      NaN

In [29]:
df4 = pd.DataFrame({
    "imie": ["jan", 'anna', 'jan', 'zdzisław', 'anna'],
    "wiek": [40, 30, 35, 40, 30],
})
df4

       imie  wiek
0       jan    40
1      anna    30
2       jan    35
3  zdzisław    40
4      anna    30

In [30]:
# usuwanie duplikatów
df4.drop_duplicates()

       imie  wiek
0       jan    40
1      anna    30
2       jan    35
3  zdzisław    40

In [31]:
df4.drop_duplicates(subset=['imie'])

       imie  wiek
0       jan    40
1      anna    30
3  zdzisław    40

In [32]:
df4.drop_duplicates(subset=["imie"], keep='last')

       imie  wiek
2       jan    35
3  zdzisław    40
4      anna    30

In [41]:
pomiary = pd.DataFrame(
    [
        {"sekunda": 1, "milisekunda": 11, "temperatura": 50},
        {"sekunda": 3, "milisekunda": 31, "temperatura": 56},
        {"sekunda": 2, "milisekunda": 21, "temperatura": 51},
        {"sekunda": 4, "milisekunda": 41, "temperatura": 51},
        {"sekunda": 3, "milisekunda": 32, "temperatura": 55, "cisnienie": 1024.5}
    ]
)
pomiary

   sekunda  milisekunda  temperatura  cisnienie
0        1           11           50        NaN
1        3           31           56        NaN
2        2           21           51        NaN
3        4           41           51        NaN
4        3           32           55     1024.5

In [43]:
pomiary.drop_duplicates(subset=["sekunda"], keep='last')

   sekunda  milisekunda  temperatura  cisnienie
0        1           11           50        NaN
2        2           21           51        NaN
3        4           41           51        NaN
4        3           32           55     1024.5

In [44]:
pomiary.drop_duplicates(subset=["sekunda"], keep="first")

   sekunda  milisekunda  temperatura  cisnienie
0        1           11           50        NaN
1        3           31           56        NaN
2        2           21           51        NaN
3        4           41           51        NaN

In [ ]:
pomiary.sort_values("milisekunda", ascending=True).drop_duplicates(subset=["sekunda"], keep="first")

   sekunda  milisekunda  temperatura  cisnienie
0        1           11           50        NaN
2        2           21           51        NaN
1        3           31           56        NaN
4        3           32           55     1024.5
3        4           41           51        NaN