In [13]:
import pandas as pd
import json
from pathlib import Path

In [14]:
dane_lista = []
for plik in Path("../dane_przykladowe/pogoda").glob("*.json"):
    with open(plik, "r", encoding="utf-8") as f:
        dane_tmp = json.load(f)
        dane_lista.append(dane_tmp)

In [15]:
df = pd.DataFrame(dane_lista)
df

,coord,weather,base,main,visibility,wind,clouds,dt,sys,timezone,id,name,cod
0,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.22, 'feels_like': 27.43, 'temp_min...",10000,"{'speed': 3.6, 'deg': 210}",{'all': 29},1788944397,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,766041,Łomianki Dolne,200
1,"{'lon': 20.9553, 'lat': 52.3349}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.28, 'feels_like': 27.49, 'temp_min...",10000,"{'speed': 3.6, 'deg': 210}",{'all': 29},1788944433,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,766041,Łomianki Dolne,200
2,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.53, 'feels_like': 27.65, 'temp_min...",10000,"{'speed': 5.14, 'deg': 210}",{'all': 29},1788945059,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,7533497,Gmina Łomianki,200
3,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.43, 'feels_like': 27.56, 'temp_min...",10000,"{'speed': 5.14, 'deg': 210}",{'all': 29},1788945661,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,766041,Łomianki Dolne,200
4,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.54, 'feels_like': 27.59, 'temp_min...",10000,"{'speed': 5.14, 'deg': 210}",{'all': 28},1788946264,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,766041,Łomianki Dolne,200
5,"{'lon': 20.9633, 'lat': 52.3278}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.8, 'feels_like': 27.84, 'temp_min'...",10000,"{'speed': 4.63, 'deg': 220}",{'all': 28},1788946665,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,7533497,Gmina Łomianki,200
6,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.96, 'feels_like': 27.99, 'temp_min...",10000,"{'speed': 4.63, 'deg': 220}",{'all': 28},1788947288,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,7533497,Gmina Łomianki,200
7,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.83, 'feels_like': 27.86, 'temp_min...",10000,"{'speed': 4.63, 'deg': 220}",{'all': 28},1788947890,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,7533497,Gmina Łomianki,200
8,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 28.08, 'feels_like': 28.11, 'temp_min...",10000,"{'speed': 4.63, 'deg': 240}",{'all': 28},1788948493,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,7533497,Gmina Łomianki,200
9,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 28.28, 'feels_like': 28.31, 'temp_min...",10000,"{'speed': 4.63, 'deg': 240}",{'all': 28},1788949095,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,7533497,Gmina Łomianki,200

In [16]:
df = pd.concat(
    [
        df,
        pd.json_normalize(df["main"]),
        pd.json_normalize(df["wind"])
    ],
    axis=1 # obok
)
df

,coord,weather,base,main,visibility,wind,clouds,dt,sys,timezone,...,temp,feels_like,temp_min,temp_max,pressure,humidity,sea_level,grnd_level,speed,deg
0,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.22, 'feels_like': 27.43, 'temp_min...",10000,"{'speed': 3.6, 'deg': 210}",{'all': 29},1788944397,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,...,27.22,27.43,25.88,28.17,1006,47,1006,996,3.60,210
1,"{'lon': 20.9553, 'lat': 52.3349}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.28, 'feels_like': 27.49, 'temp_min...",10000,"{'speed': 3.6, 'deg': 210}",{'all': 29},1788944433,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,...,27.28,27.49,25.88,28.26,1006,47,1006,996,3.60,210
2,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.53, 'feels_like': 27.65, 'temp_min...",10000,"{'speed': 5.14, 'deg': 210}",{'all': 29},1788945059,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,...,27.53,27.65,26.08,28.48,1005,46,1005,996,5.14,210
3,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.43, 'feels_like': 27.56, 'temp_min...",10000,"{'speed': 5.14, 'deg': 210}",{'all': 29},1788945661,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,...,27.43,27.56,26.15,28.52,1005,46,1005,996,5.14,210
4,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.54, 'feels_like': 27.59, 'temp_min...",10000,"{'speed': 5.14, 'deg': 210}",{'all': 28},1788946264,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,...,27.54,27.59,26.24,28.52,1006,45,1006,996,5.14,210
5,"{'lon': 20.9633, 'lat': 52.3278}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.8, 'feels_like': 27.84, 'temp_min'...",10000,"{'speed': 4.63, 'deg': 220}",{'all': 28},1788946665,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,...,27.80,27.84,26.79,29.07,1006,45,1006,996,4.63,220
6,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.96, 'feels_like': 27.99, 'temp_min...",10000,"{'speed': 4.63, 'deg': 220}",{'all': 28},1788947288,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,...,27.96,27.99,26.48,29.08,1006,45,1006,996,4.63,220
7,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.83, 'feels_like': 27.86, 'temp_min...",10000,"{'speed': 4.63, 'deg': 220}",{'all': 28},1788947890,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,...,27.83,27.86,26.68,29.08,1006,45,1006,996,4.63,220
8,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 28.08, 'feels_like': 28.11, 'temp_min...",10000,"{'speed': 4.63, 'deg': 240}",{'all': 28},1788948493,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,...,28.08,28.11,26.98,29.10,1005,45,1005,996,4.63,240
9,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 28.28, 'feels_like': 28.31, 'temp_min...",10000,"{'speed': 4.63, 'deg': 240}",{'all': 28},1788949095,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,...,28.28,28.31,27.18,29.63,1005,45,1005,996,4.63,240

In [17]:
df["weather"].explode()

0    {'id': 802, 'main': 'Clouds', 'description': '...
1    {'id': 802, 'main': 'Clouds', 'description': '...
2    {'id': 802, 'main': 'Clouds', 'description': '...
3    {'id': 802, 'main': 'Clouds', 'description': '...
4    {'id': 802, 'main': 'Clouds', 'description': '...
5    {'id': 802, 'main': 'Clouds', 'description': '...
6    {'id': 802, 'main': 'Clouds', 'description': '...
7    {'id': 802, 'main': 'Clouds', 'description': '...
8    {'id': 802, 'main': 'Clouds', 'description': '...
9    {'id': 802, 'main': 'Clouds', 'description': '...
Name: weather, dtype: object

In [18]:
df["weather_exploded"] = df["weather"].explode()

In [19]:
df = pd.concat(
    [df, pd.json_normalize(df["weather_exploded"])],
    axis=1,  # obok
)
df

,coord,weather,base,main,visibility,wind,clouds,dt,sys,timezone,...,humidity,sea_level,grnd_level,speed,deg,weather_exploded,id,main,description,icon
0,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.22, 'feels_like': 27.43, 'temp_min...",10000,"{'speed': 3.6, 'deg': 210}",{'all': 29},1788944397,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,...,47,1006,996,3.60,210,"{'id': 802, 'main': 'Clouds', 'description': '...",802,Clouds,scattered clouds,03d
1,"{'lon': 20.9553, 'lat': 52.3349}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.28, 'feels_like': 27.49, 'temp_min...",10000,"{'speed': 3.6, 'deg': 210}",{'all': 29},1788944433,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,...,47,1006,996,3.60,210,"{'id': 802, 'main': 'Clouds', 'description': '...",802,Clouds,scattered clouds,03d
2,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.53, 'feels_like': 27.65, 'temp_min...",10000,"{'speed': 5.14, 'deg': 210}",{'all': 29},1788945059,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,...,46,1005,996,5.14,210,"{'id': 802, 'main': 'Clouds', 'description': '...",802,Clouds,scattered clouds,03d
3,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.43, 'feels_like': 27.56, 'temp_min...",10000,"{'speed': 5.14, 'deg': 210}",{'all': 29},1788945661,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,...,46,1005,996,5.14,210,"{'id': 802, 'main': 'Clouds', 'description': '...",802,Clouds,scattered clouds,03d
4,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.54, 'feels_like': 27.59, 'temp_min...",10000,"{'speed': 5.14, 'deg': 210}",{'all': 28},1788946264,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,...,45,1006,996,5.14,210,"{'id': 802, 'main': 'Clouds', 'description': '...",802,Clouds,scattered clouds,03d
5,"{'lon': 20.9633, 'lat': 52.3278}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.8, 'feels_like': 27.84, 'temp_min'...",10000,"{'speed': 4.63, 'deg': 220}",{'all': 28},1788946665,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,...,45,1006,996,4.63,220,"{'id': 802, 'main': 'Clouds', 'description': '...",802,Clouds,scattered clouds,03d
6,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.96, 'feels_like': 27.99, 'temp_min...",10000,"{'speed': 4.63, 'deg': 220}",{'all': 28},1788947288,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,...,45,1006,996,4.63,220,"{'id': 802, 'main': 'Clouds', 'description': '...",802,Clouds,scattered clouds,03d
7,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.83, 'feels_like': 27.86, 'temp_min...",10000,"{'speed': 4.63, 'deg': 220}",{'all': 28},1788947890,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,...,45,1006,996,4.63,220,"{'id': 802, 'main': 'Clouds', 'description': '...",802,Clouds,scattered clouds,03d
8,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 28.08, 'feels_like': 28.11, 'temp_min...",10000,"{'speed': 4.63, 'deg': 240}",{'all': 28},1788948493,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,...,45,1005,996,4.63,240,"{'id': 802, 'main': 'Clouds', 'description': '...",802,Clouds,scattered clouds,03d
9,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 28.28, 'feels_like': 28.31, 'temp_min...",10000,"{'speed': 4.63, 'deg': 240}",{'all': 28},1788949095,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,...,45,1005,996,4.63,240,"{'id': 802, 'main': 'Clouds', 'description': '...",802,Clouds,scattered clouds,03d

In [20]:
# usuwanie kolumn
df = df.drop(columns=["main", "wind", "weather_exploded", "weather"])
df

,coord,base,visibility,clouds,dt,sys,timezone,id,name,cod,...,temp_max,pressure,humidity,sea_level,grnd_level,speed,deg,id,description,icon
0,"{'lon': 20.9579, 'lat': 52.3314}",stations,10000,{'all': 29},1788944397,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,766041,Łomianki Dolne,200,...,28.17,1006,47,1006,996,3.60,210,802,scattered clouds,03d
1,"{'lon': 20.9553, 'lat': 52.3349}",stations,10000,{'all': 29},1788944433,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,766041,Łomianki Dolne,200,...,28.26,1006,47,1006,996,3.60,210,802,scattered clouds,03d
2,"{'lon': 20.9579, 'lat': 52.3314}",stations,10000,{'all': 29},1788945059,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,7533497,Gmina Łomianki,200,...,28.48,1005,46,1005,996,5.14,210,802,scattered clouds,03d
3,"{'lon': 20.9579, 'lat': 52.3314}",stations,10000,{'all': 29},1788945661,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,766041,Łomianki Dolne,200,...,28.52,1005,46,1005,996,5.14,210,802,scattered clouds,03d
4,"{'lon': 20.9579, 'lat': 52.3314}",stations,10000,{'all': 28},1788946264,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,766041,Łomianki Dolne,200,...,28.52,1006,45,1006,996,5.14,210,802,scattered clouds,03d
5,"{'lon': 20.9633, 'lat': 52.3278}",stations,10000,{'all': 28},1788946665,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,7533497,Gmina Łomianki,200,...,29.07,1006,45,1006,996,4.63,220,802,scattered clouds,03d
6,"{'lon': 20.9579, 'lat': 52.3314}",stations,10000,{'all': 28},1788947288,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,7533497,Gmina Łomianki,200,...,29.08,1006,45,1006,996,4.63,220,802,scattered clouds,03d
7,"{'lon': 20.9579, 'lat': 52.3314}",stations,10000,{'all': 28},1788947890,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,7533497,Gmina Łomianki,200,...,29.08,1006,45,1006,996,4.63,220,802,scattered clouds,03d
8,"{'lon': 20.9579, 'lat': 52.3314}",stations,10000,{'all': 28},1788948493,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,7533497,Gmina Łomianki,200,...,29.10,1005,45,1005,996,4.63,240,802,scattered clouds,03d
9,"{'lon': 20.9579, 'lat': 52.3314}",stations,10000,{'all': 28},1788949095,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,7533497,Gmina Łomianki,200,...,29.63,1005,45,1005,996,4.63,240,802,scattered clouds,03d

In [21]:
df["pressure"].mean()

np.float64(1005.6)

In [22]:
df.columns

Index(['coord', 'base', 'visibility', 'clouds', 'dt', 'sys', 'timezone', 'id',
       'name', 'cod', 'temp', 'feels_like', 'temp_min', 'temp_max', 'pressure',
       'humidity', 'sea_level', 'grnd_level', 'speed', 'deg', 'id',
       'description', 'icon'],
      dtype='str')

In [23]:
df.value_counts("name")

name
Gmina Łomianki    6
Łomianki Dolne    4
Name: count, dtype: int64

In [24]:
# miasto ; ludzie
# wawa ; [jan, maria, tomek]
# krk ; [józek,zdzichu]


# miasto ; ludz
# wawa ; jan
# wawa ; maria
# wawa ; tomek
# krk ; jozek
# krk ; zdzichu