In [1]:
import pandas as pd
import numpy as np

In [2]:
daty_str = ['2026-01-15 18:56', '15.10.2025', '01/04/2024 05:34']

In [5]:
pd.to_datetime(daty_str, format='mixed', dayfirst=True)

DatetimeIndex(['2026-01-15 18:56:00', '2025-10-15 00:00:00',
               '2024-04-01 05:34:00'],
              dtype='datetime64[us]', freq=None)

In [8]:
daty_str = ["2026-01-15 18:56", "15.10.2025", "01/04/2024 05:34", "jakies bzdurki"]
pd.to_datetime(daty_str, format="mixed", dayfirst=True, errors='coerce')

DatetimeIndex(['2026-01-15 18:56:00', '2025-10-15 00:00:00',
               '2024-04-01 05:34:00', 'NaT'],
              dtype='datetime64[us]', freq=None)

In [12]:
daty_str = [
    "2026-01-15 18:56",
    "15.10.2025",
    "01/04/2024 05:34",
    "jakies bzdurki",
    "2026-09-29T06:43:25.963728+02:00",
]
pd.to_datetime(daty_str, format="mixed", dayfirst=True, errors="coerce", utc=True)

DatetimeIndex([       '2026-01-15 18:56:00+00:00',
                      '2025-10-15 00:00:00+00:00',
                      '2024-04-01 05:34:00+00:00',
                                            'NaT',
               '2026-09-29 04:43:25.963728+00:00'],
              dtype='datetime64[us, UTC]', freq=None)

In [55]:
daty_str = [
    "2026-01-19 08:56",
    "2026-10-05 18:56",
    "2026-05-05 14:56",
    "2026-06-10 11:56",
    "2026-11-25 01:56",
    "2026-09-26 01:56",
    "2026-11-25 01:56:45",
]
pd.to_datetime(daty_str, format="%Y-%m-%d %H:%M", errors='coerce')

DatetimeIndex(['2026-01-19 08:56:00', '2026-10-05 18:56:00',
               '2026-05-05 14:56:00', '2026-06-10 11:56:00',
               '2026-11-25 01:56:00', '2026-09-26 01:56:00',
                               'NaT'],
              dtype='datetime64[us]', freq=None)

In [56]:
df = pd.DataFrame(
    {"dt": pd.to_datetime(daty_str, format="%Y-%m-%d %H:%M", errors="coerce")}
)
df

                   dt
0 2026-01-19 08:56:00
1 2026-10-05 18:56:00
2 2026-05-05 14:56:00
3 2026-06-10 11:56:00
4 2026-11-25 01:56:00
5 2026-09-26 01:56:00
6                 NaT

In [57]:
df.dropna()

                   dt
0 2026-01-19 08:56:00
1 2026-10-05 18:56:00
2 2026-05-05 14:56:00
3 2026-06-10 11:56:00
4 2026-11-25 01:56:00
5 2026-09-26 01:56:00

In [58]:
df['dt'].dt.year

0    2026.0
1    2026.0
2    2026.0
3    2026.0
4    2026.0
5    2026.0
6       NaN
Name: dt, dtype: float64

In [59]:
df["dt"].dt.month

0     1.0
1    10.0
2     5.0
3     6.0
4    11.0
5     9.0
6     NaN
Name: dt, dtype: float64

In [60]:
df["dt"].dt.day

0    19.0
1     5.0
2     5.0
3    10.0
4    25.0
5    26.0
6     NaN
Name: dt, dtype: float64

In [61]:
df["dt"].dt.hour

0     8.0
1    18.0
2    14.0
3    11.0
4     1.0
5     1.0
6     NaN
Name: dt, dtype: float64

In [62]:
df["dt"].dt.minute

0    56.0
1    56.0
2    56.0
3    56.0
4    56.0
5    56.0
6     NaN
Name: dt, dtype: float64

In [63]:
df["dt"].dt.day_of_week

0    0.0
1    0.0
2    1.0
3    2.0
4    2.0
5    5.0
6    NaN
Name: dt, dtype: float64

In [65]:
df['typ_dnia']= np.where(df["dt"].dt.day_of_week >= 5, "weekend", "dzień roboczy")
df

                   dt       typ_dnia
0 2026-01-19 08:56:00  dzień roboczy
1 2026-10-05 18:56:00  dzień roboczy
2 2026-05-05 14:56:00  dzień roboczy
3 2026-06-10 11:56:00  dzień roboczy
4 2026-11-25 01:56:00  dzień roboczy
5 2026-09-26 01:56:00        weekend
6                 NaT  dzień roboczy

In [ ]:
pd.to_datetime("2026-09-29").day_of_week

1

In [ ]:
# nazwa tygodnai po polsku
pd.to_datetime("2026-09-29").day_name(locale='pl_PL')

'Wtorek'

In [ ]:
# po szwedzku
pd.to_datetime("2026-09-29").day_name(locale="sv_SE")

'Tisdag'

In [36]:
df = df.dropna()
df['year'] = df["dt"].dt.year
df['month'] = df["dt"].dt.month
df['day'] = df["dt"].dt.day
df['hour'] = df["dt"].dt.hour
df['minute'] = df["dt"].dt.minute
df['day_of_week'] = df["dt"].dt.day_of_week
df['day_name'] = df["dt"].dt.day_name(locale='pl_PL')
df

,dt,year,month,day,hour,minute,day_of_week,day_name
0,2026-01-19 08:56:00,2026,1,19,8,56,0,Poniedziałek
1,2026-10-05 18:56:00,2026,10,5,18,56,0,Poniedziałek
2,2026-05-05 14:56:00,2026,5,5,14,56,1,Wtorek
3,2026-06-10 11:56:00,2026,6,10,11,56,2,Środa
4,2026-11-25 01:56:00,2026,11,25,1,56,2,Środa

In [ ]:
ts = 1788946665_000_000_000 # timestamp w nanosekundach
pd.Timestamp(ts_input=ts)

Timestamp('2026-09-09 09:37:45')

In [45]:
import json
from pathlib import Path

dane_lista = []
for plik in Path("../dane_przykladowe/pogoda").glob("*.json"):
    with open(plik, "r", encoding="utf-8") as f:
        dane_tmp = json.load(f)
        dane_lista.append(dane_tmp)

df_pogoda = pd.DataFrame(dane_lista)
df_pogoda

,coord,weather,base,main,visibility,wind,clouds,dt,sys,timezone,id,name,cod
0,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.22, 'feels_like': 27.43, 'temp_min...",10000,"{'speed': 3.6, 'deg': 210}",{'all': 29},1788944397,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,766041,Łomianki Dolne,200
1,"{'lon': 20.9553, 'lat': 52.3349}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.28, 'feels_like': 27.49, 'temp_min...",10000,"{'speed': 3.6, 'deg': 210}",{'all': 29},1788944433,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,766041,Łomianki Dolne,200
2,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.53, 'feels_like': 27.65, 'temp_min...",10000,"{'speed': 5.14, 'deg': 210}",{'all': 29},1788945059,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,7533497,Gmina Łomianki,200
3,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.43, 'feels_like': 27.56, 'temp_min...",10000,"{'speed': 5.14, 'deg': 210}",{'all': 29},1788945661,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,766041,Łomianki Dolne,200
4,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.54, 'feels_like': 27.59, 'temp_min...",10000,"{'speed': 5.14, 'deg': 210}",{'all': 28},1788946264,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,766041,Łomianki Dolne,200
5,"{'lon': 20.9633, 'lat': 52.3278}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.8, 'feels_like': 27.84, 'temp_min'...",10000,"{'speed': 4.63, 'deg': 220}",{'all': 28},1788946665,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,7533497,Gmina Łomianki,200
6,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.96, 'feels_like': 27.99, 'temp_min...",10000,"{'speed': 4.63, 'deg': 220}",{'all': 28},1788947288,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,7533497,Gmina Łomianki,200
7,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.83, 'feels_like': 27.86, 'temp_min...",10000,"{'speed': 4.63, 'deg': 220}",{'all': 28},1788947890,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,7533497,Gmina Łomianki,200
8,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 28.08, 'feels_like': 28.11, 'temp_min...",10000,"{'speed': 4.63, 'deg': 240}",{'all': 28},1788948493,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,7533497,Gmina Łomianki,200
9,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 28.28, 'feels_like': 28.31, 'temp_min...",10000,"{'speed': 4.63, 'deg': 240}",{'all': 28},1788949095,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,7533497,Gmina Łomianki,200

In [51]:
%%timeit
df_pogoda["dt"].map(
    lambda dt: pd.Timestamp(ts_input=dt* 1_000_000_000)
)

181 μs ± 22.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [52]:
%%timeit
df_pogoda["dt"].apply(lambda dt: pd.Timestamp(ts_input=dt * 1_000_000_000))

164 μs ± 4.44 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [54]:
df_pogoda["datetime"] = df_pogoda["dt"].apply(
    lambda dt: pd.Timestamp(ts_input=dt * 1_000_000_000)
)

df_pogoda["year"] = df_pogoda["datetime"].dt.year
df_pogoda["month"] = df_pogoda["datetime"].dt.month
df_pogoda["day"] = df_pogoda["datetime"].dt.day
df_pogoda["hour"] = df_pogoda["datetime"].dt.hour
df_pogoda["minute"] = df_pogoda["datetime"].dt.minute
df_pogoda["day_of_week"] = df_pogoda["datetime"].dt.day_of_week
df_pogoda["day_name"] = df_pogoda["datetime"].dt.day_name(locale="pl_PL")

df_pogoda

,coord,weather,base,main,visibility,wind,clouds,dt,sys,timezone,...,name,cod,datetime,year,month,day,hour,minute,day_of_week,day_name
0,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.22, 'feels_like': 27.43, 'temp_min...",10000,"{'speed': 3.6, 'deg': 210}",{'all': 29},1788944397,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,...,Łomianki Dolne,200,2026-09-09 08:59:57,2026,9,9,8,59,2,Środa
1,"{'lon': 20.9553, 'lat': 52.3349}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.28, 'feels_like': 27.49, 'temp_min...",10000,"{'speed': 3.6, 'deg': 210}",{'all': 29},1788944433,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,...,Łomianki Dolne,200,2026-09-09 09:00:33,2026,9,9,9,0,2,Środa
2,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.53, 'feels_like': 27.65, 'temp_min...",10000,"{'speed': 5.14, 'deg': 210}",{'all': 29},1788945059,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,...,Gmina Łomianki,200,2026-09-09 09:10:59,2026,9,9,9,10,2,Środa
3,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.43, 'feels_like': 27.56, 'temp_min...",10000,"{'speed': 5.14, 'deg': 210}",{'all': 29},1788945661,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,...,Łomianki Dolne,200,2026-09-09 09:21:01,2026,9,9,9,21,2,Środa
4,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.54, 'feels_like': 27.59, 'temp_min...",10000,"{'speed': 5.14, 'deg': 210}",{'all': 28},1788946264,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,...,Łomianki Dolne,200,2026-09-09 09:31:04,2026,9,9,9,31,2,Środa
5,"{'lon': 20.9633, 'lat': 52.3278}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.8, 'feels_like': 27.84, 'temp_min'...",10000,"{'speed': 4.63, 'deg': 220}",{'all': 28},1788946665,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,...,Gmina Łomianki,200,2026-09-09 09:37:45,2026,9,9,9,37,2,Środa
6,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.96, 'feels_like': 27.99, 'temp_min...",10000,"{'speed': 4.63, 'deg': 220}",{'all': 28},1788947288,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,...,Gmina Łomianki,200,2026-09-09 09:48:08,2026,9,9,9,48,2,Środa
7,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 27.83, 'feels_like': 27.86, 'temp_min...",10000,"{'speed': 4.63, 'deg': 220}",{'all': 28},1788947890,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,...,Gmina Łomianki,200,2026-09-09 09:58:10,2026,9,9,9,58,2,Środa
8,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 28.08, 'feels_like': 28.11, 'temp_min...",10000,"{'speed': 4.63, 'deg': 240}",{'all': 28},1788948493,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,...,Gmina Łomianki,200,2026-09-09 10:08:13,2026,9,9,10,8,2,Środa
9,"{'lon': 20.9579, 'lat': 52.3314}","[{'id': 802, 'main': 'Clouds', 'description': ...",stations,"{'temp': 28.28, 'feels_like': 28.31, 'temp_min...",10000,"{'speed': 4.63, 'deg': 240}",{'all': 28},1788949095,"{'type': 2, 'id': 2000992, 'country': 'PL', 's...",7200,...,Gmina Łomianki,200,2026-09-09 10:18:15,2026,9,9,10,18,2,Środa

In [ ]:
pd.Timedelta(days=5, hours=4, minutes=13)

5

In [93]:
pd.Timestamp.now()

Timestamp('2026-09-29 13:43:46.357266')

In [ ]:
df_pogoda['jak_dawno'] = df_pogoda["datetime"] - pd.Timestamp.now()
df_pogoda["jak_dawno_dni"] = df_pogoda["jak_dawno"].dt.days
df_pogoda["jak_dawno_godziny"] = df_pogoda["jak_dawno"].dt.as_unit('s')/3600
df_pogoda["jak_dawno_godziny"] = df_pogoda["jak_dawno_godziny"].astype(int)

df_pogoda.iloc[ : , 15:]

,month,day,hour,minute,day_of_week,day_name,jak_dawno,jak_dawno_dni,jak_dawno_godziny
0,9,9,8,59,2,Środa,-21 days +19:09:13.568683,-21,-1 days +23:51:56
1,9,9,9,0,2,Środa,-21 days +19:09:49.568683,-21,-1 days +23:51:56
2,9,9,9,10,2,Środa,-21 days +19:20:15.568683,-21,-1 days +23:51:56
3,9,9,9,21,2,Środa,-21 days +19:30:17.568683,-21,-1 days +23:51:56
4,9,9,9,31,2,Środa,-21 days +19:40:20.568683,-21,-1 days +23:51:56
5,9,9,9,37,2,Środa,-21 days +19:47:01.568683,-21,-1 days +23:51:56
6,9,9,9,48,2,Środa,-21 days +19:57:24.568683,-21,-1 days +23:51:56
7,9,9,9,58,2,Środa,-21 days +20:07:26.568683,-21,-1 days +23:51:57
8,9,9,10,8,2,Środa,-21 days +20:17:29.568683,-21,-1 days +23:51:57
9,9,9,10,18,2,Środa,-21 days +20:27:31.568683,-21,-1 days +23:51:57

In [ ]:
pd.bdate_range('2026-09-28', periods=10, )

DatetimeIndex(['2026-09-28', '2026-09-29', '2026-09-30', '2026-10-01',
               '2026-10-02', '2026-10-05', '2026-10-06', '2026-10-07',
               '2026-10-08', '2026-10-09'],
              dtype='datetime64[us]', freq='B')

In [123]:
pd.date_range("2026-09-29 14:00", periods=100, freq='D')

DatetimeIndex(['2026-09-29 14:00:00', '2026-09-30 14:00:00',
               '2026-10-01 14:00:00', '2026-10-02 14:00:00',
               '2026-10-03 14:00:00', '2026-10-04 14:00:00',
               '2026-10-05 14:00:00', '2026-10-06 14:00:00',
               '2026-10-07 14:00:00', '2026-10-08 14:00:00',
               '2026-10-09 14:00:00', '2026-10-10 14:00:00',
               '2026-10-11 14:00:00', '2026-10-12 14:00:00',
               '2026-10-13 14:00:00', '2026-10-14 14:00:00',
               '2026-10-15 14:00:00', '2026-10-16 14:00:00',
               '2026-10-17 14:00:00', '2026-10-18 14:00:00',
               '2026-10-19 14:00:00', '2026-10-20 14:00:00',
               '2026-10-21 14:00:00', '2026-10-22 14:00:00',
               '2026-10-23 14:00:00', '2026-10-24 14:00:00',
               '2026-10-25 14:00:00', '2026-10-26 14:00:00',
               '2026-10-27 14:00:00', '2026-10-28 14:00:00',
               '2026-10-29 14:00:00', '2026-10-30 14:00:00',
               '2026-10-31 14:00:00', '2026-11-01 14:00:00',
               '2026-11-02 14:00:00', '2026-11-03 14:00:00',
               '2026-11-04 14:00:00', '2026-11-05 14:00:00',
               '2026-11-06 14:00:00', '2026-11-07 14:00:00',
               '2026-11-08 14:00:00', '2026-11-09 14:00:00',
               '2026-11-10 14:00:00', '2026-11-11 14:00:00',
               '2026-11-12 14:00:00', '2026-11-13 14:00:00',
               '2026-11-14 14:00:00', '2026-11-15 14:00:00',
               '2026-11-16 14:00:00', '2026-11-17 14:00:00',
               '2026-11-18 14:00:00', '2026-11-19 14:00:00',
               '2026-11-20 14:00:00', '2026-11-21 14:00:00',
               '2026-11-22 14:00:00', '2026-11-23 14:00:00',
               '2026-11-24 14:00:00', '2026-11-25 14:00:00',
               '2026-11-26 14:00:00', '2026-11-27 14:00:00',
               '2026-11-28 14:00:00', '2026-11-29 14:00:00',
               '2026-11-30 14:00:00', '2026-12-01 14:00:00',
               '2026-12-02 14:00:00', '2026-12-03 14:00:00',
               '2026-12-04 14:00:00', '2026-12-05 14:00:00',
               '2026-12-06 14:00:00', '2026-12-07 14:00:00',
               '2026-12-08 14:00:00', '2026-12-09 14:00:00',
               '2026-12-10 14:00:00', '2026-12-11 14:00:00',
               '2026-12-12 14:00:00', '2026-12-13 14:00:00',
               '2026-12-14 14:00:00', '2026-12-15 14:00:00',
               '2026-12-16 14:00:00', '2026-12-17 14:00:00',
               '2026-12-18 14:00:00', '2026-12-19 14:00:00',
               '2026-12-20 14:00:00', '2026-12-21 14:00:00',
               '2026-12-22 14:00:00', '2026-12-23 14:00:00',
               '2026-12-24 14:00:00', '2026-12-25 14:00:00',
               '2026-12-26 14:00:00', '2026-12-27 14:00:00',
               '2026-12-28 14:00:00', '2026-12-29 14:00:00',
               '2026-12-30 14:00:00', '2026-12-31 14:00:00',
               '2027-01-01 14:00:00', '2027-01-02 14:00:00',
               '2027-01-03 14:00:00', '2027-01-04 14:00:00',
               '2027-01-05 14:00:00', '2027-01-06 14:00:00'],
              dtype='datetime64[us]', freq='D')

In [124]:
pd.date_range("2026-09-29 14:00", periods=100, freq=pd.Timedelta(days=1, hours=4, minutes=15))

DatetimeIndex(['2026-09-29 14:00:00', '2026-09-30 18:15:00',
               '2026-10-01 22:30:00', '2026-10-03 02:45:00',
               '2026-10-04 07:00:00', '2026-10-05 11:15:00',
               '2026-10-06 15:30:00', '2026-10-07 19:45:00',
               '2026-10-09 00:00:00', '2026-10-10 04:15:00',
               '2026-10-11 08:30:00', '2026-10-12 12:45:00',
               '2026-10-13 17:00:00', '2026-10-14 21:15:00',
               '2026-10-16 01:30:00', '2026-10-17 05:45:00',
               '2026-10-18 10:00:00', '2026-10-19 14:15:00',
               '2026-10-20 18:30:00', '2026-10-21 22:45:00',
               '2026-10-23 03:00:00', '2026-10-24 07:15:00',
               '2026-10-25 11:30:00', '2026-10-26 15:45:00',
               '2026-10-27 20:00:00', '2026-10-29 00:15:00',
               '2026-10-30 04:30:00', '2026-10-31 08:45:00',
               '2026-11-01 13:00:00', '2026-11-02 17:15:00',
               '2026-11-03 21:30:00', '2026-11-05 01:45:00',
               '2026-11-06 06:00:00', '2026-11-07 10:15:00',
               '2026-11-08 14:30:00', '2026-11-09 18:45:00',
               '2026-11-10 23:00:00', '2026-11-12 03:15:00',
               '2026-11-13 07:30:00', '2026-11-14 11:45:00',
               '2026-11-15 16:00:00', '2026-11-16 20:15:00',
               '2026-11-18 00:30:00', '2026-11-19 04:45:00',
               '2026-11-20 09:00:00', '2026-11-21 13:15:00',
               '2026-11-22 17:30:00', '2026-11-23 21:45:00',
               '2026-11-25 02:00:00', '2026-11-26 06:15:00',
               '2026-11-27 10:30:00', '2026-11-28 14:45:00',
               '2026-11-29 19:00:00', '2026-11-30 23:15:00',
               '2026-12-02 03:30:00', '2026-12-03 07:45:00',
               '2026-12-04 12:00:00', '2026-12-05 16:15:00',
               '2026-12-06 20:30:00', '2026-12-08 00:45:00',
               '2026-12-09 05:00:00', '2026-12-10 09:15:00',
               '2026-12-11 13:30:00', '2026-12-12 17:45:00',
               '2026-12-13 22:00:00', '2026-12-15 02:15:00',
               '2026-12-16 06:30:00', '2026-12-17 10:45:00',
               '2026-12-18 15:00:00', '2026-12-19 19:15:00',
               '2026-12-20 23:30:00', '2026-12-22 03:45:00',
               '2026-12-23 08:00:00', '2026-12-24 12:15:00',
               '2026-12-25 16:30:00', '2026-12-26 20:45:00',
               '2026-12-28 01:00:00', '2026-12-29 05:15:00',
               '2026-12-30 09:30:00', '2026-12-31 13:45:00',
               '2027-01-01 18:00:00', '2027-01-02 22:15:00',
               '2027-01-04 02:30:00', '2027-01-05 06:45:00',
               '2027-01-06 11:00:00', '2027-01-07 15:15:00',
               '2027-01-08 19:30:00', '2027-01-09 23:45:00',
               '2027-01-11 04:00:00', '2027-01-12 08:15:00',
               '2027-01-13 12:30:00', '2027-01-14 16:45:00',
               '2027-01-15 21:00:00', '2027-01-17 01:15:00',
               '2027-01-18 05:30:00', '2027-01-19 09:45:00',
               '2027-01-20 14:00:00', '2027-01-21 18:15:00',
               '2027-01-22 22:30:00', '2027-01-24 02:45:00'],
              dtype='datetime64[us]', freq='1695min')

In [128]:
temp_df = pd.DataFrame(
    {
        "czas": pd.date_range("2026-09-28 00:00", periods=7 * 24, freq="h"),
        "temp": np.random.normal(20, 3, size=7 * 24),
    }
)
temp_df = temp_df.set_index("czas")
temp_df

                          temp
czas
2026-09-28 00:00:00  19.759087
2026-09-28 01:00:00  22.447673
2026-09-28 02:00:00  16.417225
2026-09-28 03:00:00  19.659272
2026-09-28 04:00:00  14.958427
...                        ...
2026-10-04 19:00:00  21.154705
2026-10-04 20:00:00  18.757712
2026-10-04 21:00:00  17.778992
2026-10-04 22:00:00  19.005464
2026-10-04 23:00:00  22.778532

[168 rows x 1 columns]

In [130]:
temp_df.resample('D').aggregate({"temp": 'mean'})

                 temp
czas
2026-09-28  19.400824
2026-09-29  19.672132
2026-09-30  19.870910
2026-10-01  20.269086
2026-10-02  18.615331
2026-10-03  20.210595
2026-10-04  18.849826

In [131]:
temp_df.resample(pd.Timedelta(days=2)).aggregate({"temp": "mean"})

                 temp
czas
2026-09-28  19.536478
2026-09-30  20.069998
2026-10-02  19.412963
2026-10-04  18.849826

In [ ]:
temp_df['temp'].rolling(window=10).mean().head(20)

czas
2026-09-28 00:00:00          NaN
2026-09-28 01:00:00          NaN
2026-09-28 02:00:00          NaN
2026-09-28 03:00:00          NaN
2026-09-28 04:00:00          NaN
2026-09-28 05:00:00          NaN
2026-09-28 06:00:00          NaN
2026-09-28 07:00:00          NaN
2026-09-28 08:00:00          NaN
2026-09-28 09:00:00    18.385902
2026-09-28 10:00:00    17.977834
2026-09-28 11:00:00    17.821531
2026-09-28 12:00:00    18.509726
2026-09-28 13:00:00    18.618512
2026-09-28 14:00:00    18.888606
2026-09-28 15:00:00    18.703184
2026-09-28 16:00:00    18.902160
2026-09-28 17:00:00    19.383435
2026-09-28 18:00:00    19.482676
2026-09-28 19:00:00    19.823998
Name: temp, dtype: float64

In [134]:
ceny_akcji = pd.Series(
    100 + np.cumsum(np.random.normal(0.2, 1.5, 100)),
    index=pd.date_range("2024-01-01", periods=100, freq="D"),
)

df_kursy = pd.DataFrame({"Kurs": ceny_akcji})
df_kursy["SMA_14"] = df_kursy["Kurs"].rolling(window=14, min_periods=5).mean()
df_kursy["Gorne_Pasmo"] = df_kursy["SMA_14"] + 2 * df_kursy["Kurs"].rolling(14).std()
df_kursy["Dolne_Pasmo"] = df_kursy["SMA_14"] - 2 * df_kursy["Kurs"].rolling(14).std()
df_kursy.tail()

                  Kurs      SMA_14  Gorne_Pasmo  Dolne_Pasmo
2024-04-05  125.050399  118.518208   128.699751   108.336666
2024-04-06  123.816272  119.422414   129.019672   109.825157
2024-04-07  122.399148  120.184796   128.793109   111.576483
2024-04-08  125.524776  121.105667   128.958981   113.252353
2024-04-09  124.557781  121.947871   128.342449   115.553293

In [135]:
lista = []
for x in range(10):
    lista.append(x*x)

In [136]:
lista

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [138]:
lista2 = [ x*x for x in range(10)]
lista2

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [ ]:
lista3 = []
for x in range(20):
    if x % 2 == 0:
        lista3.append(x * x)

In [139]:
lista3 = [x * x for x in range(20) if x % 2 == 0]
lista3

[0, 4, 16, 36, 64, 100, 144, 196, 256, 324]

In [141]:
lista_a = [1, 2, 3]
lista_b = ['a', 'b', 'c']
for el1, el2 in zip(lista_a, lista_b):
    print(f"el1: {el1}, el2: {el1}")

el1: 1, el2: 1
el1: 2, el2: 2
el1: 3, el2: 3