In [1]:
import pandas as pd

In [2]:
# axis
oceny = pd.DataFrame({
    "Matematyka": [4, 5, 3],
    "Fizyka": [3, 4, 4],
    "Informatyka": [5, 5, 4]},
    index=["Uczeń_1", "Uczeń_2", "Uczeń_3"],
)

oceny

         Matematyka  Fizyka  Informatyka
Uczeń_1           4       3            5
Uczeń_2           5       4            5
Uczeń_3           3       4            4

In [ ]:
# średnia per przedmiot - liczenie kolumnami
oceny.mean(axis=0)

Matematyka     4.000000
Fizyka         3.666667
Informatyka    4.666667
dtype: float64

In [ ]:
# średnia per uczeń - liczenie wierszami
oceny.mean(axis=1)

Uczeń_1    4.000000
Uczeń_2    4.666667
Uczeń_3    3.666667
dtype: float64

In [7]:
def foo(r):
    print(r)
    return True

In [ ]:
oceny['Informatyka'].apply(foo)

5
5
4

Uczeń_1    True
Uczeń_2    True
Uczeń_3    True
Name: Informatyka, dtype: bool

In [10]:
oceny.apply(foo, axis=0)

Uczeń_1    4
Uczeń_2    5
Uczeń_3    3
Name: Matematyka, dtype: int64
Uczeń_1    3
Uczeń_2    4
Uczeń_3    4
Name: Fizyka, dtype: int64
Uczeń_1    5
Uczeń_2    5
Uczeń_3    4
Name: Informatyka, dtype: int64

Matematyka     True
Fizyka         True
Informatyka    True
dtype: bool

In [11]:
oceny.apply(foo, axis=1)

Matematyka     4
Fizyka         3
Informatyka    5
Name: Uczeń_1, dtype: int64
Matematyka     5
Fizyka         4
Informatyka    5
Name: Uczeń_2, dtype: int64
Matematyka     3
Fizyka         4
Informatyka    4
Name: Uczeń_3, dtype: int64

Uczeń_1    True
Uczeń_2    True
Uczeń_3    True
dtype: bool

In [12]:
# pivoty

In [14]:
df_sprzedaz = pd.DataFrame(
    {
        "Miesiac": ["Marzec", "Marzec", "Kwiecień", "Kwiecień"],
        "Region": ["Północ", "Południe", "Północ", "Południe"],
        "Produkt": ["Laptop", "Laptop", "Mysz", "Laptop"],
        "Sprzedaz": [4000, 4200, 150, 4100],
    }
)
df_sprzedaz

    Miesiac    Region Produkt  Sprzedaz
0    Marzec    Północ  Laptop      4000
1    Marzec  Południe  Laptop      4200
2  Kwiecień    Północ    Mysz       150
3  Kwiecień  Południe  Laptop      4100

In [ ]:
df_sprzedaz.pivot_table(
    index=['Region'],
    columns=['Produkt'],
    values=['Sprzedaz'],
    aggfunc='sum',
)

        Sprzedaz
Produkt   Laptop   Mysz
Region
Północ    4000.0  150.0

In [ ]:
df_sprzedaz.pivot_table(
    index=["Region"],
    columns=["Produkt"],
    values=["Sprzedaz"],
    aggfunc="sum",
    fill_value=0,
)

         Sprzedaz
Produkt    Laptop Mysz
Region
Południe     8300    0
Północ       4000  150

In [47]:
tabela_p = df_sprzedaz.pivot_table(
    index=["Region"],
    columns=["Produkt"],
    values=["Sprzedaz"],
    aggfunc="sum",
    fill_value=0,
    margins=True,
    margins_name='SUMA'
)
tabela_p

         Sprzedaz
Produkt    Laptop Mysz   SUMA
Region
Południe     8300    0   8300
Północ       4000  150   4150
SUMA        12300  150  12450

In [48]:
tabela_p.columns

MultiIndex([('Sprzedaz', 'Laptop'),
            ('Sprzedaz',   'Mysz'),
            ('Sprzedaz',   'SUMA')],
           names=[None, 'Produkt'])

In [23]:
tabela_p.index

Index(['Południe', 'Północ', 'SUMA'], dtype='str', name='Region')

In [49]:
tabela_p2 = tabela_p.reset_index(drop=False)
tabela_p2

           Region Sprzedaz
Produkt             Laptop Mysz   SUMA
0        Południe     8300    0   8300
1          Północ     4000  150   4150
2            SUMA    12300  150  12450

In [50]:
tabela_p2.columns

MultiIndex([(  'Region',       ''),
            ('Sprzedaz', 'Laptop'),
            ('Sprzedaz',   'Mysz'),
            ('Sprzedaz',   'SUMA')],
           names=[None, 'Produkt'])

In [28]:
tabela_p.reset_index(drop=True)

        Sprzedaz
Produkt   Laptop Mysz   SUMA
0           8300    0   8300
1           4000  150   4150
2          12300  150  12450

In [51]:
tabela_p2.droplevel(0, axis=1)

Produkt            Laptop  Mysz   SUMA
0        Południe    8300     0   8300
1          Północ    4000   150   4150
2            SUMA   12300   150  12450

In [52]:
tabela_p2

           Region Sprzedaz
Produkt             Laptop Mysz   SUMA
0        Południe     8300    0   8300
1          Północ     4000  150   4150
2            SUMA    12300  150  12450

In [53]:
nowe_nazwy_kolumn = [f"{c[0]}_{c[1]}" for c in tabela_p2.columns]
nowe_nazwy_kolumn

['Region_', 'Sprzedaz_Laptop', 'Sprzedaz_Mysz', 'Sprzedaz_SUMA']

In [54]:
tabela_p2 = tabela_p2.droplevel(0, axis=1)
tabela_p2.columns = nowe_nazwy_kolumn
tabela_p2

    Region_  Sprzedaz_Laptop  Sprzedaz_Mysz  Sprzedaz_SUMA
0  Południe             8300              0           8300
1    Północ             4000            150           4150
2      SUMA            12300            150          12450

In [58]:
# unpivot = melt
tabela_p2.melt(id_vars=["Region_"], )

    Region_         variable  value
0  Południe  Sprzedaz_Laptop   8300
1    Północ  Sprzedaz_Laptop   4000
2      SUMA  Sprzedaz_Laptop  12300
3  Południe    Sprzedaz_Mysz      0
4    Północ    Sprzedaz_Mysz    150
5      SUMA    Sprzedaz_Mysz    150
6  Południe    Sprzedaz_SUMA   8300
7    Północ    Sprzedaz_SUMA   4150
8      SUMA    Sprzedaz_SUMA  12450

In [61]:
movies = pd.read_csv(
    "../dane_przykladowe/kino/static_data.csv",
    sep=";",
    usecols=["movie_title",
             "boxoffice_viewers_weekend_1",
             "boxoffice_viewers_weekend_2",
             "boxoffice_viewers_weekend_3",
             "boxoffice_viewers_weekend_4",
             "boxoffice_viewers_weekend_5",
             "boxoffice_viewers_weekend_6",],
)
movies

,movie_title,boxoffice_viewers_weekend_1,boxoffice_viewers_weekend_2,boxoffice_viewers_weekend_3,boxoffice_viewers_weekend_4,boxoffice_viewers_weekend_5,boxoffice_viewers_weekend_6
0,Tenet,54070,34576,20713,14567,12280,6828
1,Coco,118286,95548,103337,27713,7028,19201
2,#Jestem M. Misfit,72991,44451,19635,7389,7794,5043
3,#WSZYSTKOGRA,35506,29388,9456,3330,382,222
4,(Nie)znajomi,110396,120529,70093,36837,15325,12351
...,...,...,...,...,...,...,...
495,Drive Hard,160,33,33,33,1,1
496,Droga Aszera,200,131,0,110,0,0
497,Droga do Hiszpanii,668,157,38,38,38,38
498,Droga do zapomnienia,21598,13576,2455,4717,4612,919
499,DROGA DO RAJU,668,162,52,14,19,19

In [70]:
movies_metled = movies.melt(id_vars="movie_title", var_name="okres", value_name='widownia')
movies_metled

               movie_title                        okres  widownia
0                    Tenet  boxoffice_viewers_weekend_1     54070
1                     Coco  boxoffice_viewers_weekend_1    118286
2        #Jestem M. Misfit  boxoffice_viewers_weekend_1     72991
3             #WSZYSTKOGRA  boxoffice_viewers_weekend_1     35506
4             (Nie)znajomi  boxoffice_viewers_weekend_1    110396
...                    ...                          ...       ...
2995            Drive Hard  boxoffice_viewers_weekend_6         1
2996          Droga Aszera  boxoffice_viewers_weekend_6         0
2997    Droga do Hiszpanii  boxoffice_viewers_weekend_6        38
2998  Droga do zapomnienia  boxoffice_viewers_weekend_6       919
2999         DROGA DO RAJU  boxoffice_viewers_weekend_6        19

[3000 rows x 3 columns]

na chwilę to odpuśćmy...

In [64]:
# grupowanie
df_kadry = pd.DataFrame(
    {
        "Dzial": ["IT", "IT", "IT", "Marketing", "Marketing", "Finanse"],
        "Pracownik": ["Jan", "Anna", "Tomasz", "Ewa", "Piotr", "Zofia"],
        "Pensja": [16000, 12000, 8000, 11000, 7500, 18000],
        "Staz": [5, 3, 1, 4, 2, 8],
    }
)
df_kadry

       Dzial Pracownik  Pensja  Staz
0         IT       Jan   16000     5
1         IT      Anna   12000     3
2         IT    Tomasz    8000     1
3  Marketing       Ewa   11000     4
4  Marketing     Piotr    7500     2
5    Finanse     Zofia   18000     8

In [65]:
df_kadry.groupby("Dzial").aggregate({"Pensja": ['sum', 'mean'], "Staz": ['min', 'max']})

          Pensja          Staz
             sum     mean  min max
Dzial
Finanse    18000  18000.0    8   8
IT         36000  12000.0    1   5
Marketing  18500   9250.0    2   4

In [66]:
df_kadry.groupby("Dzial", as_index=False).aggregate({"Pensja": ["sum", "mean"], "Staz": ["min", "max"]})

       Dzial Pensja          Staz
                sum     mean  min max
0    Finanse  18000  18000.0    8   8
1         IT  36000  12000.0    1   5
2  Marketing  18500   9250.0    2   4

In [ ]:
df_kadry.groupby("Dzial", as_index=False).aggregate(
    Pensja_suma=('Pensja', 'sum'),
    Srednia_Pensja=('Pensja', 'mean'),
    Staz_min=("Staz", 'min'),
    Staz_max=("Staz", 'max')
)

       Dzial  Pensja_suma  Srednia_Pensja  Staz_min  Staz_max
0    Finanse        18000         18000.0         8         8
1         IT        36000         12000.0         1         5
2  Marketing        18500          9250.0         2         4

In [71]:
movies_metled

               movie_title                        okres  widownia
0                    Tenet  boxoffice_viewers_weekend_1     54070
1                     Coco  boxoffice_viewers_weekend_1    118286
2        #Jestem M. Misfit  boxoffice_viewers_weekend_1     72991
3             #WSZYSTKOGRA  boxoffice_viewers_weekend_1     35506
4             (Nie)znajomi  boxoffice_viewers_weekend_1    110396
...                    ...                          ...       ...
2995            Drive Hard  boxoffice_viewers_weekend_6         1
2996          Droga Aszera  boxoffice_viewers_weekend_6         0
2997    Droga do Hiszpanii  boxoffice_viewers_weekend_6        38
2998  Droga do zapomnienia  boxoffice_viewers_weekend_6       919
2999         DROGA DO RAJU  boxoffice_viewers_weekend_6        19

[3000 rows x 3 columns]

In [75]:
movies_agg = movies_metled.groupby("movie_title", as_index=False).aggregate(
    laczna_widownia=("widownia", "sum")
)
movies_agg

                        movie_title  laczna_widownia
0                 #Jestem M. Misfit           157303
1                      #WSZYSTKOGRA            78284
2                      (Nie)znajomi           365531
3    0.0 MHz Częstotliwość opętania                8
4                         10 000 km             1294
..                              ...              ...
493                           Tenet           143034
494        Trabantem do utraty tchu             1756
495             [REC] 4: Apokalipsa            34752
496                 [Rec] 3: Geneza            33116
497                            Świt            36163

[498 rows x 2 columns]

In [ ]:
# ta agregacja wyżej to odpowiednik w SQL:

# select 
#     movie_title,
#     sum(widownia) as srednia_widownia
# from 
#     movies_metled
# group by
#     movie_title

In [74]:
movies_metled[movies_metled['movie_title'] == 'Tenet']

     movie_title                        okres  widownia
0          Tenet  boxoffice_viewers_weekend_1     54070
500        Tenet  boxoffice_viewers_weekend_2     34576
1000       Tenet  boxoffice_viewers_weekend_3     20713
1500       Tenet  boxoffice_viewers_weekend_4     14567
2000       Tenet  boxoffice_viewers_weekend_5     12280
2500       Tenet  boxoffice_viewers_weekend_6      6828

In [78]:
movies_metled.groupby('movie_title')['widownia'].transform('sum')

0       143034
1       371113
2       157303
3        78284
4       365531
         ...
2995       261
2996       441
2997       977
2998     47877
2999       934
Name: widownia, Length: 3000, dtype: int64

In [81]:
movies_metled["total_widownia"] = movies_metled.groupby("movie_title")[
    "widownia"
].transform("sum")
movies_metled["widownia_pct"] = 100*movies_metled["widownia"] / movies_metled["total_widownia"]
movies_metled

,movie_title,okres,widownia,total_widownia,widownia_pct
0,Tenet,boxoffice_viewers_weekend_1,54070,143034,37.802201
1,Coco,boxoffice_viewers_weekend_1,118286,371113,31.873311
2,#Jestem M. Misfit,boxoffice_viewers_weekend_1,72991,157303,46.401531
3,#WSZYSTKOGRA,boxoffice_viewers_weekend_1,35506,78284,45.355373
4,(Nie)znajomi,boxoffice_viewers_weekend_1,110396,365531,30.201542
...,...,...,...,...,...
2995,Drive Hard,boxoffice_viewers_weekend_6,1,261,0.383142
2996,Droga Aszera,boxoffice_viewers_weekend_6,0,441,0.000000
2997,Droga do Hiszpanii,boxoffice_viewers_weekend_6,38,977,3.889458
2998,Droga do zapomnienia,boxoffice_viewers_weekend_6,919,47877,1.919502
2999,DROGA DO RAJU,boxoffice_viewers_weekend_6,19,934,2.034261

In [82]:
movies_metled.groupby("okres", as_index=False).aggregate(
    Sredni_udzial_weekendu=("widownia_pct", "mean")
)

                         okres  Sredni_udzial_weekendu
0  boxoffice_viewers_weekend_1               48.987591
1  boxoffice_viewers_weekend_2               24.697195
2  boxoffice_viewers_weekend_3               11.915806
3  boxoffice_viewers_weekend_4                6.613274
4  boxoffice_viewers_weekend_5                4.216163
5  boxoffice_viewers_weekend_6                3.143531