In [1]:
import pandas as pd

In [ ]:
# pd.merge(df1, df2)

# df1.join(df2)

In [10]:
klienci = pd.DataFrame(
    {"id": [1, 2, 3, 4],
     "nazwisko": ["Kowalski", "Nowak", "Wiśniewski", "Zielińska"]}
)
zamowienia = pd.DataFrame({
    "id_zam": [101, 102, 103],
    "id_klienta": [1, 2, 1,],
    "kwota": [250.0, 490.0, 333.0]})

In [11]:
pd.merge(klienci, zamowienia, how='left', left_on='id', right_on='id_klienta')

   id    nazwisko  id_zam  id_klienta  kwota
0   1    Kowalski   101.0         1.0  250.0
1   1    Kowalski   103.0         1.0  333.0
2   2       Nowak   102.0         2.0  490.0
3   3  Wiśniewski     NaN         NaN    NaN
4   4   Zielińska     NaN         NaN    NaN

In [12]:
pd.merge(klienci, zamowienia, how="right", left_on="id", right_on="id_klienta")

   id  nazwisko  id_zam  id_klienta  kwota
0   1  Kowalski     101           1  250.0
1   2     Nowak     102           2  490.0
2   1  Kowalski     103           1  333.0

In [5]:
pd.merge(zamowienia, klienci, how="left", left_on="id_klienta", right_on="id")

   id_zam  id_klienta  kwota  id  nazwisko
0     101           1  250.0   1  Kowalski
1     102           2  490.0   2     Nowak

In [6]:
pd.merge(zamowienia, klienci, how="right", left_on="id_klienta", right_on="id")

   id_zam  id_klienta  kwota  id    nazwisko
0   101.0         1.0  250.0   1    Kowalski
1   102.0         2.0  490.0   2       Nowak
2     NaN         NaN    NaN   3  Wiśniewski
3     NaN         NaN    NaN   4   Zielińska

In [13]:
pd.merge(klienci, zamowienia, how="left", left_on="id", right_on="id_klienta", validate="1:1")

MergeError: Merge keys are not unique in right dataset; not a one-to-one merge
Duplicates in right:
  id_klienta
          1 ...

In [14]:
pd.merge(
    klienci, zamowienia, how="left", left_on="id", right_on="id_klienta", validate="1:m"
)

   id    nazwisko  id_zam  id_klienta  kwota
0   1    Kowalski   101.0         1.0  250.0
1   1    Kowalski   103.0         1.0  333.0
2   2       Nowak   102.0         2.0  490.0
3   3  Wiśniewski     NaN         NaN    NaN
4   4   Zielińska     NaN         NaN    NaN

In [15]:
pd.merge(
    klienci,
    zamowienia,
    how="left",
    left_on="id",
    right_on="id_klienta",
    validate="1:m",
    indicator=True,
)

   id    nazwisko  id_zam  id_klienta  kwota     _merge
0   1    Kowalski   101.0         1.0  250.0       both
1   1    Kowalski   103.0         1.0  333.0       both
2   2       Nowak   102.0         2.0  490.0       both
3   3  Wiśniewski     NaN         NaN    NaN  left_only
4   4   Zielińska     NaN         NaN    NaN  left_only

In [ ]:
pd.merge(zamowienia, klienci, how="right", left_on="id_klienta", right_on="id", indicator=True, )

   id_zam  id_klienta  kwota  id    nazwisko      _merge
0   101.0         1.0  250.0   1    Kowalski        both
1   103.0         1.0  333.0   1    Kowalski        both
2   102.0         2.0  490.0   2       Nowak        both
3     NaN         NaN    NaN   3  Wiśniewski  right_only
4     NaN         NaN    NaN   4   Zielińska  right_only

In [19]:
klienci2 = pd.DataFrame(
    {"id": [1, 2, 3, 4], "nazwisko": ["Kowalski", "Nowak", "Wiśniewski", "Zielińska"]}
)
zamowienia2 = pd.DataFrame(
    {
        "id_zam": [101, 102, 103],
        "id": ['a', 'b', 'c'],
        "id_klienta": [
            1,
            2,
            1,
        ],
        "kwota": [250.0, 490.0, 333.0],
    }
)

In [ ]:
pd.merge(
    klienci2,
    zamowienia2,
    how="left",
    left_on="id",
    right_on="id_klienta", suffixes=("_lewa", "_prawa")
)

KeyError: 'id'

In [24]:
df1 = pd.DataFrame(
    {
        "id": [1, 1, 2, 2],
        "kategoria": ["A", "B", "A", "B"],
        "wartosc_1": [10, 20, 30, 40],
    }
)

df2 = pd.DataFrame(
    {
        "id": [1, 2, 2, 3],
        "kategoria": ["A", "A", "B", "A"],
        "wartosc_2": [100, 200, 300, 400],
    }
)

# Łączenie (domyślnie left inner join) po dwóch kolumnach
wynik = pd.merge(df1, df2, on=["id", "kategoria"])
wynik

   id kategoria  wartosc_1  wartosc_2
0   1         A         10        100
1   2         A         30        200
2   2         B         40        300

In [27]:
pd.merge(df1, df2, on="id")

   id kategoria_x  wartosc_1 kategoria_y  wartosc_2
0   1           A         10           A        100
1   1           B         20           A        100
2   2           A         30           A        200
3   2           A         30           B        300
4   2           B         40           A        200
5   2           B         40           B        300

In [26]:
wynik2 = pd.merge(df1, df2, left_on=["id", "kategoria"], right_on=["id", "kategoria"])
wynik2

   id kategoria  wartosc_1  wartosc_2
0   1         A         10        100
1   2         A         30        200
2   2         B         40        300

In [28]:
# merge_asof - łączenie do najbliższego momentu w czasie
transakcje = pd.DataFrame(
    {
        "czas": pd.to_datetime(["10:00", "10:05", "10:07"]),
        "symbol": ["AAA", "AAA", "BBB"],
        "ilosc": [10, 20, 15],
    }
).sort_values("czas")
transakcje

C:\Users\lemur\AppData\Local\Temp\ipykernel_26592\1299881211.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  "czas": pd.to_datetime(["10:00", "10:05", "10:07"]),

                 czas symbol  ilosc
0 2026-09-30 10:00:00    AAA     10
1 2026-09-30 10:05:00    AAA     20
2 2026-09-30 10:07:00    BBB     15

In [ ]:
notowania = pd.DataFrame(
    {
        "czas": pd.to_datetime(["09:59", "10:04", "10:06", "10:08"]),
        "symbol": ["AAA", "AAA", "BBB", "BBB"],
        "cena": [150.0, 151.5, 300.0, 301.0],
    }
).sort_values("czas")
notowania

C:\Users\lemur\AppData\Local\Temp\ipykernel_26592\2718127713.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  "czas": pd.to_datetime(["09:59", "10:04", "10:06", "10:08"]),

                 czas symbol   cena
0 2026-09-30 09:59:00    AAA  150.0
1 2026-09-30 10:04:00    AAA  151.5
2 2026-09-30 10:06:00    BBB  300.0
3 2026-09-30 10:08:00    BBB  301.0

In [30]:
pd.merge_asof(transakcje, notowania, on="czas", by="symbol")

                 czas symbol  ilosc   cena
0 2026-09-30 10:00:00    AAA     10  150.0
1 2026-09-30 10:05:00    AAA     20  151.5
2 2026-09-30 10:07:00    BBB     15  300.0

In [32]:
pd.merge_asof(transakcje, notowania, on="czas", by="symbol", direction='forward')

                 czas symbol  ilosc   cena
0 2026-09-30 10:00:00    AAA     10  151.5
1 2026-09-30 10:05:00    AAA     20    NaN
2 2026-09-30 10:07:00    BBB     15  301.0

In [33]:
pd.merge_asof(transakcje, notowania, on="czas", by="symbol", direction="nearest")

                 czas symbol  ilosc   cena
0 2026-09-30 10:00:00    AAA     10  150.0
1 2026-09-30 10:05:00    AAA     20  151.5
2 2026-09-30 10:07:00    BBB     15  300.0

In [ ]:
# po staremu, na piechotę
pd.merge(transakcje, notowania, on="symbol") \
    .rename(columns={
        "czas_x": "czas_transakcji",
        "czas_y": "czas_notowania"
    }) \
    .assign(
        delta_czas_s=lambda r: (r["czas_transakcji"] - r["czas_notowania"]).dt.seconds
    ) \
    .sort_values(['symbol', 'ilosc', 'delta_czas_s']) \
    .groupby(['symbol', 'ilosc'], as_index=False) \
    .first()

  symbol  ilosc     czas_transakcji      czas_notowania   cena  delta_czas_s
0    AAA     10 2026-09-30 10:00:00 2026-09-30 09:59:00  150.0            60
1    AAA     20 2026-09-30 10:05:00 2026-09-30 10:04:00  151.5            60
2    BBB     15 2026-09-30 10:07:00 2026-09-30 10:06:00  300.0            60