In [1]:
import pandas as pd

In [8]:
movies = pd.read_csv(
    "../dane_przykladowe/kino/static_data.csv",
    sep=";",
    usecols=["movie_title", "boxoffice_viewers_weekend_1", "countries", "genre_list"],
).dropna()
movies

,movie_title,genre_list,countries,boxoffice_viewers_weekend_1
0,Tenet,"1db1ac18-a83d-4645-9cb7-3c60a03012ba,d34b4e2c-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,54070
1,Coco,"4fc66943-7c2c-4e0c-a93f-8f7abb752c8c,15c0b1ce-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,118286
2,#Jestem M. Misfit,"57366ac3-c349-4e55-ad5d-6f8061179e88,ddb001d6-...",c29315d3-7743-480d-ba69-783e11af73bf,72991
3,#WSZYSTKOGRA,"57366ac3-c349-4e55-ad5d-6f8061179e88,cc52ba6b-...",c29315d3-7743-480d-ba69-783e11af73bf,35506
4,(Nie)znajomi,"f0506edd-d123-41d3-ad36-1d31a8bb23b8,57366ac3-...",c29315d3-7743-480d-ba69-783e11af73bf,110396
...,...,...,...,...
495,Drive Hard,"57366ac3-c349-4e55-ad5d-6f8061179e88,d34b4e2c-...","dcbf781d-54a3-4734-9b69-a7e119d59fa5,7bc66e23-...",160
496,Droga Aszera,f0506edd-d123-41d3-ad36-1d31a8bb23b8,"84ba792c-d86a-49a2-96a2-05d3d744cddf,c29315d3-...",200
497,Droga do Hiszpanii,f0506edd-d123-41d3-ad36-1d31a8bb23b8,e9d4935d-ff76-4487-b6fe-c098e0681f47,668
498,Droga do zapomnienia,"36a330ff-bd5d-4a0e-b74c-8a0d4473b778,f0506edd-...",7bc66e23-af7a-4d1d-a72b-b745f9c430d4,21598
499,DROGA DO RAJU,516495a0-f121-4086-9b59-41a2d17bd118,c29315d3-7743-480d-ba69-783e11af73bf,668

In [ ]:
countries_dict = pd.read_csv(
    "../dane_przykladowe/kino/countries.csv",
    sep=";"
)
genres_dict = pd.read_csv("../dane_przykladowe/kino/genres.csv", sep=";")

                                      id              name
0   0376ce5c-766a-4e7c-b5dc-c70563551658   Romantic comedy
1   0453b3cf-3556-43ee-9986-250405910025          genre:33
2   04b0945b-33ba-44c6-9088-919c24abc85e          genre:30
3   05cedac6-2816-49fa-98b7-084beda79acc          Biblijny
4   08db2f75-3b0a-4de3-8b27-fb38be03b1b1              Thor
..                                   ...               ...
93  f0506edd-d123-41d3-ad36-1d31a8bb23b8            Dramat
94  f993c509-cd39-4b0f-903a-c3630b38f7cc  Dramat społeczny
95  fcbf0f68-001f-4106-9f75-92895ed907b9      Propagandowy
96  fe7c2e3f-b22e-4a78-a480-2fe36013ee51        Dla dzieci
97  ffab3c3a-98ff-40f3-84c8-a41b9ebf98a7     Dramat sądowy

[98 rows x 2 columns]

In [9]:
pd.merge(movies, genres_dict, left_on='genre_list', right_on='id')

,movie_title,genre_list,countries,boxoffice_viewers_weekend_1,id,name
0,13 grzechów,d31939d6-e42e-40f4-8e25-f18e47a1e035,dcbf781d-54a3-4734-9b69-a7e119d59fa5,9603,d31939d6-e42e-40f4-8e25-f18e47a1e035,Horror
1,2 dni w Nowym Jorku,57366ac3-c349-4e55-ad5d-6f8061179e88,"51d9043b-068a-4a31-a0fb-74719a5a6a11,6614b794-...",20166,57366ac3-c349-4e55-ad5d-6f8061179e88,Komedia
2,21 x Nowy Jork,2c2fd51f-d2b8-4fb5-aec2-faf911088642,c29315d3-7743-480d-ba69-783e11af73bf,1002,2c2fd51f-d2b8-4fb5-aec2-faf911088642,Dokumentalny
3,3 serca,f0506edd-d123-41d3-ad36-1d31a8bb23b8,"51d9043b-068a-4a31-a0fb-74719a5a6a11,6614b794-...",957,f0506edd-d123-41d3-ad36-1d31a8bb23b8,Dramat
4,30 gramów,f0506edd-d123-41d3-ad36-1d31a8bb23b8,b0233cad-fd3d-4140-b00b-28a045525410,227,f0506edd-d123-41d3-ad36-1d31a8bb23b8,Dramat
...,...,...,...,...,...,...
196,Drapacz chmur,d34b4e2c-74ce-42ab-b438-86fbbdcaee15,dcbf781d-54a3-4734-9b69-a7e119d59fa5,34330,d34b4e2c-74ce-42ab-b438-86fbbdcaee15,Akcja
197,Drive,d34b4e2c-74ce-42ab-b438-86fbbdcaee15,dcbf781d-54a3-4734-9b69-a7e119d59fa5,28492,d34b4e2c-74ce-42ab-b438-86fbbdcaee15,Akcja
198,Droga Aszera,f0506edd-d123-41d3-ad36-1d31a8bb23b8,"84ba792c-d86a-49a2-96a2-05d3d744cddf,c29315d3-...",200,f0506edd-d123-41d3-ad36-1d31a8bb23b8,Dramat
199,Droga do Hiszpanii,f0506edd-d123-41d3-ad36-1d31a8bb23b8,e9d4935d-ff76-4487-b6fe-c098e0681f47,668,f0506edd-d123-41d3-ad36-1d31a8bb23b8,Dramat
200,DROGA DO RAJU,516495a0-f121-4086-9b59-41a2d17bd118,c29315d3-7743-480d-ba69-783e11af73bf,668,516495a0-f121-4086-9b59-41a2d17bd118,Komedia obycz.

In [15]:
movies['lista_gatunkow'] = movies["genre_list"].str.split(",")
movies = movies.explode("lista_gatunkow")
movies

,movie_title,genre_list,countries,boxoffice_viewers_weekend_1,lista_gatunkow
0,Tenet,"1db1ac18-a83d-4645-9cb7-3c60a03012ba,d34b4e2c-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,54070,1db1ac18-a83d-4645-9cb7-3c60a03012ba
0,Tenet,"1db1ac18-a83d-4645-9cb7-3c60a03012ba,d34b4e2c-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,54070,d34b4e2c-74ce-42ab-b438-86fbbdcaee15
0,Tenet,"1db1ac18-a83d-4645-9cb7-3c60a03012ba,d34b4e2c-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,54070,6a5af1f4-128c-4ca8-960d-3f0f36d29764
1,Coco,"4fc66943-7c2c-4e0c-a93f-8f7abb752c8c,15c0b1ce-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,118286,4fc66943-7c2c-4e0c-a93f-8f7abb752c8c
1,Coco,"4fc66943-7c2c-4e0c-a93f-8f7abb752c8c,15c0b1ce-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,118286,15c0b1ce-34ec-4d67-ba14-0138c61d5b54
...,...,...,...,...,...
496,Droga Aszera,f0506edd-d123-41d3-ad36-1d31a8bb23b8,"84ba792c-d86a-49a2-96a2-05d3d744cddf,c29315d3-...",200,f0506edd-d123-41d3-ad36-1d31a8bb23b8
497,Droga do Hiszpanii,f0506edd-d123-41d3-ad36-1d31a8bb23b8,e9d4935d-ff76-4487-b6fe-c098e0681f47,668,f0506edd-d123-41d3-ad36-1d31a8bb23b8
498,Droga do zapomnienia,"36a330ff-bd5d-4a0e-b74c-8a0d4473b778,f0506edd-...",7bc66e23-af7a-4d1d-a72b-b745f9c430d4,21598,36a330ff-bd5d-4a0e-b74c-8a0d4473b778
498,Droga do zapomnienia,"36a330ff-bd5d-4a0e-b74c-8a0d4473b778,f0506edd-...",7bc66e23-af7a-4d1d-a72b-b745f9c430d4,21598,f0506edd-d123-41d3-ad36-1d31a8bb23b8
499,DROGA DO RAJU,516495a0-f121-4086-9b59-41a2d17bd118,c29315d3-7743-480d-ba69-783e11af73bf,668,516495a0-f121-4086-9b59-41a2d17bd118

In [17]:
movies = pd.merge(movies, genres_dict, left_on="lista_gatunkow", right_on="id")
movies

,movie_title,genre_list,countries,boxoffice_viewers_weekend_1,lista_gatunkow,id,name
0,Tenet,"1db1ac18-a83d-4645-9cb7-3c60a03012ba,d34b4e2c-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,54070,1db1ac18-a83d-4645-9cb7-3c60a03012ba,1db1ac18-a83d-4645-9cb7-3c60a03012ba,Thriller
1,Tenet,"1db1ac18-a83d-4645-9cb7-3c60a03012ba,d34b4e2c-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,54070,d34b4e2c-74ce-42ab-b438-86fbbdcaee15,d34b4e2c-74ce-42ab-b438-86fbbdcaee15,Akcja
2,Tenet,"1db1ac18-a83d-4645-9cb7-3c60a03012ba,d34b4e2c-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,54070,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
3,Coco,"4fc66943-7c2c-4e0c-a93f-8f7abb752c8c,15c0b1ce-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,118286,4fc66943-7c2c-4e0c-a93f-8f7abb752c8c,4fc66943-7c2c-4e0c-a93f-8f7abb752c8c,Animacja
4,Coco,"4fc66943-7c2c-4e0c-a93f-8f7abb752c8c,15c0b1ce-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,118286,15c0b1ce-34ec-4d67-ba14-0138c61d5b54,15c0b1ce-34ec-4d67-ba14-0138c61d5b54,Familijny
...,...,...,...,...,...,...,...
738,Droga Aszera,f0506edd-d123-41d3-ad36-1d31a8bb23b8,"84ba792c-d86a-49a2-96a2-05d3d744cddf,c29315d3-...",200,f0506edd-d123-41d3-ad36-1d31a8bb23b8,f0506edd-d123-41d3-ad36-1d31a8bb23b8,Dramat
739,Droga do Hiszpanii,f0506edd-d123-41d3-ad36-1d31a8bb23b8,e9d4935d-ff76-4487-b6fe-c098e0681f47,668,f0506edd-d123-41d3-ad36-1d31a8bb23b8,f0506edd-d123-41d3-ad36-1d31a8bb23b8,Dramat
740,Droga do zapomnienia,"36a330ff-bd5d-4a0e-b74c-8a0d4473b778,f0506edd-...",7bc66e23-af7a-4d1d-a72b-b745f9c430d4,21598,36a330ff-bd5d-4a0e-b74c-8a0d4473b778,36a330ff-bd5d-4a0e-b74c-8a0d4473b778,Biograficzny
741,Droga do zapomnienia,"36a330ff-bd5d-4a0e-b74c-8a0d4473b778,f0506edd-...",7bc66e23-af7a-4d1d-a72b-b745f9c430d4,21598,f0506edd-d123-41d3-ad36-1d31a8bb23b8,f0506edd-d123-41d3-ad36-1d31a8bb23b8,Dramat
742,DROGA DO RAJU,516495a0-f121-4086-9b59-41a2d17bd118,c29315d3-7743-480d-ba69-783e11af73bf,668,516495a0-f121-4086-9b59-41a2d17bd118,516495a0-f121-4086-9b59-41a2d17bd118,Komedia obycz.

In [20]:
movies.groupby("name").aggregate(
    Srednia_widownia_na_premierze=("boxoffice_viewers_weekend_1", "mean"),
    Liczba_filmow=("movie_title", "nunique"),
).sort_values("Srednia_widownia_na_premierze", ascending=False)

                     Srednia_widownia_na_premierze  Liczba_filmow
name
Erotyczny                            453931.000000              1
Sci-Fi                                88207.093750             32
Baśń                                  78567.000000              1
Dla młodzieży                         72991.000000              1
Komedia obycz.                        69267.750000              4
Melodramat                            67604.000000             13
Familijny                             67452.560000             25
Sensacyjny                            67254.833333              6
Komedia rom.                          66807.833333              6
Akcja                                 61468.392157             51
Wojenny                               59448.000000              5
Świąteczny                            58299.000000              5
Animacja                              57507.029412             34
Przygodowy                            54943.933333             30
Western                               54194.000000              2
Fantasy                               52838.739130             23
Komedia                               45766.279570             93
Obyczajowy                            39609.200000              5
Muzyczny                              39192.083333             12
Szpiegowski                           37218.000000              2
Dramat obyczajowy                     35616.428571              7
Thriller                              35525.959184             49
Polityczny                            33829.600000              5
Biograficzny                          30815.090909             22
Musical                               25458.428571              7
Dramat historyczny                    25321.500000              4
Dla dzieci                            24770.666667              3
Horror                                24166.303030             33
Psychologiczny                        22595.000000              4
Dramat                                18683.949153            177
Kostiumowy                            17987.400000              5
Kryminał                              17698.210526             19
Komedia kryminalna                    15656.857143              7
Poetycki                              12311.000000              1
Sportowy                              11633.000000              6
Fabularyzowany dok.                    9616.000000              2
Romans                                 8778.000000              5
Religijny                              6921.000000              1
Czarna komedia                         4932.666667              3
Dokumentalny                           2356.586207             29
Dokumentalizowany                      1701.000000              1
Surrealistyczny                        1008.000000              1
Historyczny                             334.000000              1

In [22]:
movies[movies["name"] == "Sci-Fi"].sort_values("boxoffice_viewers_weekend_1", ascending=False)

,movie_title,genre_list,countries,boxoffice_viewers_weekend_1,lista_gatunkow,id,name
209,Avengers: Koniec gry,"d34b4e2c-74ce-42ab-b438-86fbbdcaee15,6a5af1f4-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,548204,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
213,Avengers: Wojna bez granic,"d34b4e2c-74ce-42ab-b438-86fbbdcaee15,6a5af1f4-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,271279,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
207,Avengers: Czas Ultrona,"d34b4e2c-74ce-42ab-b438-86fbbdcaee15,6a5af1f4-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,213938,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
619,Deadpool 2,"57366ac3-c349-4e55-ad5d-6f8061179e88,d34b4e2c-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,209194,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
614,Deadpool,"57366ac3-c349-4e55-ad5d-6f8061179e88,d34b4e2c-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,206092,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
324,Blade Runner 2049,"1db1ac18-a83d-4645-9cb7-3c60a03012ba,6a5af1f4-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,127404,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
205,Avengers,"d34b4e2c-74ce-42ab-b438-86fbbdcaee15,6a5af1f4-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,125751,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
263,Batman v Superman: Świt sprawiedliwości,"d34b4e2c-74ce-42ab-b438-86fbbdcaee15,6a5af1f4-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,119237,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
164,Aquaman,"d34b4e2c-74ce-42ab-b438-86fbbdcaee15,6a5af1f4-...","dcbf781d-54a3-4734-9b69-a7e119d59fa5,7bc66e23-...",110174,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
159,Ant-Man i Osa,"d34b4e2c-74ce-42ab-b438-86fbbdcaee15,6a5af1f4-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,102674,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
188,Atlas chmur,"f0506edd-d123-41d3-ad36-1d31a8bb23b8,6a5af1f4-...","dcbf781d-54a3-4734-9b69-a7e119d59fa5,6614b794-...",91890,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
389,Bumblebee,"6a5af1f4-128c-4ca8-960d-3f0f36d29764,d34b4e2c-...","dcbf781d-54a3-4734-9b69-a7e119d59fa5,270542da-...",87216,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
109,Alita: Battle Angel,"d34b4e2c-74ce-42ab-b438-86fbbdcaee15,6a5af1f4-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,56777,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
568,Człowiek ze stali,"d34b4e2c-74ce-42ab-b438-86fbbdcaee15,6a5af1f4-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,55586,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
66,Ad Astra: Ku gwiazdom,"6a5af1f4-128c-4ca8-960d-3f0f36d29764,1db1ac18-...","dcbf781d-54a3-4734-9b69-a7e119d59fa5,244d82ee-...",54351,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
2,Tenet,"1db1ac18-a83d-4645-9cb7-3c60a03012ba,d34b4e2c-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,54070,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
15,1000 lat po Ziemi,"9a150cd3-6c32-4b58-b1a4-aea6992c564c,6a5af1f4-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,49219,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
266,Battleship: Bitwa o Ziemię,6a5af1f4-128c-4ca8-960d-3f0f36d29764,dcbf781d-54a3-4734-9b69-a7e119d59fa5,45518,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
157,Ant-Man,"d34b4e2c-74ce-42ab-b438-86fbbdcaee15,6a5af1f4-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,44358,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
455,Ciche miejsce,"d31939d6-e42e-40f4-8e25-f18e47a1e035,6a5af1f4-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,40636,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
610,Dawca pamięci,"f0506edd-d123-41d3-ad36-1d31a8bb23b8,6a5af1f4-...","dcbf781d-54a3-4734-9b69-a7e119d59fa5,ff8fb8e4-...",35674,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
425,Chappie,"d34b4e2c-74ce-42ab-b438-86fbbdcaee15,6a5af1f4-...","dcbf781d-54a3-4734-9b69-a7e119d59fa5,ff8fb8e4-...",33373,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
331,Bliźniak,"d34b4e2c-74ce-42ab-b438-86fbbdcaee15,6a5af1f4-...","dcbf781d-54a3-4734-9b69-a7e119d59fa5,270542da-...",31576,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
469,Cloverfield Lane 10,"1db1ac18-a83d-4645-9cb7-3c60a03012ba,6a5af1f4-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,22591,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
496,Coś,"d31939d6-e42e-40f4-8e25-f18e47a1e035,6a5af1f4-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,21480,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
412,Captain America: Pierwsze starcie,"d34b4e2c-74ce-42ab-b438-86fbbdcaee15,6a5af1f4-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,20575,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
382,Brightburn: Syn ciemności,"d31939d6-e42e-40f4-8e25-f18e47a1e035,6a5af1f4-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,10000,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
552,Czego dusza zapragnie,"57366ac3-c349-4e55-ad5d-6f8061179e88,6a5af1f4-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,9880,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
566,Człowiek z magicznym pudełkiem,"8ec4b60e-c873-4767-9684-2d4031d99871,6a5af1f4-...",c29315d3-7743-480d-ba69-783e11af73bf,8557,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
734,Dredd,"d34b4e2c-74ce-42ab-b438-86fbbdcaee15,6a5af1f4-...","dcbf781d-54a3-4734-9b69-a7e119d59fa5,203b1bdc-...",8143,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
580,Czwarty stopień,"1db1ac18-a83d-4645-9cb7-3c60a03012ba,6a5af1f4-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,6577,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi
504,CREATIVE CONTROL,"f0506edd-d123-41d3-ad36-1d31a8bb23b8,6a5af1f4-...",dcbf781d-54a3-4734-9b69-a7e119d59fa5,633,6a5af1f4-128c-4ca8-960d-3f0f36d29764,6a5af1f4-128c-4ca8-960d-3f0f36d29764,Sci-Fi

In [ ]:
# w ramach ćwiczenia - zrób to samo z krajami

In [23]:
countries_dict

                                       id               name
0    005c8bc3-d1b3-421b-8b63-3496541f07f7            Romania
1    01442413-d7d6-44fa-8506-d008dc18586a             Canada
2    03aa0c39-3180-4314-80f0-e1abc5482cd9         Luksemburg
3    03ac8e24-c7a5-49d6-a351-4c79ad2ff6d8           Mongolia
4    06bc9384-3540-4d36-be29-80628b947485           Dominika
..                                    ...                ...
252  fa32b133-bf08-4849-9508-b3f8517d3b83           Kiribati
253  fc2f6092-8593-45eb-8877-7684e2ac7ca2  Trynidad i Tobago
254  fd02cb83-450d-4e6a-9d05-8e18b124ea00               Togo
255  fee3c4a6-d925-43ce-8f71-6aadcc8e4449    Wallis i Futuna
256  ff8fb8e4-4f80-44e9-a945-559e886a9a80                RPA

[257 rows x 2 columns]

In [25]:
countries_dict.head(3).to_dict()

{'id': {0: '005c8bc3-d1b3-421b-8b63-3496541f07f7',
  1: '01442413-d7d6-44fa-8506-d008dc18586a',
  2: '03aa0c39-3180-4314-80f0-e1abc5482cd9'},
 'name': {0: 'Romania', 1: 'Canada', 2: 'Luksemburg'}}

In [26]:
countries_dict.head(3).to_dict(orient='records')

[{'id': '005c8bc3-d1b3-421b-8b63-3496541f07f7', 'name': 'Romania'},
 {'id': '01442413-d7d6-44fa-8506-d008dc18586a', 'name': 'Canada'},
 {'id': '03aa0c39-3180-4314-80f0-e1abc5482cd9', 'name': 'Luksemburg'}]

In [ ]:
{
    "005c8bc3-d1b3-421b-8b63-3496541f07f7": "Romania",
    "01442413-d7d6-44fa-8506-d008dc18586a": "Canada",
    "03aa0c39-3180-4314-80f0-e1abc5482cd9": "Luksemburg",
}

{'005c8bc3-d1b3-421b-8b63-3496541f07f7': 'Romania',
 '01442413-d7d6-44fa-8506-d008dc18586a': 'Canada',
 '03aa0c39-3180-4314-80f0-e1abc5482cd9': 'Luksemburg'}

In [32]:
lista_rekordow = countries_dict.to_dict(orient="records")

slownik = {}
for rekord in lista_rekordow:
    slownik[rekord['id']] = rekord['name']

slownik

{'005c8bc3-d1b3-421b-8b63-3496541f07f7': 'Romania',
 '01442413-d7d6-44fa-8506-d008dc18586a': 'Canada',
 '03aa0c39-3180-4314-80f0-e1abc5482cd9': 'Luksemburg',
 '03ac8e24-c7a5-49d6-a351-4c79ad2ff6d8': 'Mongolia',
 '06bc9384-3540-4d36-be29-80628b947485': 'Dominika',
 '09d4a448-e2b9-4400-9f5e-730f5eb483c2': 'Maroko',
 '09ee0bb5-32b6-4a05-b22f-922fc9c4a775': 'Birma',
 '0b5c4bd5-8e4a-4e70-84aa-9963210f56cc': 'Kostaryka',
 '0dfd9ee5-c937-47ca-8b0c-a63da5e461c7': 'country:GB',
 '0e4c434d-a0fc-417c-b0b7-f5f0393c9707': 'Wyspy Cooka',
 '0e532683-6733-4a28-ba59-48d7c577169f': 'Turcja',
 '0ecdf301-1720-44fe-acb1-1034062b206c': 'Grenlandia',
 '0f8b70df-acbb-4546-91a2-7d65f6d6e864': 'Falklandy (Malwiny)',
 '0fbc1250-ac0f-4692-b23c-5fa4b57a36ca': 'Gabon',
 '0ff763a8-5b91-4332-9c84-4abfae38010a': 'Mołdawia',
 '102930e9-1572-41e4-b64c-cd6bdd3abde7': 'Rwanda',
 '11325065-dbd4-4cfe-88f8-ad84f3bf170a': 'Vanuatu',
 '116f84ab-f821-42b3-a646-dc8a2444256f': 'Macedonia Północna',
 '117e26fd-260a-442c-ad67-d816303d381b': 'Kosowo ',
 '12d4f915-596e-4891-9837-cf74700bacae': 'Antigua i Barbuda',
 '13d98885-a89e-477c-b886-488db50ecf4d': 'Colombia',
 '1438a174-032b-4e1e-8c6d-fa82543b3120': 'Grecja',
 '14e8baa4-6b6d-46bd-8980-6e3f95145a3f': 'Russia',
 '157ed641-9866-4610-af29-a2db653d0500': 'Sahara Zachodnia',
 '18552243-587b-4937-8fb3-c3494a6c5975': 'Gwinea Równikowa',
 '193d0ce4-810d-4885-8e58-10000ba1bf49': 'Chiny - Specjalny Region Administracyjny Hongkong',
 '19eafdf3-8512-4de7-9bd5-e5bf1c9addd2': 'Pakistan',
 '1b7463ea-f722-4147-a4b2-261b08bede20': 'Dania',
 '1bc091c2-c204-41f4-8cfb-6a0b1095459a': 'Seszele',
 '1bcfcd86-d925-4c61-89ce-00b38e268d7d': 'Nowa Zelandia',
 '1c238b6f-2736-4c83-b143-ad777ba7b90e': 'Martynika',
 '1c8db7e6-8ab8-4d0e-b0c2-8da00e172b48': 'Slovakia',
 '1da1cbf1-ba09-4f22-9671-935eab127b62': 'Bhutan',
 '1e32f160-e4ca-4cbd-b65f-69c14e2646f3': 'Nowa Kaledonia',
 '1f9b39aa-54d5-443b-8190-2a93766a4c75': 'San Marino',
 '203b1bdc-e7e1-4cb8-a3aa-d40b824fb902': 'Indie',
 '22012dd5-4f96-44f4-bdb7-48bc02c5e8d3': 'Katar',
 '23b75bad-d0d2-4cb7-8435-32f38257fced': 'Kuba',
 '244d82ee-fac6-439f-b523-145e08dfcfec': 'Brazylia',
 '24fe046b-8fc6-4b83-beb0-559d15bebb76': 'Malezja',
 '253ac9c1-62d4-477c-8fbd-cc6c6ed740a9': 'South Africa',
 '270542da-ad6a-4404-8f03-01fd73a4c545': 'Chiny',
 '27b80f24-40f7-4bef-bf53-f8bee93de1b7': 'Monako',
 '29703937-d521-4129-93b4-4c7045b2d609': 'Lesotho',
 '29ad26a7-da1a-4155-90c0-8a17fab6bcf4': 'Belgium',
 '29af9bec-212c-4878-bf62-ad1337ce64b7': 'Demokratyczna Republika Konga',
 '29fbb99b-fff3-4721-a1dc-ac77e657fd03': 'Uganda',
 '2a2c985b-6b04-476d-aedf-66462b2ed5bc': 'Ghana',
 '2ade11cc-452a-4f58-a53c-d4cd1f16e462': 'country:FR',
 '2bfa0f18-878f-4bdb-9ccc-f65bc2e7be58': 'Bahamy',
 '2cb2e969-34f1-43aa-8ae7-721d9570647f': 'Libia',
 '2db65204-28f6-45f1-b92b-ad2bd7374953': 'Tajwan',
 '2fc5f499-63db-46db-81cc-799185445a66': 'Thailand',
 '302800cc-896a-4ebf-b475-548ae7df8174': 'Polinezja Francuska',
 '316db17e-853a-48ca-a5f1-cab7af38c938': 'Nigeria',
 '32bd38d4-6afa-4ddc-a5cf-5ee04ee0fea1': 'Wyspy Kokosowe',
 '333fca31-3273-4f98-86d5-f56230419e6d': 'Mauretania',
 '35c5b59b-76d5-40ac-b685-928ade8f184d': 'Netherlands',
 '36146266-9a1a-4aaa-90bf-6dfcd641a141': 'Burundi',
 '362f356e-5cf0-47b0-86cb-14f473e93d42': 'Gujana Francuska',
 '36a6ae4d-cf21-416d-a92a-ef425cbe7723': 'Nauru',
 '37383b62-2270-4027-9c73-79336ca8a1ac': 'Saint Kitts i Nevis',
 '380f767c-1de0-4266-809f-666a5f2e3c47': 'Hongkong',
 '383df329-1525-47ab-b77c-104b1bf50c0a': 'Saint-Pierre i Miquelon',
 '3931af46-4861-495d-8f0d-0fba777012f9': 'Armenia',
 '399f5393-dc15-4ade-8fc4-c65d9782ae3a': 'Bośnia i Hercegowina',
 '39a3e84d-85ed-4421-90e5-26722b3bc1d8': 'Surinam',
 '3c883887-f7b3-46e6-a8ec-fc78b2457668': 'Wyspa Świętej Heleny',
 '3cf612e1-163d-4754-92ac-1ad4afeaa1cf': 'Belarus',
 '3cfca45b-4727-4d23-aa33-bc552bda2865': 'Palau',
 '3d0b542e-f42c-4302-9245-c8e06fb98491': 'Albania',
 '3d0d057f-10c2-4817-b170-c4c09fb100d8': 'Kuwejt',
 '3d3ee462-73f9-4ffe-ae28-36bf4e30ae00': 'Czechosłowacja',
 '3d402adc-9bbb-4456-91da-8d74dc0c3172': 'Zjednoczone Emiraty Arabskie',
 '3e9c11f8-6c9c-43d5-ab20-085c6eba18e6': 'Boliwia',
 '3ec394f9-c247-4179-a1fe-185c3e57bb50': 'Finlandia',
 '3ec8ec74-e509-4399-8b73-a85864cbed80': 'Mariany Północne',
 '3f2a0fff-aeb0-483e-b82c-4f1f78bbf246': 'ZSRR',
 '40b32eec-a75c-4549-b8b7-0d3b90e2ef32': 'Węgry',
 '4139e44f-4971-4cec-ac9a-de42204f4d90': 'Sierra Leone',
 '41955800-72c7-4723-a195-6212f4b214b4': 'Tanzania',
 '42c78f2a-95ee-4a5d-995a-5b06aa65749e': 'Timor Wschodni',
 '442249ad-7065-42f8-96d5-e67b19ca63ff': 'Gwadelupa',
 '44355211-404b-492c-9216-0a64bf93b6be': 'South Korea',
 '44a6a152-8907-4952-a41c-92e6b6d991b7': 'Argentina',
 '44e3c5e9-4308-49b2-9789-d4d3850bd7be': 'Azerbejdżan',
 '45cf06c8-eb6b-429f-ba4c-0e7c8f6346b4': 'Eswatini (Suasi)',
 '45ffa582-b37c-4ddb-be04-dac8f1fb4d8d': 'Burkina Faso',
 '472ae5cd-4114-4f4b-9344-aad49b230d1c': 'Kambodża',
 '47f223cb-6d02-4bb2-963f-99db76dc80bf': 'Czarnogóra',
 '483e9511-5ef6-4080-98f1-2f77afd73cde': 'Jordania',
 '4877f16f-9889-4695-8351-a69c90e39166': 'Madagaskar',
 '4935e757-fc7d-4e6a-a793-b7d305898de2': 'Dominikana',
 '4a24d17f-9f9b-4fe9-a697-7a9ff4b0c9b3': 'Francuskie Terytoria Południowe',
 '4b976e59-1523-4b82-9b93-7313ad86cb95': 'Sark',
 '4cf9e21d-30fd-4a17-b654-adeaa1c23d41': 'country:BE',
 '4d675aec-8421-4889-9313-3f50708a95d0': 'Ekwador',
 '4de0e08f-d74e-46fa-bf2a-5f15e6054683': 'Nikaragua',
 '4f43548f-8dfa-4a2e-9ddb-51dcb48a02ef': 'Bangladesz',
 '4fb67e3b-9a46-4126-a3e7-61543696aaba': 'country:IT',
 '5038de85-8767-43ed-b933-a1ebb6251ec0': 'Guernsey',
 '50a054db-53b0-46af-ab20-122b7fa54a2d': 'Tunezja',
 '513a05b1-966c-4524-a429-10227b94afb4': 'Wyspy Aland',
 '516ff332-4635-4738-bdb3-89f91b9425be': 'Gwinea Bissau',
 '51ca2b27-4b06-4a97-9c65-b0ad76c8f6ab': 'Montserrat',
 '51d9043b-068a-4a31-a0fb-74719a5a6a11': 'Francja',
 '5657e6de-685a-4531-b3e2-56089d86f877': 'Republika Środkowoafrykańska',
 '5674f9c6-b66d-40c9-8527-817c5cabc554': 'Chorwacja',
 '56ce5915-202c-4c2c-ab71-776bfc955c8a': 'Bahrajn',
 '56f2414a-f947-4700-b2ed-c7e98b4c1c1c': 'Jamajka',
 '578e3881-0b2b-4969-8059-b9afd082697a': 'Gwatemala',
 '58174cd1-1e90-48ff-9b20-573d03f4a30e': 'Egipt',
 '583dc0fc-df37-4bfd-a3cb-8adcd09a328e': 'Afganistan',
 '5864f521-7e23-4d39-bdd9-5f6a80ff7ec0': 'Paragwaj',
 '5959fb3b-bf03-42a5-9716-cd42cf60080b': 'Wyspa Bożego Narodzenia',
 '5aaf37a7-55da-4120-99b5-40ebae2a5f7a': 'Chiny - Specjalny Region Administracyjny Makau',
 '5b3a745b-8dfc-42ad-b00d-d76bb817e516': 'Salwador',
 '5b661046-6f4e-4e56-820b-da1c7b750694': 'Gibraltar',
 '5be1722f-93d8-4b79-8945-0d91bf9f8f5e': 'Bermudy',
 '5cdb0ae8-0a45-461b-9817-ca92c22cb528': 'UK',
 '5ea18f43-25ac-4e47-b791-86d0c9a5e851': 'Ireland',
 '5ea42f33-65d0-46c7-9e27-dc96b049c3d1': 'Arabia Saudyjska',
 '62745829-c5ba-493a-aa4f-efad0e0fb37f': 'Wyspy Świętego Tomasza i Książęca',
 '62e9b188-1cac-499d-9092-6f070fa5ff0e': 'Singapore',
 '630348e2-5006-473e-8b91-af19b1225b96': 'Komory',
 '64f712c0-e427-4917-bf9b-d7d21f9f0653': 'Mali',
 '654011b0-4c4d-4eea-9eb3-749a4a438219': 'Islandia',
 '6584b7a0-1dd5-4aed-aa58-1f5df0c2a11a': 'Italy',
 '6614b794-9b07-4de2-837e-3aba6098ec7a': 'Niemcy',
 '67a0030a-e22f-4bdb-9e6a-c60d96fa808d': 'Nepal',
 '6b1c3c8b-fcbd-4f9a-8d8f-0e0e6d305a00': 'Czad',
 '6d10b186-3daf-452e-b48e-382e70b7f609': 'Botswana',
 '6da4f240-7fd9-4934-9689-f93f51cac24c': 'Litwa',
 '6dff9e42-9110-41c1-a2d1-c68e919c36c7': 'Norway',
 '6e01e9e6-bf10-4828-87d5-b1c98aae8e0d': 'Honduras',
 '6ec0db81-6558-43bf-9142-36d2e8bc321a': 'Haiti',
 '6f962b42-d29f-499c-87f6-e9546b8a0c92': 'Sri Lanka',
 '703ab25a-ab01-42a0-b7cd-c8f059b2e145': 'Gruzja',
 '70acdacb-a99d-48ce-9058-9948f29699dd': 'Korea Północna',
 '718f27b3-47ba-4c30-af01-febc9d241bcf': 'Portoryko',
 '724dbf07-a5e6-48be-bb56-f3dcdfc600e0': 'Kajmany',
 '726840c0-4fc5-4c7b-9900-9e995028994f': 'Reunion',
 '746be90c-2ad0-4a9c-9c61-c818e65f9024': 'Somalia',
 '758b8e9d-e8be-49c3-9d6f-4666bc75b7af': 'Macedonia',
 '75f50632-81a8-431c-b826-976e77573b08': 'Republika Zielonego Przylądka',
 '7759f57c-1e62-40ac-8c02-2b86242df436': 'Mauritius',
 '79825b0c-4532-4759-af83-e29465fb1898': 'Brunei',
 '79c15d47-cf6e-41a3-9c33-b9319ebfbabc': 'Kongo',
 '7abbf9c0-2b4b-4c46-b0c3-56cc2a943538': 'Wyspy Marshalla',
 '7bc66e23-af7a-4d1d-a72b-b745f9c430d4': 'Australia',
 '7c3c6900-cff1-44d1-8e05-b71f752b95d4': 'Meksyk',
 '7d224f92-a3ab-4dff-a2e6-392e1033eb87': 'Mozambik',
 '7fee7fcb-3792-4301-850c-6d9c12cb989d': 'Oman',
 '81fd52e2-f22a-4e27-83d9-6b45cc2d2946': 'Bulgaria',
 '82212d8f-c0dc-4ce2-874a-3fd1a9c41e67': 'Watykan',
 '8305b894-02ab-4edf-8b8d-80bc65300fe3': 'Urugwaj',
 '84ba792c-d86a-49a2-96a2-05d3d744cddf': 'Izrael',
 '85804edf-8e3a-4db7-b35e-4026ffcc0cc1': 'Kirgistan',
 '8594ada5-a15a-42f7-b242-9d8067c81307': 'country:NL',
 '86ada895-cdea-4fbd-bf7e-ade7848bcc4e': 'Filipiny',
 '887ff35e-edb0-4ba5-96c5-6bcc8efd43ad': 'Switzerland',
 '88cba7f0-879a-44af-9a25-4e086d43cff6': 'Grenada',
 '88fb57a1-0c75-40c0-99f1-eba2b10235d1': 'Guam',
 '8af68d9e-6fc5-4f86-876d-29962367a362': 'Wyspy Salomona',
 '8c94c5da-b5fb-4b55-8b3f-66195402bede': 'Zimbabwe',
 '8e3301c8-7bec-4040-a5bb-f2cc0830b3c5': 'Angola',
 '901ce5bd-d531-407d-b439-202b90afc0e3': 'Namibia',
 '907a5b8f-ce95-40f3-9e4e-99dca620ab6f': 'Ucraine',
 '910b960c-5760-44e3-9894-7eaeb2503bd6': 'Wyspa Norfolk',
 '91ea2629-5665-4f36-8d24-5c8b444d514f': 'Anguilla',
 '9259e39c-1399-4adb-a1f9-3c7bb6bbbc9d': 'Syria',
 '95291def-51d0-4704-a51c-4a14477497ad': 'Tokelau',
 '95e8fb98-c2da-4b45-95a1-a1d1f22e3383': 'Bonaire',
 '980d99fe-ea69-4e06-b546-86078e86edd9': 'Dżibuti',
 '98371c36-0ae0-4161-98ac-d884bed55489': 'Majotta',
 '985604a2-6dfe-42b2-b4d4-4150ac635121': 'Wyspy Dziewicze Stanów Zjednoczonych',
 '9a8cfad4-962b-40cb-834b-11271b325868': 'Sweden',
 '9c775095-e249-4677-bdd7-b28c9697be50': 'Japan',
 '9d7e7f13-f52d-4f4c-bf17-944976f017b6': 'Turkmenistan',
 '9f65dccd-5de2-44aa-a068-73eee026bf62': 'Barbados',
 'a280a38e-53e2-49ad-b2cc-35e2fbe106ea': 'country:US',
 'a3ab0727-6b63-4d7f-81ee-54448d52a536': 'Samoa Amerykańskie',
 'a56f0cb9-6307-4a15-b901-24c6354fc82c': 'Mikronezja',
 'a5c39b09-2f76-49b3-8159-c2b7f5cdd0b9': 'Czech Republic',
 'a6abd7b4-afa0-4653-a5b4-0f83e8c01ee6': 'Indonezja',
 'aa074dfa-b908-4b56-b6b7-230fe2fffeab': 'Łotwa',
 'ad60629b-6a56-462d-9c7b-3e68fd12b5ac': 'Estonia',
 'af6296bf-ba2b-4acc-ab07-0e2c7f2f6449': 'Fidżi',
 'af755660-861f-4f10-83f5-07128d3f7773': 'Wietnam',
 'af7cdff1-5323-4581-a06e-14a9b289d4ac': 'Ukraina',
 'afdf67ae-b1a1-445d-a7e8-0841fedf04b0': 'Papua-Nowa Gwinea',
 'b0233cad-fd3d-4140-b00b-28a045525410': 'Iran',
 'b078fcdf-5ab4-4abc-8d1d-569e944eca61': 'Spain',
 'b1608a60-0782-4a2d-843e-07352a77a5b7': 'Wyspy Owcze',
 'b2d9b207-a611-40de-b5ef-18580b3513d4': 'Laos',
 'b3719280-9f56-4d4f-8beb-cc34244c8d1f': 'Niger',
 'b3940a50-94c3-4418-9c75-cc9cd54fe854': 'Tadżykistan',
 'b3e7a9b7-f6ee-4e5c-9172-dbf9a3315fc6': 'Wyspa Man',
 'b757fdd3-7139-4e76-8309-164ce2bca39f': 'Erytrea',
 'b76e108b-e153-44ef-a65f-b9f3dd8aec53': 'Mjanma (Birma)',
 'bb4079c8-93a7-43bf-bcc1-f4bda2c0e8d0': 'Benin',
 'bca6412b-c525-4596-bfdb-c9f3251ce9e4': 'Cypr',
 'bd0ad58f-73fd-488e-974c-e82f21122cdb': 'Gambia',
 'be8e67e2-fea4-49a8-b3b9-4984c54856b9': 'Svalbard i Jan Mayen',
 'c19644c3-3236-4d0b-8027-f90bb4e2f806': 'Liberia',
 'c1c54103-80d2-46b8-9f48-16c95abe7bda': 'Andora',
 'c29315d3-7743-480d-ba69-783e11af73bf': 'Polska',
 'c29dd754-c598-487c-8ad8-0c373de535fa': 'Algieria',
 'c66b1c33-cccb-4245-9626-9392785af5a7': 'Gujana',
 'c6701151-aad3-47b8-bd71-0ac583fee4c7': 'country:DE',
 'c6a7670c-2141-42d1-9ee4-7483f56d418d': 'Niue',
 'c7f19d4b-851b-442d-8048-a7bcab2de895': 'Etiopia',
 'c8dfffd6-8499-489f-9285-9828ba14c802': 'Chile',
 'cafc43fa-275d-480e-b7f1-b998f2faebb5': 'Irak',
 'cb480387-3952-4039-befe-e2de6283f974': 'Malawi',
 'cc0ac9b5-2547-4e64-8ecf-8cb7f3ba878e': 'Malta',
 'cc787b20-1861-4f6a-8c09-645872c70da4': 'Kazachstan',
 'cd9b4e79-1455-454b-a950-ae242e610ffa': 'Liban',
 'cdb094e4-744e-4e16-86d4-cc01f243975b': 'Belize',
 'ce5e2109-9ae4-4462-8bd9-408e84f613c8': 'Brytyjskie Wyspy Dziewicze',
 'd1348208-9d84-49f2-b567-491545a5f22b': 'Uzbekistan',
 'd214ddf7-23df-4184-9c27-c27f3dae4229': 'country:HU',
 'd46507f2-a93b-4c65-bd39-8fb303b46cb1': 'Senegal',
 'd485df53-13ad-41bb-b48f-dd449a6b462d': 'Wenezuela',
 'd6258fc0-deb9-485a-864c-1782022d4fe2': 'Pitcairn',
 'd6d221c6-8669-4947-b2f7-60f211214380': 'Słowenia',
 'd71dc674-ccae-45b2-bba8-93c9f80acdc4': 'Tuvalu',
 'd88fe104-cdb4-4a3a-88c0-d133641a9052': 'Tonga',
 'd9351110-ed5b-4140-8d62-f88b2860c913': 'Peru',
 'd97f3191-6ab8-4327-916c-9f8a83d9696e': 'Zambia',
 'd9c6deaf-b31d-4092-8040-8b3b58f3d907': 'Brytyjskie Terytorium Oceanu Indyjskiego',
 'da28d548-d069-45e2-8234-5b1203a8056d': 'Liechtenstein',
 'dcbf781d-54a3-4734-9b69-a7e119d59fa5': 'Stany Zjednoczone',
 'e13ac228-178e-4d96-8ac8-37eae82e20d9': 'Saint Lucia',
 'e4daf024-a9f5-45db-9f32-327f9b7cbc2c': 'Kenia',
 'e7e435ef-9713-46fe-9814-40423c54165f': 'Palestyna',
 'e8d92c28-bd89-42b4-8977-553eaa2731f1': 'Turks i Caicos',
 'e9d4935d-ff76-4487-b6fe-c098e0681f47': 'Austria',
 'ec2176f2-7f11-4c01-abf0-76c940f4f6df': 'Panama',
 'ed62df6a-7c87-446a-bfe4-0aa55ad3d120': 'Jersey',
 'eee80e4c-8c23-485b-a66e-144e6dea129d': 'Serbia',
 'ef2169a0-95d7-407b-b47c-c3b15a4acf60': 'Samoa',
 'efb37ea3-6c83-48b9-b0ab-d683bb50f639': 'Wybrzeże Kości Słoniowej',
 'f1e5dc13-9b23-489b-a415-997a5b5efa9b': 'Gwinea',
 'f28c4596-92d1-4aef-b3e9-95fbd4c574c9': 'Kamerun',
 'f4554f4a-1794-491a-9d36-15dd531c2570': 'country:JP',
 'f50791cc-a488-4444-95c3-cfd986f20ee4': 'Saint Vincent i Grenadyny',
 'f6d23a2d-3a98-42e9-8dae-29ce47c9e05b': 'Malediwy',
 'f7e593d9-f9ed-40de-a7b2-b9a31cbeadde': 'Sudan',
 'f89a6abb-7c4b-4907-9af1-3d122a08491c': 'RFN',
 'f8f0c64f-e1b8-4790-8c39-219b7c915b41': 'Portugalia',
 'f91d860f-749e-4c50-9f47-2ad15c03b181': 'Jemen',
 'fa32b133-bf08-4849-9508-b3f8517d3b83': 'Kiribati',
 'fc2f6092-8593-45eb-8877-7684e2ac7ca2': 'Trynidad i Tobago',
 'fd02cb83-450d-4e6a-9d05-8e18b124ea00': 'Togo',
 'fee3c4a6-d925-43ce-8f71-6aadcc8e4449': 'Wallis i Futuna',
 'ff8fb8e4-4f80-44e9-a945-559e886a9a80': 'RPA'}

In [33]:
movies['countries'].map(slownik)

0      Stany Zjednoczone
1      Stany Zjednoczone
2      Stany Zjednoczone
3      Stany Zjednoczone
4      Stany Zjednoczone
             ...
738                  NaN
739              Austria
740            Australia
741            Australia
742               Polska
Name: countries, Length: 743, dtype: str

In [34]:
movies.iloc[738, :]

movie_title                                                         Droga Aszera
genre_list                                  f0506edd-d123-41d3-ad36-1d31a8bb23b8
countries                      84ba792c-d86a-49a2-96a2-05d3d744cddf,c29315d3-...
boxoffice_viewers_weekend_1                                                  200
lista_gatunkow                              f0506edd-d123-41d3-ad36-1d31a8bb23b8
id                                          f0506edd-d123-41d3-ad36-1d31a8bb23b8
name                                                                      Dramat
Name: 738, dtype: object

In [ ]:
# dict-comprehention z data frame
slownik = {r["id"]: r["name"] for r in countries_dict.to_dict(orient="records")}
slownik

{'005c8bc3-d1b3-421b-8b63-3496541f07f7': 'Romania',
 '01442413-d7d6-44fa-8506-d008dc18586a': 'Canada',
 '03aa0c39-3180-4314-80f0-e1abc5482cd9': 'Luksemburg',
 '03ac8e24-c7a5-49d6-a351-4c79ad2ff6d8': 'Mongolia',
 '06bc9384-3540-4d36-be29-80628b947485': 'Dominika',
 '09d4a448-e2b9-4400-9f5e-730f5eb483c2': 'Maroko',
 '09ee0bb5-32b6-4a05-b22f-922fc9c4a775': 'Birma',
 '0b5c4bd5-8e4a-4e70-84aa-9963210f56cc': 'Kostaryka',
 '0dfd9ee5-c937-47ca-8b0c-a63da5e461c7': 'country:GB',
 '0e4c434d-a0fc-417c-b0b7-f5f0393c9707': 'Wyspy Cooka',
 '0e532683-6733-4a28-ba59-48d7c577169f': 'Turcja',
 '0ecdf301-1720-44fe-acb1-1034062b206c': 'Grenlandia',
 '0f8b70df-acbb-4546-91a2-7d65f6d6e864': 'Falklandy (Malwiny)',
 '0fbc1250-ac0f-4692-b23c-5fa4b57a36ca': 'Gabon',
 '0ff763a8-5b91-4332-9c84-4abfae38010a': 'Mołdawia',
 '102930e9-1572-41e4-b64c-cd6bdd3abde7': 'Rwanda',
 '11325065-dbd4-4cfe-88f8-ad84f3bf170a': 'Vanuatu',
 '116f84ab-f821-42b3-a646-dc8a2444256f': 'Macedonia Północna',
 '117e26fd-260a-442c-ad67-d816303d381b': 'Kosowo ',
 '12d4f915-596e-4891-9837-cf74700bacae': 'Antigua i Barbuda',
 '13d98885-a89e-477c-b886-488db50ecf4d': 'Colombia',
 '1438a174-032b-4e1e-8c6d-fa82543b3120': 'Grecja',
 '14e8baa4-6b6d-46bd-8980-6e3f95145a3f': 'Russia',
 '157ed641-9866-4610-af29-a2db653d0500': 'Sahara Zachodnia',
 '18552243-587b-4937-8fb3-c3494a6c5975': 'Gwinea Równikowa',
 '193d0ce4-810d-4885-8e58-10000ba1bf49': 'Chiny - Specjalny Region Administracyjny Hongkong',
 '19eafdf3-8512-4de7-9bd5-e5bf1c9addd2': 'Pakistan',
 '1b7463ea-f722-4147-a4b2-261b08bede20': 'Dania',
 '1bc091c2-c204-41f4-8cfb-6a0b1095459a': 'Seszele',
 '1bcfcd86-d925-4c61-89ce-00b38e268d7d': 'Nowa Zelandia',
 '1c238b6f-2736-4c83-b143-ad777ba7b90e': 'Martynika',
 '1c8db7e6-8ab8-4d0e-b0c2-8da00e172b48': 'Slovakia',
 '1da1cbf1-ba09-4f22-9671-935eab127b62': 'Bhutan',
 '1e32f160-e4ca-4cbd-b65f-69c14e2646f3': 'Nowa Kaledonia',
 '1f9b39aa-54d5-443b-8190-2a93766a4c75': 'San Marino',
 '203b1bdc-e7e1-4cb8-a3aa-d40b824fb902': 'Indie',
 '22012dd5-4f96-44f4-bdb7-48bc02c5e8d3': 'Katar',
 '23b75bad-d0d2-4cb7-8435-32f38257fced': 'Kuba',
 '244d82ee-fac6-439f-b523-145e08dfcfec': 'Brazylia',
 '24fe046b-8fc6-4b83-beb0-559d15bebb76': 'Malezja',
 '253ac9c1-62d4-477c-8fbd-cc6c6ed740a9': 'South Africa',
 '270542da-ad6a-4404-8f03-01fd73a4c545': 'Chiny',
 '27b80f24-40f7-4bef-bf53-f8bee93de1b7': 'Monako',
 '29703937-d521-4129-93b4-4c7045b2d609': 'Lesotho',
 '29ad26a7-da1a-4155-90c0-8a17fab6bcf4': 'Belgium',
 '29af9bec-212c-4878-bf62-ad1337ce64b7': 'Demokratyczna Republika Konga',
 '29fbb99b-fff3-4721-a1dc-ac77e657fd03': 'Uganda',
 '2a2c985b-6b04-476d-aedf-66462b2ed5bc': 'Ghana',
 '2ade11cc-452a-4f58-a53c-d4cd1f16e462': 'country:FR',
 '2bfa0f18-878f-4bdb-9ccc-f65bc2e7be58': 'Bahamy',
 '2cb2e969-34f1-43aa-8ae7-721d9570647f': 'Libia',
 '2db65204-28f6-45f1-b92b-ad2bd7374953': 'Tajwan',
 '2fc5f499-63db-46db-81cc-799185445a66': 'Thailand',
 '302800cc-896a-4ebf-b475-548ae7df8174': 'Polinezja Francuska',
 '316db17e-853a-48ca-a5f1-cab7af38c938': 'Nigeria',
 '32bd38d4-6afa-4ddc-a5cf-5ee04ee0fea1': 'Wyspy Kokosowe',
 '333fca31-3273-4f98-86d5-f56230419e6d': 'Mauretania',
 '35c5b59b-76d5-40ac-b685-928ade8f184d': 'Netherlands',
 '36146266-9a1a-4aaa-90bf-6dfcd641a141': 'Burundi',
 '362f356e-5cf0-47b0-86cb-14f473e93d42': 'Gujana Francuska',
 '36a6ae4d-cf21-416d-a92a-ef425cbe7723': 'Nauru',
 '37383b62-2270-4027-9c73-79336ca8a1ac': 'Saint Kitts i Nevis',
 '380f767c-1de0-4266-809f-666a5f2e3c47': 'Hongkong',
 '383df329-1525-47ab-b77c-104b1bf50c0a': 'Saint-Pierre i Miquelon',
 '3931af46-4861-495d-8f0d-0fba777012f9': 'Armenia',
 '399f5393-dc15-4ade-8fc4-c65d9782ae3a': 'Bośnia i Hercegowina',
 '39a3e84d-85ed-4421-90e5-26722b3bc1d8': 'Surinam',
 '3c883887-f7b3-46e6-a8ec-fc78b2457668': 'Wyspa Świętej Heleny',
 '3cf612e1-163d-4754-92ac-1ad4afeaa1cf': 'Belarus',
 '3cfca45b-4727-4d23-aa33-bc552bda2865': 'Palau',
 '3d0b542e-f42c-4302-9245-c8e06fb98491': 'Albania',
 '3d0d057f-10c2-4817-b170-c4c09fb100d8': 'Kuwejt',
 '3d3ee462-73f9-4ffe-ae28-36bf4e30ae00': 'Czechosłowacja',
 '3d402adc-9bbb-4456-91da-8d74dc0c3172': 'Zjednoczone Emiraty Arabskie',
 '3e9c11f8-6c9c-43d5-ab20-085c6eba18e6': 'Boliwia',
 '3ec394f9-c247-4179-a1fe-185c3e57bb50': 'Finlandia',
 '3ec8ec74-e509-4399-8b73-a85864cbed80': 'Mariany Północne',
 '3f2a0fff-aeb0-483e-b82c-4f1f78bbf246': 'ZSRR',
 '40b32eec-a75c-4549-b8b7-0d3b90e2ef32': 'Węgry',
 '4139e44f-4971-4cec-ac9a-de42204f4d90': 'Sierra Leone',
 '41955800-72c7-4723-a195-6212f4b214b4': 'Tanzania',
 '42c78f2a-95ee-4a5d-995a-5b06aa65749e': 'Timor Wschodni',
 '442249ad-7065-42f8-96d5-e67b19ca63ff': 'Gwadelupa',
 '44355211-404b-492c-9216-0a64bf93b6be': 'South Korea',
 '44a6a152-8907-4952-a41c-92e6b6d991b7': 'Argentina',
 '44e3c5e9-4308-49b2-9789-d4d3850bd7be': 'Azerbejdżan',
 '45cf06c8-eb6b-429f-ba4c-0e7c8f6346b4': 'Eswatini (Suasi)',
 '45ffa582-b37c-4ddb-be04-dac8f1fb4d8d': 'Burkina Faso',
 '472ae5cd-4114-4f4b-9344-aad49b230d1c': 'Kambodża',
 '47f223cb-6d02-4bb2-963f-99db76dc80bf': 'Czarnogóra',
 '483e9511-5ef6-4080-98f1-2f77afd73cde': 'Jordania',
 '4877f16f-9889-4695-8351-a69c90e39166': 'Madagaskar',
 '4935e757-fc7d-4e6a-a793-b7d305898de2': 'Dominikana',
 '4a24d17f-9f9b-4fe9-a697-7a9ff4b0c9b3': 'Francuskie Terytoria Południowe',
 '4b976e59-1523-4b82-9b93-7313ad86cb95': 'Sark',
 '4cf9e21d-30fd-4a17-b654-adeaa1c23d41': 'country:BE',
 '4d675aec-8421-4889-9313-3f50708a95d0': 'Ekwador',
 '4de0e08f-d74e-46fa-bf2a-5f15e6054683': 'Nikaragua',
 '4f43548f-8dfa-4a2e-9ddb-51dcb48a02ef': 'Bangladesz',
 '4fb67e3b-9a46-4126-a3e7-61543696aaba': 'country:IT',
 '5038de85-8767-43ed-b933-a1ebb6251ec0': 'Guernsey',
 '50a054db-53b0-46af-ab20-122b7fa54a2d': 'Tunezja',
 '513a05b1-966c-4524-a429-10227b94afb4': 'Wyspy Aland',
 '516ff332-4635-4738-bdb3-89f91b9425be': 'Gwinea Bissau',
 '51ca2b27-4b06-4a97-9c65-b0ad76c8f6ab': 'Montserrat',
 '51d9043b-068a-4a31-a0fb-74719a5a6a11': 'Francja',
 '5657e6de-685a-4531-b3e2-56089d86f877': 'Republika Środkowoafrykańska',
 '5674f9c6-b66d-40c9-8527-817c5cabc554': 'Chorwacja',
 '56ce5915-202c-4c2c-ab71-776bfc955c8a': 'Bahrajn',
 '56f2414a-f947-4700-b2ed-c7e98b4c1c1c': 'Jamajka',
 '578e3881-0b2b-4969-8059-b9afd082697a': 'Gwatemala',
 '58174cd1-1e90-48ff-9b20-573d03f4a30e': 'Egipt',
 '583dc0fc-df37-4bfd-a3cb-8adcd09a328e': 'Afganistan',
 '5864f521-7e23-4d39-bdd9-5f6a80ff7ec0': 'Paragwaj',
 '5959fb3b-bf03-42a5-9716-cd42cf60080b': 'Wyspa Bożego Narodzenia',
 '5aaf37a7-55da-4120-99b5-40ebae2a5f7a': 'Chiny - Specjalny Region Administracyjny Makau',
 '5b3a745b-8dfc-42ad-b00d-d76bb817e516': 'Salwador',
 '5b661046-6f4e-4e56-820b-da1c7b750694': 'Gibraltar',
 '5be1722f-93d8-4b79-8945-0d91bf9f8f5e': 'Bermudy',
 '5cdb0ae8-0a45-461b-9817-ca92c22cb528': 'UK',
 '5ea18f43-25ac-4e47-b791-86d0c9a5e851': 'Ireland',
 '5ea42f33-65d0-46c7-9e27-dc96b049c3d1': 'Arabia Saudyjska',
 '62745829-c5ba-493a-aa4f-efad0e0fb37f': 'Wyspy Świętego Tomasza i Książęca',
 '62e9b188-1cac-499d-9092-6f070fa5ff0e': 'Singapore',
 '630348e2-5006-473e-8b91-af19b1225b96': 'Komory',
 '64f712c0-e427-4917-bf9b-d7d21f9f0653': 'Mali',
 '654011b0-4c4d-4eea-9eb3-749a4a438219': 'Islandia',
 '6584b7a0-1dd5-4aed-aa58-1f5df0c2a11a': 'Italy',
 '6614b794-9b07-4de2-837e-3aba6098ec7a': 'Niemcy',
 '67a0030a-e22f-4bdb-9e6a-c60d96fa808d': 'Nepal',
 '6b1c3c8b-fcbd-4f9a-8d8f-0e0e6d305a00': 'Czad',
 '6d10b186-3daf-452e-b48e-382e70b7f609': 'Botswana',
 '6da4f240-7fd9-4934-9689-f93f51cac24c': 'Litwa',
 '6dff9e42-9110-41c1-a2d1-c68e919c36c7': 'Norway',
 '6e01e9e6-bf10-4828-87d5-b1c98aae8e0d': 'Honduras',
 '6ec0db81-6558-43bf-9142-36d2e8bc321a': 'Haiti',
 '6f962b42-d29f-499c-87f6-e9546b8a0c92': 'Sri Lanka',
 '703ab25a-ab01-42a0-b7cd-c8f059b2e145': 'Gruzja',
 '70acdacb-a99d-48ce-9058-9948f29699dd': 'Korea Północna',
 '718f27b3-47ba-4c30-af01-febc9d241bcf': 'Portoryko',
 '724dbf07-a5e6-48be-bb56-f3dcdfc600e0': 'Kajmany',
 '726840c0-4fc5-4c7b-9900-9e995028994f': 'Reunion',
 '746be90c-2ad0-4a9c-9c61-c818e65f9024': 'Somalia',
 '758b8e9d-e8be-49c3-9d6f-4666bc75b7af': 'Macedonia',
 '75f50632-81a8-431c-b826-976e77573b08': 'Republika Zielonego Przylądka',
 '7759f57c-1e62-40ac-8c02-2b86242df436': 'Mauritius',
 '79825b0c-4532-4759-af83-e29465fb1898': 'Brunei',
 '79c15d47-cf6e-41a3-9c33-b9319ebfbabc': 'Kongo',
 '7abbf9c0-2b4b-4c46-b0c3-56cc2a943538': 'Wyspy Marshalla',
 '7bc66e23-af7a-4d1d-a72b-b745f9c430d4': 'Australia',
 '7c3c6900-cff1-44d1-8e05-b71f752b95d4': 'Meksyk',
 '7d224f92-a3ab-4dff-a2e6-392e1033eb87': 'Mozambik',
 '7fee7fcb-3792-4301-850c-6d9c12cb989d': 'Oman',
 '81fd52e2-f22a-4e27-83d9-6b45cc2d2946': 'Bulgaria',
 '82212d8f-c0dc-4ce2-874a-3fd1a9c41e67': 'Watykan',
 '8305b894-02ab-4edf-8b8d-80bc65300fe3': 'Urugwaj',
 '84ba792c-d86a-49a2-96a2-05d3d744cddf': 'Izrael',
 '85804edf-8e3a-4db7-b35e-4026ffcc0cc1': 'Kirgistan',
 '8594ada5-a15a-42f7-b242-9d8067c81307': 'country:NL',
 '86ada895-cdea-4fbd-bf7e-ade7848bcc4e': 'Filipiny',
 '887ff35e-edb0-4ba5-96c5-6bcc8efd43ad': 'Switzerland',
 '88cba7f0-879a-44af-9a25-4e086d43cff6': 'Grenada',
 '88fb57a1-0c75-40c0-99f1-eba2b10235d1': 'Guam',
 '8af68d9e-6fc5-4f86-876d-29962367a362': 'Wyspy Salomona',
 '8c94c5da-b5fb-4b55-8b3f-66195402bede': 'Zimbabwe',
 '8e3301c8-7bec-4040-a5bb-f2cc0830b3c5': 'Angola',
 '901ce5bd-d531-407d-b439-202b90afc0e3': 'Namibia',
 '907a5b8f-ce95-40f3-9e4e-99dca620ab6f': 'Ucraine',
 '910b960c-5760-44e3-9894-7eaeb2503bd6': 'Wyspa Norfolk',
 '91ea2629-5665-4f36-8d24-5c8b444d514f': 'Anguilla',
 '9259e39c-1399-4adb-a1f9-3c7bb6bbbc9d': 'Syria',
 '95291def-51d0-4704-a51c-4a14477497ad': 'Tokelau',
 '95e8fb98-c2da-4b45-95a1-a1d1f22e3383': 'Bonaire',
 '980d99fe-ea69-4e06-b546-86078e86edd9': 'Dżibuti',
 '98371c36-0ae0-4161-98ac-d884bed55489': 'Majotta',
 '985604a2-6dfe-42b2-b4d4-4150ac635121': 'Wyspy Dziewicze Stanów Zjednoczonych',
 '9a8cfad4-962b-40cb-834b-11271b325868': 'Sweden',
 '9c775095-e249-4677-bdd7-b28c9697be50': 'Japan',
 '9d7e7f13-f52d-4f4c-bf17-944976f017b6': 'Turkmenistan',
 '9f65dccd-5de2-44aa-a068-73eee026bf62': 'Barbados',
 'a280a38e-53e2-49ad-b2cc-35e2fbe106ea': 'country:US',
 'a3ab0727-6b63-4d7f-81ee-54448d52a536': 'Samoa Amerykańskie',
 'a56f0cb9-6307-4a15-b901-24c6354fc82c': 'Mikronezja',
 'a5c39b09-2f76-49b3-8159-c2b7f5cdd0b9': 'Czech Republic',
 'a6abd7b4-afa0-4653-a5b4-0f83e8c01ee6': 'Indonezja',
 'aa074dfa-b908-4b56-b6b7-230fe2fffeab': 'Łotwa',
 'ad60629b-6a56-462d-9c7b-3e68fd12b5ac': 'Estonia',
 'af6296bf-ba2b-4acc-ab07-0e2c7f2f6449': 'Fidżi',
 'af755660-861f-4f10-83f5-07128d3f7773': 'Wietnam',
 'af7cdff1-5323-4581-a06e-14a9b289d4ac': 'Ukraina',
 'afdf67ae-b1a1-445d-a7e8-0841fedf04b0': 'Papua-Nowa Gwinea',
 'b0233cad-fd3d-4140-b00b-28a045525410': 'Iran',
 'b078fcdf-5ab4-4abc-8d1d-569e944eca61': 'Spain',
 'b1608a60-0782-4a2d-843e-07352a77a5b7': 'Wyspy Owcze',
 'b2d9b207-a611-40de-b5ef-18580b3513d4': 'Laos',
 'b3719280-9f56-4d4f-8beb-cc34244c8d1f': 'Niger',
 'b3940a50-94c3-4418-9c75-cc9cd54fe854': 'Tadżykistan',
 'b3e7a9b7-f6ee-4e5c-9172-dbf9a3315fc6': 'Wyspa Man',
 'b757fdd3-7139-4e76-8309-164ce2bca39f': 'Erytrea',
 'b76e108b-e153-44ef-a65f-b9f3dd8aec53': 'Mjanma (Birma)',
 'bb4079c8-93a7-43bf-bcc1-f4bda2c0e8d0': 'Benin',
 'bca6412b-c525-4596-bfdb-c9f3251ce9e4': 'Cypr',
 'bd0ad58f-73fd-488e-974c-e82f21122cdb': 'Gambia',
 'be8e67e2-fea4-49a8-b3b9-4984c54856b9': 'Svalbard i Jan Mayen',
 'c19644c3-3236-4d0b-8027-f90bb4e2f806': 'Liberia',
 'c1c54103-80d2-46b8-9f48-16c95abe7bda': 'Andora',
 'c29315d3-7743-480d-ba69-783e11af73bf': 'Polska',
 'c29dd754-c598-487c-8ad8-0c373de535fa': 'Algieria',
 'c66b1c33-cccb-4245-9626-9392785af5a7': 'Gujana',
 'c6701151-aad3-47b8-bd71-0ac583fee4c7': 'country:DE',
 'c6a7670c-2141-42d1-9ee4-7483f56d418d': 'Niue',
 'c7f19d4b-851b-442d-8048-a7bcab2de895': 'Etiopia',
 'c8dfffd6-8499-489f-9285-9828ba14c802': 'Chile',
 'cafc43fa-275d-480e-b7f1-b998f2faebb5': 'Irak',
 'cb480387-3952-4039-befe-e2de6283f974': 'Malawi',
 'cc0ac9b5-2547-4e64-8ecf-8cb7f3ba878e': 'Malta',
 'cc787b20-1861-4f6a-8c09-645872c70da4': 'Kazachstan',
 'cd9b4e79-1455-454b-a950-ae242e610ffa': 'Liban',
 'cdb094e4-744e-4e16-86d4-cc01f243975b': 'Belize',
 'ce5e2109-9ae4-4462-8bd9-408e84f613c8': 'Brytyjskie Wyspy Dziewicze',
 'd1348208-9d84-49f2-b567-491545a5f22b': 'Uzbekistan',
 'd214ddf7-23df-4184-9c27-c27f3dae4229': 'country:HU',
 'd46507f2-a93b-4c65-bd39-8fb303b46cb1': 'Senegal',
 'd485df53-13ad-41bb-b48f-dd449a6b462d': 'Wenezuela',
 'd6258fc0-deb9-485a-864c-1782022d4fe2': 'Pitcairn',
 'd6d221c6-8669-4947-b2f7-60f211214380': 'Słowenia',
 'd71dc674-ccae-45b2-bba8-93c9f80acdc4': 'Tuvalu',
 'd88fe104-cdb4-4a3a-88c0-d133641a9052': 'Tonga',
 'd9351110-ed5b-4140-8d62-f88b2860c913': 'Peru',
 'd97f3191-6ab8-4327-916c-9f8a83d9696e': 'Zambia',
 'd9c6deaf-b31d-4092-8040-8b3b58f3d907': 'Brytyjskie Terytorium Oceanu Indyjskiego',
 'da28d548-d069-45e2-8234-5b1203a8056d': 'Liechtenstein',
 'dcbf781d-54a3-4734-9b69-a7e119d59fa5': 'Stany Zjednoczone',
 'e13ac228-178e-4d96-8ac8-37eae82e20d9': 'Saint Lucia',
 'e4daf024-a9f5-45db-9f32-327f9b7cbc2c': 'Kenia',
 'e7e435ef-9713-46fe-9814-40423c54165f': 'Palestyna',
 'e8d92c28-bd89-42b4-8977-553eaa2731f1': 'Turks i Caicos',
 'e9d4935d-ff76-4487-b6fe-c098e0681f47': 'Austria',
 'ec2176f2-7f11-4c01-abf0-76c940f4f6df': 'Panama',
 'ed62df6a-7c87-446a-bfe4-0aa55ad3d120': 'Jersey',
 'eee80e4c-8c23-485b-a66e-144e6dea129d': 'Serbia',
 'ef2169a0-95d7-407b-b47c-c3b15a4acf60': 'Samoa',
 'efb37ea3-6c83-48b9-b0ab-d683bb50f639': 'Wybrzeże Kości Słoniowej',
 'f1e5dc13-9b23-489b-a415-997a5b5efa9b': 'Gwinea',
 'f28c4596-92d1-4aef-b3e9-95fbd4c574c9': 'Kamerun',
 'f4554f4a-1794-491a-9d36-15dd531c2570': 'country:JP',
 'f50791cc-a488-4444-95c3-cfd986f20ee4': 'Saint Vincent i Grenadyny',
 'f6d23a2d-3a98-42e9-8dae-29ce47c9e05b': 'Malediwy',
 'f7e593d9-f9ed-40de-a7b2-b9a31cbeadde': 'Sudan',
 'f89a6abb-7c4b-4907-9af1-3d122a08491c': 'RFN',
 'f8f0c64f-e1b8-4790-8c39-219b7c915b41': 'Portugalia',
 'f91d860f-749e-4c50-9f47-2ad15c03b181': 'Jemen',
 'fa32b133-bf08-4849-9508-b3f8517d3b83': 'Kiribati',
 'fc2f6092-8593-45eb-8877-7684e2ac7ca2': 'Trynidad i Tobago',
 'fd02cb83-450d-4e6a-9d05-8e18b124ea00': 'Togo',
 'fee3c4a6-d925-43ce-8f71-6aadcc8e4449': 'Wallis i Futuna',
 'ff8fb8e4-4f80-44e9-a945-559e886a9a80': 'RPA'}